### ISSUE TITLE
Unterschiedliche Ergebnisse bei bibel range

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#100]
wenn man nach bible range sucht (z.b. Mk 16) kommen unterschiedliche Ergebnisse, je nachdem ob man die einfache Suche oder die Erweiterte Suche verwendet.
Richtig dürfte das Ergebnis der Erweiterten Suche sein (38 Treffer):
[Bibelstellensuche1.pdf](https://github.com/ubtue/ixTheo/files/123824/Bibelstellensuche1.pdf)

Falsch ist das Ergebnis der einfachen Suche (1113 Treffer):
[Bibelstellensuche2.pdf](https://github.com/ubtue/ixTheo/files/123827/Bibelstellensuche2.pdf)

**Comment by thefass** [comment]
Mc 16 hat anderes Ergenis als Mk 16.
Dazu falsche (findet Mc als Namensbestandteil)
https://ptah.ub.uni-tuebingen.de/Search/Results?sort=relevance&join=AND&lookfor0[]=Mc+16&type0[]=BibleRangeSearch&bool0[]=AND&illustration=-1&daterange[]=publishDate&publishDatefrom=&publishDateto=

**Comment by oobenland** [comment]
Die Bibelstellensuche bei der Erweiterten Suche war mal ein Versuch. Da ist nur noch der Eintrag übrig geblieben. Heißt: es wird eine normale Suche ausgeführt.
Das Problem: Bei der erweiterten Suche wird die Suchsyntax intern so abgeändert, dass spezielle Befehle für die Bibelstellensuche maskiert und nicht mehr ausgeführt werden.
Ich werde den Eintrag bei der Erweiterten Suche entfernen.

**Comment by thefass** [comment]
@oobenland: warte bitte nochmal mit dem Entfernen. Wir sehen uns ja am Freitag, da würde ich gerne nochmal das Thema Bibelstellensuche ansprechen

**Comment by oobenland** [comment]
Das ist nur eine Zeile in der Konfiguration, die auch noch im Verlauf von GitHub steht. Somit lösche ich kurz die Konfiguration, damit das nicht weiter verwirrend ist.
