### ISSUE TITLE
Fehler in Titelanzeige innerhlab der Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#111]
Betrifft den ersten Treffer:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter[]=ixtheo_notation_facet%3A%22NBC%22&sort=year

Dort wird neben dem Titel  "Gott als Vater eine Metapher"  fälschlicherweise nochmal die Autorin angezeigt "Angelika Strotmann"

**Comment by IxTheoKm** [comment]
"Angelika Strotmann" ist die Vorlageform, die erfasst ist in 245. 
Nicht erfasst ist die Form "von Strotmann, Angelika...". Wurde die zusätzlich erzeugt aus 100?

**Comment by ruschein** [comment]
Ich habe jetzt 245$c herausgenommen.  (Eine Änderung der Anzeige werden wir aber erst bein nächsten Datenimport sehen können.)  "Strotmann, Angelika 1956-" ist aus dem 100er Feld.  Ein "von ..." sehe ich nicht.

**Comment by IxTheoKm** [comment]
[Issue_111.docx](https://github.com/ubtue/ixTheo/files/130308/Issue_111.docx)

"von" s. Screenshot

Wenn die Vorlageform von der Vorzugsbenennung abweicht, fällt sie bei der Titelanzeige unter den Tisch. Sie ist nur im Internformat sichtbar. Ist das so gewollt?

**Comment by ruschein** [comment]
On 15/02/16 09:28, IxTheoKm wrote:
> Issue_111.docx <https://github.com/ubtue/ixTheo/files/130308/Issue_111.docx>
> 
> "von" s. Screenshot


Danke, aber in Zukunft bitte JPEG oder PNG für Screenshots verwenden.
"von" ist übrigens von VuFind und nicht aus den Daten.

> 
> Wenn die Vorlageform von der Vorzugsbenennung abweicht, fällt sie bei
> der Titelanzeige unter den Tisch. Sie ist nur im Internformat sichtbar.
> Ist das so gewollt?

Keine Ahnung.  Da müssen Sie die Theologen fragen.  Uns ist das egal.
Wir machen was Sie empfehlen.  Z.B. Regel:  Wenn XXX$y existiert, das
verwenden, sonst ZZZ$w verwenden.  Ich sollte hinzufügen, dass wir hier
nicht wissen was eine Vorlageform bzw. eine Vorzugsbenennung überhaupt sind.

> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/111#issuecomment-184109863>.
> 

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by IxTheoKm** [comment]
Der Autorenname aus 245 c = _Vorlageform_ muss vom Titel getrennt werden (vgl. #122) und darf keinesfalls in die Titelstichwortsuche einbezogen werden (vgl. #113).

![issue_111c](https://cloud.githubusercontent.com/assets/17004223/13079791/34fe8d9e-d4c6-11e5-91b4-823aeae51bb9.jpg)

--> Ausgeliefert : Antinomien der Agression in der theologischen Ethik / von Cornelia Richter
Die zusätzliche Zeile mit "von" entfällt


Wenn 245 c _nicht_ vorhanden ist, kann die Namensform aus 100 = _Vorzugsbenennung_ angezeigt werden (dann geht wohl nur die invertierte Form „Familienname, Vorname“; „von“ stört dann nicht)

![issue_111d](https://cloud.githubusercontent.com/assets/17004223/13080059/5f276dec-d4c7-11e5-9d30-3f7c5f2fa68b.jpg)

**Comment by thefass** [comment]
closed
