### ISSUE TITLE
Unterschiedliches Browser-Verhalten

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#112]
s. Ergebnisanzeige #111

Korrekte Anzeige über Firefox.

Beim Windows-Explorer öffnen sich die Titel beim Anklicken nicht bzw. nur vereinzelt. 
Der Scroll-Balken am rechten Rand fehlt. 
Im Suchfeld der einfachen Suche kann man nicht schreiben.

**Comment by jriedl** [comment]
Um welche Version des Windows Explorer handelt es sich denn?

**Comment by IxTheoKm** [comment]
Ich meinte natürlich Internet Explorer, sorry: 11.0.9600.18204

**Comment by oobenland** [comment]
Sollte nun behoben sein

**Comment by IxGe** [comment]
Hier im Institut verwende ich die gleich Version des Explorers - jetzt kann ich problemlos navigieren, der Scrollbalken ist auch da.
Bei jedem Schritt taucht allerdings auf:
![inhalt](https://cloud.githubusercontent.com/assets/17196047/13141506/ffc12ce0-d637-11e5-9f9d-0cd0b0b03324.PNG)

Liegt das an der individuellen Einstellung an meinem Gerät oder am VuFindOpac - wie bekommt man das wieder los?

**Comment by oobenland** [comment]
Die Benachrichtigung lag daran, dass die Einbindung von Piwik über eine unsichere Verbindung ging. Sollte inzwischen behoben sein, oder spätestens heute Mittag.

**Comment by IxTheoKm** [comment]
Bei mir jetzt o.k.
@IxGe bitte im Institut prüfen

**Comment by IxGe** [comment]
Auch vom Institut aus sieht jetzt alles gut aus (Navigation, Scrollbalken, Schreibfeld).
Diese lästige Meldung ist auch nicht mehr da.

**Comment by IxTheoKm** [comment]
Im Internet-Explorer gibt es keinen Feedback-Button

**Comment by IxTheoKm** [comment]
Feedback-Button jetzt vhd.
