### ISSUE TITLE
Falsche Schlagwortanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#113]
Der Autor wird fälschlich als Schlagwort angezeigt.
Bsp. Winkler, Klaus

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=winkler%2C+klaus&type=Author&limit=20&sort=relevance

**Comment by jriedl** [comment]
"Winkler, Klaus" wird im Feld 601 angegeben, welches derzeit zur Menge der Felder für die Schlagworte gehört.

**Comment by IxTheoKm** [comment]
In manchen Fällen werden für Schlagwörter die GND-Nummern angezeigt:

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=bulle&type=Subject&limit=20&sort=relevance

**Comment by IxTheoKm** [comment]
Die aus Titelstichwörtern erzeugten Schlagwörter sollten nicht angezeigt werden, wenn korrekte, intellektuell vergebene Schlagwörter vorhanden sind.
In der Liste Bsp. 4 "Nazareth". Darum geht es in dem Werk nicht:
![issue_113](https://cloud.githubusercontent.com/assets/17004223/13081524/731d4ce4-d4cd-11e5-8f37-1aa0264f1c41.jpg)
![issue_113b](https://cloud.githubusercontent.com/assets/17004223/13081607/b9e27e38-d4cd-11e5-952f-a9d499416c73.jpg)

**Comment by IxGe** [comment]
Wird in der Kurztitelliste nur ein, bzw. das erste Schlagwort angezeigt, auch wenn eine ganze Folge vorhanden ist? Also nur das 1. 689?
![doping4](https://cloud.githubusercontent.com/assets/17196047/13149874/7cdd3cc0-d663-11e5-9a3d-189becbac155.PNG)

**Comment by thefass** [comment]
@IxGe das, was Ihnen als das erste Schalgwort erscheint, ist keine Anzeige der Schlagwörter an dieser Stelle, sondern ein highlighting des Suchbegriffs. Hier wird also gezeigt, dass das Suchwort auch noch in den Schlagwörtern vorkommt. Ob wir das so wollen, müssen wir noch diskutieren
