### ISSUE TITLE
Bibelstellenbezeichnungen englisch und deutsch

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#115]
1 Cor 15 wird nicht als 1. Kor 15 (1.Korinterbrief, 15. Kapitel) erkannt.
1 Cor 15 findet man in Feld 245 1 0 a
(https://ptah.ub.uni-tuebingen.de/Record/400880415)

**Comment by IxGe** [comment]
An diesem Beispiel ist auch überraschend:
statt  Paulus, Apostel, Heiliger, Korintherbrief 
wird Paulus, I., Apostel, Heiliger, Korintherbrief ... angezeigt; d.h.
aus SWB $PPaulus$lApostel, Heiliger
wird im Internformat : |D u  |0 (DE-588)4123919-2  |0 (DE-576)209563753  |2 gnd  |a Paulus  |b I.  |c Apostel, Heiliger 
=> das System macht aus $l fälschlicherweise |b I.

**Comment by oobenland** [comment]
Die Bibelstellensuche nach "1. Kor 15" und "1 Cor 15" enthält als Treffer 33 den genannten Record:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=1.+Kor+15&type=BibleRangeSearch&page=2

Der Problematik mit dem Unterfeld gehen wir nach. Das ist wirklich komisch, liegt aber leider nicht in unserer Hand...
