### ISSUE TITLE
stark abweichende Suchergebnisse "Alle Felder" - "Bibelstellensuche"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#117]
Bei der Suche nach Ps 22,2 (Psalm 22 Vers 2)
erhalte ich über "Alle Felder" 18 Ergebnisse 
![ps 22 alle felder](https://cloud.githubusercontent.com/assets/16759964/13050664/2e69e9fa-d3f5-11e5-8473-2eaeb0dca9fa.png)
an welchen Stellen Ps 22,2 vorkommt, ist markiert. Teilweise wird aus Ps 22,2 - Ps 2,2.

wenn ich über die Bibelstellensuche nach Psalm 22,2 suche, erhalte ich 1.284 Ergebnisse
![bbs 22 2](https://cloud.githubusercontent.com/assets/16759964/13050700/6a5dc6f2-d3f5-11e5-96fd-350e40ead295.png)
inwiefern in den Ergebnissen Ps 22,2 vorkommt, ist nicht gelb markiert.

im Internformat des ersten Titels begegnet mir nichts direkt zu Psalm 22, lediglich "Psalmen" in Kategorie 630 unter t (https://ptah.ub.uni-tuebingen.de/Record/029835518)

**Comment by oobenland** [comment]
Die Bibelstellensuche wird inzwischen nur ausgeführt, wenn dies explizit gewünscht ist (also durch die Auswahl). Somit wird bei "Allen Feldern" wirklich alle Felder durchsucht (Highlighting ist dabei aktiviert). Bei der Bibelstellensuche wird nur Feld 801 durchsucht (deshalb die Trennung, da das nicht alle Felder sind). Ps 22,2 wird zu 5602202:5602202 übersetzt und überschneidet sich mit 5600000_5699999. Aber dadurch dass das ein Zahlenwert ist kann man kein Highlighting durchführen.

**Comment by thefass** [comment]
@Mannsperger: das Zahlensystem besprechen wir am Freitag
@oobenland, @ruschein: In der Kaskade der hierarchischen Ergebnisdarstellung bei einer Suche nach einer konkreten Stelle sollten wir die Range 5600000_5699999 herausnehmen. Das ist nämlich insofern verwirrend (auch wenn die Idee dazu von mir kam) als bei Nichttreffern von konkreten Versen oder ganzen Kapiteln dann immer eine riesige Treffermenge da ist und man das gar nicht durchschauen kann, warum das so ist. Und man dann immer auf der Suche ist, was die Ergebnismenge mit der Suchanfrage zu tun hat.
Die Hierarchie sollte also so sein:
1. Exakte Treffer: also genau Ps 22,2 (5602202:5602202)
2. Treffer, in denen Ps 22,2 enthalten sind
z.B. Ps 22,1-10 (5602201:5602210) oder Ps 21-25 (5602100:5602500) oder Ps 21,12-22,10 (5602112:5602210) oder Ps 22,2.6.10 (5602202, 5602206, 5602210)
3. Treffer aus dem zugehörigen Kapitel ( im Falle der Psalmen, die keine Kapitel haben: des ganzen Psalms)
Ps 22 (5602200:5602299)
Beispiel aus Nicht-Psalmen: Mk 5,1-20 >>> Mk 5 (xx0500-xx0599)

**Comment by Mannsperger** [comment]
Wenn ich über die Bibelstellensuche nach Ps 22 suche, bekomme ich Ergebnisse, die mit Psalm 22 zu tun haben:
![ps 22](https://cloud.githubusercontent.com/assets/16759964/13174553/b1e131aa-d704-11e5-9c92-e73fe63362ff.png)
wenn ich aber nach Ps 22,2 suche (also Psalm 22 Vers 2) kommen Ergebnisse ganz allgemein zu Psalmen:
![ps 22 2](https://cloud.githubusercontent.com/assets/16759964/13174562/c895e760-d704-11e5-9b0e-5d91ac050b89.png)

**Comment by oobenland** [comment]
Den Wunsch von Martin habe ich jetzt umgesetzt:
Es werden jetzt nur dann Treffer, die das gesuchte Buch betreffen, angezeigt, wenn man nach einem kompletten Buch sucht (Also bei der Suche nach "Ps"). Wenn man ein Kapitel mit angibt ("Ps 22") oder ein Vers ("Ps 22,2") werden diese Treffer nicht mehr angezeigt, sonder nur Treffer, die passende Kapitel oder Verse behandeln.

**Comment by thefass** [comment]
super, das ist jetzt viel besser.

Was noch nicht so gut ist, ist die Sortierung. Siehe Suche Mk 5,21-43
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Mk+5%2C21-43&type=BibleRangeSearch

Dort sind die Treffer 7 - 17 Titel, die jeweils viele Kapitel umfassen (meist Mk Kapitel 1-8).
Trefer 18-21 und 23-24 sind Titel, die an Mk 5,21-43 viel näher dran sind und vor Treffer 17ff sein müßten

**Comment by Mannsperger** [comment]
Über WinIBW findet man zwei Titel direkt zu Ps 22,2. 
![ibw 221](https://cloud.githubusercontent.com/assets/16759964/13220275/8e58683e-d975-11e5-8e05-2bdfe62bdcb6.png)
![ibw 222](https://cloud.githubusercontent.com/assets/16759964/13220278/9298194e-d975-11e5-9f40-a6efc23f8fa2.png)
diese tauchen nicht in den ersten 40 Treffern über die Bibelstellensuche auf, sind jedoch in Ptah vorhanden, auch direkt mit 22,2 in 689 gekennzeichnet. Deswegen wundert es mich, dass sie nicht in der Suche sofort als erste Ergebnisse erscheinen:
![ps22p1](https://cloud.githubusercontent.com/assets/16759964/13220302/c40d7dca-d975-11e5-8572-9a61e241503f.png)
![ps 22p2](https://cloud.githubusercontent.com/assets/16759964/13220307/c79375f8-d975-11e5-997c-c1468578b6cc.png)

**Comment by thefass** [comment]
funktioniert
