### ISSUE TITLE
Farbgestaltung

### ISSUE THREAD

**Issue by IxGe** [ubtue/ixTheo#118]
Grundsätzliche Frage:
Die Farbgestaltung Dunkelblau - Hellblau - Weiß entspricht sehr stark dem Auftritt aller Produkte aus dem Thieme-Verlag : https://www.thieme.de/de/index.htm
Habe nur ich diese Assoziation? Gibt es da (marken-)rechtliche Probleme?

**Comment by oobenland** [comment]
Ich habe diese Assoziation nicht. Ich kannte diese Website davor aber auch nicht.
Das Design ist bis jetzt nur ein Prototyp um in irgendeiner Form eine einigermaßen ansehnliche Präsentation zu ermöglichen.
Zurzeit läuft ein Wettbewerb auf http://www.designenlassen.de um ein hübsches Design zu bekommen. Ich bin schon echt gespannt was da raus kommt ;-)

**Comment by thefass** [comment]
Ich auch nicht. Design ist noch nicht festgelegt. Wir brauchen aber schon mal etwas Ansehliches, so wie oobenland das schon gesagt hat.
