### ISSUE TITLE
Abtrennung Zusatz in Kurz- und Vollanzige

### ISSUE THREAD

**Issue by IxGe** [ubtue/ixTheo#122]
s. https://ptah.ub.uni-tuebingen.de/Search/Results?sort=relevance&join=AND&lookfor0%5B%5D=winkler%2C+klaus&type0%5B%5D=Author&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&illustration=-1&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=

statt: im 4. Treffer:
Begräbnis-Homiletik Trauerhilfe, Glaubenshilfe und Lebenshilfe für Hinterbliebene als Dienst der Kirche Bernhard Klaus u. Klaus Winkler 

sollte angezeigt werden:

Begräbnis-Homiletik : Trauerhilfe, Glaubenshilfe und Lebenshilfe für Hinterbliebene ... 

=> aus 245  |a Begräbnis-Homiletik :  |b Trauerhilfe, Glaubenshilfe und Lebenshilfe für Hinterbliebene als Dienst der Kirche /  |c Bernhard Klaus u. Klaus Winkler 

"einfach"  |a |b |c weglassen - dann stehen schon die richtigen : /  ... diese dann auch anzeigen

**Comment by IxGe** [comment]
vgl. die Lösung im VuFind-Katalog plus für diesen Titel:
![winkler](https://cloud.githubusercontent.com/assets/17196047/13078364/bcf9a93e-d4be-11e5-9374-383767f3a261.PNG)

**Comment by oobenland** [comment]
Ich verstehe nicht, was falsch ist. Wir sollen |a, |b, |c weglassen?

**Comment by IxTheoKm** [comment]
IxGe meint, dass die Unterfelder |a |b und |c jeweils durch die Zeichen getrennt werden sollen, die schon im MARC-Feld stehen. Also nur die _Buchstaben_ a, b und c weglassen.

Die Anzeige sieht dann so aus wie oben beschrieben:
**Begräbnis-Homiletik : Trauerhilfe, Glaubenshilfe und Lebenshilfe für Hinterbliebene / Bernhard Klaus u. Klaus Winkler**

Im Moment werden 245 a, 245 b und 245 c (Haupttitel, Zusatz zum Sachtitel und Verfasser in Vorlageform) ungetrennt als ein "Bandwurm" angezeigt.

**Comment by oobenland** [comment]
Ok, das bekommen wir hin :-)

**Comment by IxGe** [comment]
Offensichtlich wird der ":" als Abtrennung des Zusatzes in der Kurztiteliste nicht angezeigt, wenn er unmittelbar nach dem unterlegten Suchbegriff steht : 
![doping3](https://cloud.githubusercontent.com/assets/17196047/13148856/4d577a5a-d65f-11e5-9773-360bdce3518d.PNG)

**Comment by thefass** [comment]
gelöst ist das Problem in der Volltitelanzeige
nicht gelöst ist es in der Kurztitelanzeige:
Bsp:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Die+ethischen+Grundfragen+10+Vortr%C3%A4ge%22&type=AllFields&sort=year

**Comment by oobenland** [comment]
Hier liegt jetzt das Problem an dem Highlighting. Bei #131 wird das auch ein Problem sein und auch behoben werden müssen. Kann dieses Issue somit geschlossen werden?
![bildschirmfoto vom 2016-02-24 01 26 31](https://cloud.githubusercontent.com/assets/1352796/13271519/beaedfce-da95-11e5-8a9c-e554575ae108.png)

**Comment by IxGe** [comment]
Wenn ihr das Problem im Auge behaltet, kann das issue geschlossen werden.

**Comment by thefass** [comment]
@oobenland bitte dann ein eigenes Issue mit dem Problem aufmachen, so dass wir das nicht aus den Augen verlieren
