### ISSUE TITLE
Anzeige mehrerer Autorennamen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#124]
Bitte mehrere Autorennamen in der Titelanzeige wie in 245 c durch Semikolon trennen, nicht durch Komma. Man erkennt sonst nicht immer, wo der Name des folgenden Autors beginnt (insbesondere bei Doppelnamen oder persönlichen Namen ohne Inversionskomma):
![autoren](https://cloud.githubusercontent.com/assets/17004223/13078302/5f9544f6-d4be-11e5-87e4-befe3ed17267.jpg)

**Comment by IxTheoKm** [comment]
Trennung ist jetzt wieder mit Komma und damit so unübersichtlich wie am Anfang

**Comment by IxTheoKm** [comment]
In der Kurzanzeige ist es o.k., in der Vollanzeige nicht:

https://ixtheo-test.de/Search/Results?join=AND&lookfor0[]=cahill&type0[]=Author&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&bool0[]=AND&daterange[]=publishDate&publishDatefrom=&publishDateto=&limit=20

https://ixtheo-test.de/Record/443240388

**Comment by mtrojan-ub** [comment]
Müsste auf ptah jetzt passen, siehe:
https://ptah.ub.uni-tuebingen.de/Record/443240388

**Comment by IxTheoKm** [comment]
Ist jetzt o.k.
