### ISSUE TITLE
Fehlgeleitete Verlinkung

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#127]
Auf der Seite https://ptah.ub.uni-tuebingen.de/Search/Advanced gibt es die "Hilfe zur erweiterten Suche".
Darin gibt es im ersten Absatz einen Link auf erlaubte Suchoperatoren.
Der Link führt aber fälschlicherweise immer auf die Startseite. Das ist übrigens auch bei der Krimdok so

**Comment by oobenland** [comment]
Ich kann nicht erkennen, was falsch sein soll. Ich sehe Links, die auf die erweiterte Suche, genauer auf eine Überschrift verweist.
Könnte es sein, dass das ein Browserproblem ist? Hast du das Problem im Safari entdeckt? Oder hast du es auch mit anderen Browsern getestet?

**Comment by thefass** [comment]
Nein mit dem Firefox (43.0.2)
Der Link ist auf der Hilfeseite im ersten Absatz (Suchoperatoren).
Ich habe mal die Linkadresse kopiert:
https://ptah.ub.uni-tuebingen.de/Search/Home?topic=search
Der müßte aber auf die Hilfseite der Suchoperatoren führen

**Comment by oobenland** [comment]
Ist gefixt, danke.

**Comment by thefass** [comment]
Ja, funktioniert.
kannst Du bitte auch noch einen Link zurück einbauen, so dass man auch wieder zur Hilfeseite zurückkommt?

**Comment by oobenland** [comment]
Ich habe mir das nochmal angeschaut. Ich glaube dass das aufwendiger ist, als wenn der Benutzer die Hilfeseite einfach schließt und wieder die andere Seite öffnet.
Das Problem ist, dass man ein Zurück-Knopf einbauen müsste, der nur erscheint, wenn man von der einen Hilfeseite zur anderen wechselt.

**Comment by thefass** [comment]
ok, lassen wir es erst einmal so, auch wenn das nicht optimal ist.
