### ISSUE TITLE
Eingrenzen in der erweiterten Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#128]
Ich gehe davon aus, dass die Auswahlkriterien beim Eingrenzen in der erweiterten Suche wie folgt eingerichtet werden, richtig?

"Signatur" wird IxTheo-Notation
"Sprachen" werden deutsch angegeben
"Format" wird analog zu den Facetten bei der Titelanzeige bestückt (Unterschied z.B. derzeit "Braille" gegenüber "Blindendruck" bei der Titelanzeige)

![eingrenzen](https://cloud.githubusercontent.com/assets/17004223/13141174/2eed4d84-d636-11e5-8431-2613e5073dfa.jpg)

**Comment by thefass** [comment]
es ist schon mit der IT besprochen wie etwas bezeichnet wird

**Comment by thefass** [comment]
geprüft werden muss in Bezug auf diese Issue nur noch, ob die Bezeichnungnen in der Facette "Format" mit der Bezeichnung in "Format" in der Erweiterten Suche übereinstimmen.
die anderen Punkte von IxTheoKm sind geklärt

**Comment by oobenland** [comment]
Die Facetten sind nun angepasst.

**Comment by thefass** [comment]
@oobenland Bitte noch auf der Seite der erweiterten Suche:
https://ptah.ub.uni-tuebingen.de/Search/Advanced
die Bezeichnungen der Klassen der IxTheo Klassifikation mit anzeigen
