### ISSUE TITLE
Vorgaben für die Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#131]
Regel 1
Trennung von Hauptitel (245$a) vom Untertitel (245$c oder 245$p) folgendermaßen:
Leerzeichen : Leerzeichen 
in Analogie zur Volltitelanzeige
Bsp: https://ptah.ub.uni-tuebingen.de/Record/05720666X

**Comment by thefass** [comment]
2.
das "von" vor dem Autor soll nun doch bleiben

**Comment by thefass** [comment]
3. 
Anzeige von bis zu 3 Autoren in der selben Zeile getrennt durch Semikolon und Leerzeichen
Felder der AUTOREN:
1. AUTOR: 100
2. WEITERE AUTOREN: 700
3. Wenn mehr als zwei Autoren in 700 stecken, dann die weiteren Autoren nicht anzeigen, sondern Leerzeichen und drei Punkte (...)
4. Wenn 100 und 700 nicht vorhanden, dann gegebenfalls die Körperschaft aus Feld 110. Falls nicht vorhanden dann aus Feld 710

**Comment by thefass** [comment]
Regel 4
die Einleitung "veröffentlicht" soll prinzipiell entfernt werden

**Comment by thefass** [comment]
Regel 5
gilt für unselbständige Werke (Artikel, Rezensionen):
Angabe der übergeordneten Werke, alles in einer Zeile eingeleitet mit "in: "
Bsp:
in: ZeitschriftXY, Band(Jahr), Heft, Seite(n)
Reihenfolge der Felder
773$a $g $w
Achtung: in $w steht nach der Info in der Klammer die PPN Nummer. die PPN als Link einer Suche nach dieser PPN umsetzen.
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/455078785
Dort seht Ihr im Internformat dies in der 773$w

**Comment by thefass** [comment]
Regel 6
gilt für alles andere:
Angabe des Verlages und des Erscheinungsjahres:
Reihenfolge der Felder:
260 $a $c
Achtung: Bei der Anzeige Leerzeichen zwischen $a und $c einfügen

**Comment by IxTheoKm** [comment]
Ergänzung zu Regel 1 nach Rücksprache mit thefass:

Wenn 245 ... $b = [Leerzeichen Gleichheitszeichen Leerzeichen] vorhanden ist, dann soll kein Doppelpunkt vorangestellt werden.
(Dies betrifft auch die Volltitelanzeige!)
Bsp.:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A451444574&type=AllFields&limit=20&sort=relevance
bzw.
https://ptah.ub.uni-tuebingen.de/Record/451444574

**Comment by oobenland** [comment]
Regel 1: Bis auf Highlighting umgesetzt
Regel 2: Nichts zu tun
Regel 3: 
Regel 4: 
Regel 5:
Regel 6:

**Comment by thefass** [comment]
Präzisierung zu Regel 3
in der 700 stecken auch die Herausgeber.
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/424648148
bitte auch $e anzeigen

**Comment by socheres** [comment]
@jriedl Korrekturvoschlag zu Regel 5: [Komma und Spatium](https://cloud.githubusercontent.com/assets/1545743/13442740/fe860402-dffd-11e5-9c8b-629225a0220f.PNG)

**Comment by jriedl** [comment]
Es wird jetzt Komma und Leerzeichen eingefügt

**Comment by socheres** [comment]
@jriedl das Komma kommt nach Zeitschriftentitel und nicht nach Bandzählung.

**Comment by thefass** [comment]
Issue kann geschlossen werden, wenn die Ergänzung zu Regel 1 umgesetzt ist (siehe Kommentar IxTheoKm vom 19.2.

**Comment by IxTheoKm** [comment]
Ergänzung zu Regel 1 ist umgesetzt
