### ISSUE TITLE
unterschiedliche "Trefferhierarchie"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#138]
der Titel mit der PPN 453236464 erscheint nicht in den ersten 580 Treffern über die Bibelstellensuche nach Lk 7,1-17, obwohl er in Ptah gelistet ist und unter 689 auch Lk 7,1-17 zu finden ist
![689 7 und 8](https://cloud.githubusercontent.com/assets/16759964/13177734/67f3c23a-d71b-11e5-895f-dc2a2f4a6605.png)

Noch eine andere Frage in diesem Zusammenhang:
Kann man sich alle Suchergebnisse auch auf einer Seite anzeigen lassen, um z.B. nicht bei 866 Treffern 44mal weiterklicken zu müssen?

**Comment by thefass** [comment]
Die Stelle unter 689 ist nicht in die numerische Angabe in 801 umgesetzt.
Vermutung/Frage: der Satz hat schon die neue RDA Struktur. Vermutlich findet der jetzige Algorithmus ihn deswegen nicht?
@oobenland @ruschein Könnt Ihr bitte Euren Algorithmus prüfen
Die neuen Sätze nach RDA beginnen immer mit $tBibel
Siehe:
689 	0 	1 	|D u  |0 (DE-588)1069926078  |0 (DE-576)429613415  |2 gnd  |t Bibel  |p Lukasevangelium  |n 8,40-56  

**Achtung!**
Solange nicht alle Bibelstellen in das neue RDA Format überführt sind müssen wir mit beiden Versionen arbeiten können

**Comment by Mannsperger** [comment]
Bei der Suche nach "Mk 15" (Markusevangelium 15)
erhalte ich über WinIBW vier Treffer, die alle nicht auftauchen in der Suche nach Mk 15 über die Bibelstellensuche, bei den ersten beiden Titel befindet sich die Information in 689 $t und $n
bei den anderen beiden Titeln in 630 §t $n
![afre](https://cloud.githubusercontent.com/assets/16759964/13178259/175958b4-d71e-11e5-8a10-87bac3e5c668.png)
![roswsse](https://cloud.githubusercontent.com/assets/16759964/13178258/1758edac-d71e-11e5-88d5-09c7b1dd0785.png)
![patte](https://cloud.githubusercontent.com/assets/16759964/13178261/1af823ec-d71e-11e5-816b-45e66a1bddbb.png)
![roswsse](https://cloud.githubusercontent.com/assets/16759964/13178262/1af8a010-d71e-11e5-8319-5e9717214be7.png)

**Comment by Mannsperger** [comment]
s. für die Ergebnisse auf ptah: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Mk+15&type=BibleRangeSearch&filter[]=publishDate%3A%22[2015+TO+2015]%22&limit=20&sort=relevance

**Comment by oobenland** [comment]
Ich habe etwas gebraucht um zu verstehen, warum diese Ergebnisse nicht angezeigt werden. In der genannten Suche ist das Veröffentlichungsdatum auf das Jahr 2015 eingeschränkt. Nimmt man diese Einschränkung raus, so sind die ersten drei Ergebnisse die fehlenden Treffer (@Mannsperger du hast "Il grido di Gesú in croce" doppelt angegeben).

**Comment by thefass** [comment]
ja das war tricky. Wir sollten nochmal überlegen, was wir (optisch) machen können, so dass man solche Einstellungen nicht übersieht. Ist mir nämlich auch schon mehrmals passiert
