### ISSUE TITLE
Paginierung

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#139]
@Mannsperger wrote:
Noch eine andere Frage in diesem Zusammenhang:
Kann man sich alle Suchergebnisse auch auf einer Seite anzeigen lassen, um z.B. nicht bei 866 Treffern 44mal weiterklicken zu müssen?
**Das ist tatsächlich ein Problem.**
@ruschein @oobenland @jriedl 
 Eure Kollegen im Nebenzimmer haben für unser IxTheo Zeitschriftensystem das Problem gelöst.
Dort kann jeder die Anzahl derangezeitem Menge der Titel selbst bestimmen )30,50,100,500,1000)

**Comment by oobenland** [comment]
Wenn nur alles so einfach wäre, wie das ;-)
Sollte ab heute Mittag testbar sein.

**Comment by Mannsperger** [comment]
Beim Klicken durch die 50 momentanen Ergebnisse zu Psalm 22,2 trat eine Fehlermeldung auf, als ich die dritte Ergebnisse Seite anklicken wollte, ich würde euch bitten, das zu beheben:
![ps 22 2 2202](https://cloud.githubusercontent.com/assets/16759964/13220086/57a791bc-d974-11e5-874e-e9c5e1587a45.png)
![ps 22 2 3 fehler](https://cloud.githubusercontent.com/assets/16759964/13220089/5ac9e7d2-d974-11e5-85d4-fe4ac8147bb6.png)

**Comment by oobenland** [comment]
Den Fehler muss ich prüfen. Die Auswahlmöglichkeit für die Länge der Ergebnisliste ist drin. Standardmäßig sind folgende Wahlmöglichkeiten gegeben: 10,20,40,60,80,100
Ich kann das aber auch gerne auf 10, 50, 100 einschränken. Mehr wie 100 macht aus mehreren Gründen kein Sinn.

**Comment by oobenland** [comment]
Ok, es scheint, dass der Index inkonsistent ist. @ruschein Könntest du folgende URL aufrufen und dann neu indizieren? (muss vorher noch richtig angepasst werden)
http://host:port/solr/core/update?stream.body=<delete><query>*:*</query></delet‌​e>&commit=true

**Comment by ruschein** [comment]
@jriedl Da Du gestern einen neuen Import gemacht hast, weise ich es Dir zu.

**Comment by thefass** [comment]
@oobenland  bitte auf 10, 50, 100 einschränken

**Comment by thefass** [comment]
Korrektur: bitte 10, 20, 50, 100 
default:20

**Comment by jriedl** [comment]
Ist angepasst

**Comment by jriedl** [comment]
@oobenland Die Indizierung ist durchgelaufen, der Fehler ist aber geblieben. Ein manueller Aufruf der Debug-Ausgaben der Solr-Kommunikation führt zu sinnvoll aussehenden Ergebnissen, deshalb ist es vermutlich kein Index-Problem.

**Comment by oobenland** [comment]
Der Fehler scheint behoben zu sein.

**Comment by thefass** [comment]
@Mannsperger bitte testen

**Comment by Mannsperger** [comment]
Es funktioniert wunderbar.
