### ISSUE TITLE
Fehlende Treffer in der Bibelstellensuche

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#140]
WinIBW findet direkt zu Joh 1,23 folgenden Titel:
![joh 1 23](https://cloud.githubusercontent.com/assets/16759964/13221028/7e4d6d3c-d979-11e5-8396-572b9345c332.png)
dieser ist über Ptah auffindbar, wird jedoch nicht bei der Bibelstellensuche nach Joh 1,23 angezeigt (jedoch 36 andere Treffer), obwohl in 689 0 3 n und 801 die Information enthalten ist.
https://ptah.ub.uni-tuebingen.de/Record/426836111
![joh 1 23p](https://cloud.githubusercontent.com/assets/16759964/13221173/41cd1154-d97a-11e5-9046-acc3dd22f1eb.png)
Könnte es daran liegen, dass sowohl Joh 1,23 als auch Joh 1,1-3 als Bibelstellen in die Felder aufgenommen wurden?

**Comment by Mannsperger** [comment]
Ich kann 1 Joh , 2 Joh und 3 Joh separat suchen, die Suche 1-3 Joh (1. bis 3. Johannesbrief) funktioniert auch, aber die Suche nach 1-2 Joh bzw. 2-3 Joh funktioniert nicht. Diese Art der Suche könnte hilfreich sein, falls jemand z.B. nach Literatur nur zu dem 1. und dem 2. oder 2. und 3. Johannesbrief suchen möchte.
![2-3 joh](https://cloud.githubusercontent.com/assets/16759964/13223642/63139fda-d985-11e5-88b6-cbda20f1577f.png) (s. https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=2-3+Joh&type=BibleRangeSearch&limit=20&sort=relevance)

**Comment by IxGe** [comment]
Johannesbrief 1.-2. gibt es als Schlagwort noch nicht, es gibt keinen Treffer im IxTheo.
Johannesbrief 2.-3. gibt es in der GND  !215855736! - hierzu gibt es einen Treffer im SWB !110491564!, der aber nicht hier in ptah geladen ist - warum nicht? Oder warum finde ich diesen nicht?

**Comment by thefass** [comment]
Jetzt war @IxGe schneller als ich.
@IxGe Darf ich Sie bitten, Frau @Mannsperger zu schreiben wie man diese Bücherübergreifenden Normsätze in der WinIBW findet. Danke!

**Comment by thefass** [comment]
Ich finde den Satz den von @IxGe vermissten Satz mit Eingabe in den Suchschlitz id:110491564 in ptah:
https://ptah.ub.uni-tuebingen.de/Record/110491564

**Comment by IxGe** [comment]
Jetzt weiß ich, warum ich den Titel nicht gefunden habe, bei einfachen Suche war noch  "Bibelstellen" eingestellt - das ist etwas ungewöhnlich, da man bei einem solchen Suchschlitz eine Freitextsuche über alle Felder erwartet, dass diese voreingestellt ist oder darauf bei einer neuen Suche zurückspringt
![naaste](https://cloud.githubusercontent.com/assets/17196047/13224896/ec08222a-d98a-11e5-9f28-3c84d2bf7c0b.PNG)

Man findet im SWB die Johannesbriefe 1-2 oder 2-3 je nachdem ob sie in der alten oder neuen Form angesetzt sind
sc sp Johannesbrief i  (="alt")

![johann 1](https://cloud.githubusercontent.com/assets/17196047/13224957/23949cf0-d98b-11e5-8b48-d883df9fa41b.PNG)

oder
sc sp Bibel johannesbrief 1. (neu)

![johann 2](https://cloud.githubusercontent.com/assets/17196047/13224998/4c0edd9e-d98b-11e5-9edd-9c28715d1f94.PNG)

**Comment by IxGe** [comment]
... und ich vergaß: bei diesem Titel
https://ptah.ub.uni-tuebingen.de/Record/110491564
 hat die Anzeige der Schlagwortfolgen

![anz1](https://cloud.githubusercontent.com/assets/17196047/13225282/6f998eb6-d98c-11e5-8328-c95a3d07ce97.PNG)

 mit der Verschlagwortung im SWB und auch mit der im internen Format vorhandenen sehr wenig zu tun:
![an2](https://cloud.githubusercontent.com/assets/17196047/13225295/7c65bf66-d98c-11e5-8c12-8f627f8d7a21.PNG)

**Comment by IxGe** [comment]
... jetzt habe ich wieder zu schnell abgeschickt:

Woher wird die erste Schlagwortfolge genommen oder konstruiert?
Bibel / Kommentar
kann ich im internen Format  oder im SWB nicht nachvollziehen.

Werden nur zwei Folgen angezeigt?

Und warum dann die letzte?

Oder liegt es tatsächlich daran, dass das System die Bibelstellen in der RDA-Form nicht erkennen und verabeiten kann? Dass zwar |t Bibel verarbeitet werden kann, aber alle anderen Bibelstellen  ...|p nicht?

Dann muss, das dringend behoben werden!

**Comment by thefass** [comment]
muss gelöst werden, aber nicht mehr bis zum Kolloquium, da die Volltextanzeige insgesamt überarbeitet werden muss

**Comment by IxGe** [comment]
Der rote aDis-Katalog und der VuFind Katalog + bekommen das auch (noch) nicht hin.
Lediglich der blaue Opac - mal wieder - kann die neuen rda-Ansicht korrekt anzeigen.

![naaste2](https://cloud.githubusercontent.com/assets/17196047/13245276/54009f16-da0c-11e5-9dac-3d977302cbcb.PNG)

**Comment by oobenland** [comment]
> @IxGe:
> Woher wird die erste Schlagwortfolge genommen oder konstruiert?
> Bibel / Kommentar
> kann ich im internen Format oder im SWB nicht nachvollziehen.

Hier sollten wir korrekte Regeln bekommen. Als wir die Schlagwortfolgen implementiert haben, hatten wir nur wenige Beispiele. Unsere (fehlerhafte) Regel:

- Für jedes 689-Feld:
  - Durchsuche nach Unterfeld 2 mit Inhalt 'gnd'
  - Nehme alle folgenden Unterfelder, wenn es ein a-, b-, c- oder t-Unterfeld ist.
  - Wenn eines dieser folgenden Unterfeld ein 9-Unterfeld ist und der Inhalt mit 'p:' beginnt, dann nehmen wir den Inhalt bis auf 'p:' in Klammern.
  - Die Inhalte der ausgewählten Unterfelder werden dann kommasepariert konkatiniert und bilded ein Wort der Schlagwortfolge.

**Comment by IxTheoKm** [comment]
https://ixtheo-test.de/Record/455123039#details
689 	0 	0 	|D u  |0 (DE-588)1069931802  |0 (DE-576)429618611  |2 gnd  |t Bibel  |p Markusevangelium  |n 7,34

In der **Bibelstellensuche** wird Mk 7,34 nicht gefunden

**Comment by thefass** [comment]
fehler treten nicht mehr auf
