### ISSUE TITLE
Bibelstellen nicht angezeigt

### ISSUE THREAD

**Issue by IxGe** [ubtue/ixTheo#141]
Bei https://ptah.ub.uni-tuebingen.de/Record/377822671
werden in der Schlagwortfolge die Bibelstellen nicht angezeigt, obwohl  in 689 vorhanden
![bibel](https://cloud.githubusercontent.com/assets/17196047/13221675/e864b786-d97c-11e5-9aa3-1d14b2ea5c3f.PNG)

**Comment by IxTheoKm** [comment]
Die Zählungen nach $n werden nicht angezeigt. Die erste Bibelstelle wird noch angezeigt, weil die Zählung nach alter Version ohne $n erfasst ist

**Comment by IxGe** [comment]
#141
offensichtlich kann das System nicht nur $n sondern auch $p nicht verarbeiten : das bedeutet, dass ALLE  Bibelstellen, die nach RDA erfasst sind, nicht korrekt angezeigt werden und in einen Topf "Bibel " geworfen werden!

**Comment by thefass** [comment]
Das ist nur ein Anzeigeproblem. Die Infos sind ja in 689 vorhanden und werden auch für die Bibelstellensuche richtig in der 801 umgesetzt

**Comment by oobenland** [comment]
Wir kennen die Regeln nicht. Wenn jemand uns die genauen Regeln definieren kann oder uns ein gutes Dokument zukommen lassen kann, können wir das anpassen. Nach dem Kolloquium.

**Comment by IxGe** [comment]
Ehe ich die Regeln zusammenstelle:
Ist es möglich die Anzeige in der Schlagwortfolge auch aus 801 zu generieren?
Hintergrund:
Es gibt drei Regelwerksstufen (RAK alt, RAK, und RDA), die zu zwei grundsätzlich unterschiedlichen und damit uneinheitlichen Anzeigeformen führt. Diese unterschiedlichen Formen wird es noch eine längere Zeit in der GND geben.
Aus 801 hätten wir sofort eine einheitliche Anzeige : Titel nach RDA + Verszählung.
Wobei wir uns überlegen könnten, ob wir innerhalb des IxTheo auf den "Vorspann" : Bibel .  ... auch verzichten könnten.
In diesem Zusammenhang:
Ist es geplant ein verbales Bibelstellenregister - eine Facette mit Bibelstellen einzurichten? Dann wäre eine einheitliche Form der Ansetzung von Nutzen (bzw. diese Facette müsste auf jeden Fall auf 801 beruhen)

**Comment by thefass** [comment]
funktioniert
