### ISSUE TITLE
Suche über PPN funktioniert teilweise nicht

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#142]
Die Suche über id:PPN funktioniert gerade nicht bei allen PPN über Ptah.
Es funktioniert zum Beispiel bei der PPN 037529552 über den Befehl "id:037529552",
![id funk](https://cloud.githubusercontent.com/assets/16759964/13222297/a26a4608-d97f-11e5-8e8c-8f9918d0238e.png)

aber nicht bei (Matthäus-,Markus-,Lukas-, Johannesevangelium, Apostelgeschichte)
id:209027703
id:209025816
id:209019492
id:208978895
id:20961076X
![id not f](https://cloud.githubusercontent.com/assets/16759964/13222304/a8681daa-d97f-11e5-9651-b61fbb8fa712.png)

über WinIBW sind die PPN problemlos zu finden

**Comment by thefass** [comment]
@Mannsperger Bei den PPNs, die Sie anführen, handelt es sich um die Normdaten. Es ist aber (momentan zumindet nicht. Ob sinnvoll müßte gut überlegt werden) keine Suche nach Normdaten vorgesehen.
