### ISSUE TITLE
Sortierung der Trefferliste nach ...

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#154]
Das Pull-Down-Menü der Trefferlisten-Sortierung bietet "Signatur" an.
Ist hier die IxTheo-Notation gemeint? 
Bitte dann das Pull-Down-Menü anpassen:
![signatur](https://cloud.githubusercontent.com/assets/17004223/13355625/a0f7c640-dca1-11e5-8ac6-afaefe95257f.jpg)

**Comment by oobenland** [comment]
Nach Signatur sortieren heißt nach DDC zu sortieren.

**Comment by thefass** [comment]
muss noch umbenannt werden. Wie steht in den handgeschriebenen papers

**Comment by thefass** [comment]
behoben
