### ISSUE TITLE
Wieso finde ich das nicht?

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#155]
Es gibt das Schlagwort Islamische Länder ...
Freie Suche findet 1104 Treffer:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=islamische+L%C3%A4nder&type=AllFields&filter[]=topic_facet%3A%22Islamische+L%C3%A4nder%2FIslamische+Welt%22

Wenn man das mit Schlagwortfolgen sucht, gibt es keine Treffer:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=islamische+L%C3%A4nder&type=Keywordchains&limit=20&sort=relevance

**Comment by thefass** [comment]
schaut Euch mal diese Suche an, komisch nicht?
https://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Results?lookfor=islamische+L%C3%A4*&type=KeywordChainSearch

**Comment by thefass** [comment]
auch hier eine komische Sortierung. Was passiert da?
https://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Results?lookfor=islamische+L%C3%A4*&type=keywordChainSearch&page=9

**Comment by socheres** [comment]
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn%3D040731723 <https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=040731723>

**Comment by jriedl** [comment]
Eine Schlagwortfolge nur dem Eintrag "Islamische Länder" existiert nicht. Da es Schlagwortfolge als anwählbare Suchkategorie nicht gibt, sollte das für die Praxis kein Problem darstellen. Die Verwendung von Wildcards wie dem Stern wird mittlerweile korrekt behandelt. Nach Abschluss des Imports heute Abend sollten auch die derzeit noch auftretenden komplexen Ketten von Einzelschlagwörtern behoben sein.

**Comment by thefass** [comment]
funktioniert auf Ptah. Closed
