### ISSUE TITLE
Bibelstellensuche über "1-2"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#157]
Wenn ich über die Bibelstellensuche mit der Abkürzung "1-2 Kor" suche (1. und 2. Korintherbrief), so werden mir genau die gleichen Ergebnisse angezeigt wie wenn ich nach "2 Kor" suche (also dem 2. Korintherbrief). Die Idee dieser Abkürzung sollte, so wie ich es verstanden habe, sein, dass man durch diese Abkürzung nur Ergebnisse erhält, die sich mit beiden Briefen befassen und nicht die Treffer, die sich nur mit dem 1. oder nur mit dem 2. Korintherbrief befassen.
Die ersten drei Titel sind jedoch nur mit dem 2. Korintherbrief verschlagwortet, nicht mit dem 1. und dem 2.(https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=1-2+Kor&type=BibleRangeSearch&limit=50&sort=relevance).
Es wäre also optimal, wenn bei der Suche für 1-2 bzw. 1-3 bzw. 2-3 Joh (bei den Johannesbriefen) nur die Ergenisse angezeigt werden, die sich mit diesen Briefen befassen und nicht die Ergenisse, die sich nur mit einem der Briefe befassen. Das gilt für:
1-2 Kor/1-2 Cor/1-2 Co/1-2 K
1-2 Thess/1-2 Thes/1-2 Th/1-2 Tess/1-2 Ts/1-2 Te
1-2 Tim/1-2 Tm/1-2 T
1-2 Petr/1-2 Pet/1-2 Pt/1-2 Pe/1-2 P/1-2 Piet

und - hier in Ausnahme nur 1-3 und 2-3:
1-3 John/1-3 Joh/1-3 Jn/1-3 J/1-3 Io/1-3 Gv

für 2-3 gibt es nur einen Titel, der auch in Ptah gelistet ist mit der PPN 110491564, der jedoch über "2-3 joh" nicht gefunden wird.
Könnte es sein, dass er nicht gefunden wird, weil er in 689 mit "2.-3." und nicht mit 2-3 aufgeführt ist?

**Comment by Mannsperger** [comment]
Zu 1-2 Tim:
Auch die Suchergebnisse nach 1-2 Tim und 2 Tim sind identisch (63 Treffer).
Für die Suche nach 1-2 Tim passt es, dass zuerst Treffer angezeigt werden, die sich mit beiden Büchern befassen, bei der Suche nach Relevanz nach "2 Tim" hätte ich jedoch erwartet, dass zuerst Treffer erscheinen, die sich nur mit 2 Tim befassen.
![1-2 tim](https://cloud.githubusercontent.com/assets/16759964/13399128/06845dc2-df02-11e5-812a-9c3a40df5b37.png)

**Comment by Mannsperger** [comment]
Zu 1-2 Petr (1. und 2. Petrusbrief)
![2 petr](https://cloud.githubusercontent.com/assets/16759964/13402436/89803800-df10-11e5-8446-0d13ce56f26a.png)
Hier das gleiche Phänomen: jeweils 161 Treffer in der gleichen Reihenfolge zu 1-2 Petr oder 2 Petr, 172 Treffer für den 1. Petrusbrief.
Zum Vergleich: WinIBW findet 158 Treffer zum 1. Petrusbrief, 64 Treffer zum 2. Petrusbrief und 94 Treffer direkt zu den beiden Petrusbriefen.

**Comment by Mannsperger** [comment]
Auch bei der Suche nach 1-3 Joh (1. bis 3. Johannesbrief) stimmen die Ergebnisse (192 Treffer) mit denen nach 3 Joh überein.(Treffer zu den einzelnen: 1 Joh: 88, 2 Joh: 7, 3 Joh: 192)
WinIbw findet 193 Treffer für "1-3 Joh", 85 Treffer für Johannesbrief I, jeweils 6 Treffer für Johannesbrief II und Johannesbrief III (Titel die sich mit Johannesbrief 2 und 3 befassen)

**Comment by oobenland** [comment]
Oh oh... das ist problematisch. Das das möglich ist war uns nicht bekannt. Das überhaupt Ergebnisse kommen verwundert mich.

1-2 Kor und 2 Kor wird übersetzt zu 0800000:0899999
1 Kor wird übersetzt zu 0700000:0799999
Eigentlich müsste 1-2 Kor übersetzt werden zu 0700000:0899999

Das Problem: Die Bücher sind nicht sortiert. Das 1. Kor und 2. Kor nebeneinander (07* und 08*) liegen ist Zufall.

1. Joh: 6400000:6499999
2. Joh: 6500000:6599999
3. Joh: 4200000:4299999 !

**Comment by oobenland** [comment]
> Die Idee dieser Abkürzung sollte, so wie ich es verstanden habe, sein, dass man durch diese Abkürzung nur Ergebnisse erhält, die sich mit beiden Briefen befassen und nicht die Treffer, die sich nur mit dem 1. oder nur mit dem 2. Korintherbrief befassen.
Das entspricht auch nicht der Funktionalität der Bibelstellensuche. Die Idee ist, dass man Ergebnisse bekommt, die sich mit dem einen, dem anderen oder beiden Briefen befassen, nur dass die Ergebnisses, die sich mit beiden Briefen befassen ganz oben in der Ergebnisliste auftauchen.

**Comment by Mannsperger** [comment]
Im Alten Testament funktioniert die Suche für die beiden Samuelbücher über keine der Abkürzungen:
1-2 Sam/1-2 Sm/1-2 S
![1-2 sam](https://cloud.githubusercontent.com/assets/16759964/13492565/0e768986-e139-11e5-9ddb-1561494b3476.png)

**Comment by Mannsperger** [comment]
bei der Suche nach den ersten beiden Büchern der Chronik (Altes Testament), funktionieren die Abkürzungen "1-2 Chron/1-2 Chr/1-2 Ch/1-2 Cr/1-2 Par". Die Ergebnisse sind hier wieder mit den Ergebnissen der Suche nach dem zweiten Chronikbuch über die Abkürzungen "2 Chron/2 Chr/2 Ch/2 Cr/2 Par" identisch (jeweils 164 Treffer in der gleichen Reihenfolge).

**Comment by Mannsperger** [comment]
Bei der Suche nach "1-2 Tim" erhält man über Ptah 63 Treffer.
40 der 41 Treffer sind in diesen 63 Treffern enthalten.
Dieser Titel jedoch nicht, er fehlt auch an sich in Ptah:
![couard](https://cloud.githubusercontent.com/assets/16759964/13495667/54269bac-e14c-11e5-94e6-8c2cf7a65126.png)

**Comment by ruschein** [comment]
Ready for testing on ptah.
