### ISSUE TITLE
Fehler bei "andere Suchmöglichkeiten"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#158]
Die Anzeige "andere Suchmöglichkeiten" funktioniert nicht, wenn ich die Bibelstellensuche eingestellt habe, jedoch über die Auswahl "Alle Felder". Suche nach 2 ts (2. Thessalonicherbrief):
![2 ts](https://cloud.githubusercontent.com/assets/16759964/13400343/932f1082-df07-11e5-906c-b01364bc2f5a.png)
![2 tsd](https://cloud.githubusercontent.com/assets/16759964/13400350/98e2a8a4-df07-11e5-9e31-7da8e39ae47a.png)
![2 tsd alle felder](https://cloud.githubusercontent.com/assets/16759964/13400352/9cbcf9de-df07-11e5-838b-c5bd547e8154.png)

Die anderen Suchmöglichkeiten stehen darüber hianus nicht in offensichtlichem Zusammenhang mit dem gesuchten Brief.
Wenn ich nach 2 ts (2. Thessalonicherbrief) suche, hätte ich erwartet, dass mir vielleicht die anderen Suchmöglichkeiten für diesen Brief angezeigt werden, also: 
2. Thessalonicherbrief/2 Thess/2 Thes/2 Th/2 Tess/2 Te

**Comment by thefass** [comment]
@Mannsperger Bibelstellensuche und die verschiedenen Abkürzungen funktionieren nur bei eingestellter **Bibelstellensuche**
Wenn man in alle Felder sucht, dann sucht man explizit nicht in den Bibelstellen, sondern in allen anderen Feldern. Deswegen die Treffer im dritten screenshot

**Comment by thefass** [comment]
Wahrscheinliche Lösung des Problems:
Entfernen der Option "Andere Suchmöglichkeiten" bei der Bibelstellensuche.
Müssen wir in Ruhe überlegen

**Comment by thefass** [comment]
Die Vorschläge unterhalb des Suchschlitzes in der Rubrik "Andere Suchmöglichkeiten" sind irreführend.
Z.Bsp wird bei der erlaubten Suche 2 ts u.a. als Alternative 2 s angeboten. Unter 2 ts versteht man den 2. Thessalonicherbrief, unter 2 s aber das 2. Samuelbuch.

@ruschein 
Bitte im Modus Bibelstellensuche die Option "Andere Suchmöglichkeiten" abschalten

**Comment by thefass** [comment]
@ruschein
Bitte im Modus Bibelstellensuche die Option "Andere Suchmöglichkeiten" abschalten. Ist das möglich?

**Comment by mtrojan-ub** [comment]
@thefass 
Ja das ist möglich und kann per Konfiguration abgeschaltet werden.

Bei aktuellen Tests ist mir noch etwas aufgefallen. Erhält man in der Bibelstellensuche keine Ergebnisse, werden aktuell folgende Vorschläge angezeigt:

![grafik](https://user-images.githubusercontent.com/26873381/32825485-7a4c2d8c-c9e5-11e7-9e42-6092663a00f3.png)

Ganz unten wird noch vorgeschlagen, dass man Wildcards für die Suche verwenden soll. Allerdings wird dies wohl von der Bibelstellensuche nicht unterstützt. Sollen wir das ebenfalls rausnehmen?

**Comment by thefass** [comment]
Ja, bitte auch herausnehmen.

Könnte bitte bei Nichtergebnis folgende Nachricht angezeigt werden:

Bitte prüfen Sie, ob Sie die gesuchte Bibelstelle korrekt eingegeben haben. Eine Liste der erlaubten Bibelbuchabkürzungen finden Sie hier: https://www.ixtheo.de/docs/Bible_abbreviation.pdf

**Comment by mtrojan-ub** [comment]
Ist beides umgesetzt, allerdings erst in tuefind. Ich melde mich nochmal sobald es auf ptah zur Verfügung steht.

![grafik](https://user-images.githubusercontent.com/26873381/32881030-0cb2f6cc-cab0-11e7-9d5f-cad69f0bc05d.png)

**Comment by mtrojan-ub** [comment]
... kann jetzt auf ptah getestet werden!

**Comment by thefass** [comment]
funktioniert! beides ist umgesetzt.
Allerdings kommt bei Klick auf den Link für die Abkürzungen der 403 Fehler
![bildschirmfoto 2017-11-22 um 22 58 34](https://user-images.githubusercontent.com/14169098/33151613-0baa4eaa-cfd9-11e7-8514-83b4f1c1769f.png)

**Comment by mtrojan-ub** [comment]
stimmt, wir mussten die Dokument-Ablagestruktur im Hintergrund nochmal anpassen und ich habe den Link an dieser Stelle leider vergessen anzupassen. ist jetzt aber behoben!

**Comment by thefass** [comment]
Funktioniert.
Bitte das pdf in einem neuen Reiter aufgehen lassen.

**Comment by mtrojan-ub** [comment]
ist geändert!

**Comment by thefass** [comment]
alles ok.
