### ISSUE TITLE
Bereinigung veralteter Links auf den jetzigen IxTheo im SWB

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#162]
https://ptah.ub.uni-tuebingen.de/Record/107293617

Hier muss spätestens nach Abschaltung des alten IxTheo folgender Link verändert werden:
    "Aufsatznachweise im Index theologicus"

Am besten durch automatische Bereinigung in den SWB Daten mit Ersetzung durch eine neue Webadresse

**Comment by ruschein** [comment]
Hat nichts mit uns zu tun.

**Comment by thefass** [comment]
Bereinigung ist erfolgt.
