### ISSUE TITLE
Bibelstellenanzeige der GND-Nummern bei SWB 5580

### ISSUE THREAD

**Issue by IxGe** [ubtue/ixTheo#164]
War das nicht schon ein issue?
Bei https://ptah.ub.uni-tuebingen.de/Record/044643179
wird bei Schlagwortfolgen

(DE-588)4041771-2 (DE-576)209046724 gnd Bibel Neues Testament 

angezeigt.

Auch in bei Schlagworte wird falsch

Bibel > Neues Testament

angezeigt.
![pate](https://cloud.githubusercontent.com/assets/17196047/13454835/03c83fc8-e05a-11e5-8fc8-8eea31074f9e.PNG)

**Comment by jriedl** [comment]
Anzeige der GND Informationen für die Schlagwortfolgen wird nun unterdrückt. 
Inwiefern ist die Anzeige bei den Schlagworten selbst nicht korrekt?

**Comment by IxGe** [comment]
Bitte bei der Darstellung der Werktitel und damit der Bibelstellen beachten:
$p wird zu  .  [Punkt]       also: Bibel $pNeues Testament     wird zu  Bibel. Neues Testament
$n wird zu     [Leestelle] also: Bibel $pHabakuk $n2,15-17  wird zu   Bibel. Habkuk 2,15-17

**Comment by jriedl** [comment]
Ok. Die Schwierigkeit hierbei ist, dass für die Schlagworte das '>' das Trennzeichen für Einzelterme ist mit dem man durch Überfahren mit der Maus eine neue Suchanfrage mit den "markierten" Werten generieren kann. Würde dieser Aspekt der Verbindung von Einzeltermen durch die Punkttrennung nicht eher verdeckt?

**Comment by IxTheoKm** [comment]
Warum wird bei 044643179 jetzt ein Punkt nach Bibel angezeigt, sonst aber Komma z.B. 46713829X und 446327948.
Punkt ist lt. IxGe korrekt

**Comment by ruschein** [comment]
Das @ ruschein war wohl falsch, es hätte ein @jriedl sein sollen.

**Comment by thefass** [comment]
stimmt, war falsch. Gemeint war @jriedl

**Comment by thefass** [comment]
erledigt
