### ISSUE TITLE
Abtrennung ":" bei Kurztitelanzeige geht verloren wenn der Begriff davor "gehighlighted" ist

### ISSUE THREAD

**Issue by IxGe** [ubtue/ixTheo#168]
zur Erinnerung,
hier Treffer 1 + 3
![doping](https://cloud.githubusercontent.com/assets/17196047/13465983/4fb1cbbe-e098-11e5-9593-c46557e2e651.PNG)

**Comment by thefass** [comment]
Funktioniert
