### ISSUE TITLE
nicht funktionierende Abkürzungen

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#170]
Folgende Abkürzungen funktionieren nicht:
3 Ezra/3 Ezr/3 Esra/3 Esd/1 Esdras 
4 Ezra/4 Ezr/4 Esra/4 Esd/2 Esdras
5 Ezra/5 Ezr/5 Esra/5 Esd
6 Ezra/6 Ezr/6 Esra/6 Esd
![3 ezra](https://cloud.githubusercontent.com/assets/16759964/13493148/a10cb0e2-e13c-11e5-88b4-3542d6ea62aa.png)

**Comment by Mannsperger** [comment]
...und die Abkürzung "2 Ezra" als Abkürzung für das Nehemiabuch.
![2 ezra](https://cloud.githubusercontent.com/assets/16759964/13493250/4a4251c6-e13d-11e5-872f-af76b0cb8d0c.png)

**Comment by Mannsperger** [comment]
Die Abkürzung "Hi" für das Buch Hiob funktioniert nicht. Über die Abkürzungen "Iob Job Jb Gb" und über "Hiob" erhält man 587 Treffer.
![hi](https://cloud.githubusercontent.com/assets/16759964/13493733/164d03a4-e140-11e5-88e8-389a879827f3.png)

**Comment by ruschein** [comment]
Wir unterstützen nur die Abkürzungen, die wir geliefert bekommen hatten.  Ich habe die Liste hier angehängt.
[books_of_the_bible_to_canonical_form.zip](https://github.com/ubtue/ixTheo/files/177661/books_of_the_bible_to_canonical_form.zip)

**Comment by ruschein** [comment]
Bitte ergänzen Sie die Liste.

**Comment by Mannsperger** [comment]
Folgende Abkürzungen kommen in der Liste vor, liefern aber keine Ergebnisse über die Bibelstellensuche in Ptah:
Für das Esra Buch III: 3 Ezra/3 Ezr/3 Esra/3 Esd/1 Esdras
Für das Esra Buch IV: 4 Ezra/4 Ezr/4 Esra/4 Esd/2 Esdras
Für das Esra Buch IV 1-2: 5 Ezra/5 Ezr/5 Esra/5 Esd
Für das Esra Bich IV 15-16: Ezra/6 Ezr/6 Esra/6 Esd
![3 ezra](https://cloud.githubusercontent.com/assets/16759964/14248012/772d395a-fa72-11e5-8ae4-56e9074a90fc.png)

Folgende Abkürzungen Fehlen aus meiner Sicht noch:
Für "Ijob": "Hiob" und "Hi" - das sind die meistgebräuchlichen Abkürzungen im deutschen, evangelischen theologischen Bereich. Wobei auch jetzt schon die Suche nach "Hiob" funktioniert(aber nicht nach "Hi"), nur die Bezeichnung habe ich nicht in der Liste gefunden.

Für "Hoheslied" fehlt noch "Hohelied", das ist auch eine sehr gebräuchliche Bezeichnung.

Ich habe die Datei in diesem Sinne bearbeitet, ich hoffe, man kann in diesem Format noch die sichtbargemachten Änderungen sehen:
[books_of_the_bible_to_canonical_form_geändert.txt](https://github.com/ubtue/ixTheo/files/202402/books_of_the_bible_to_canonical_form_geandert.txt)

**Comment by ruschein** [comment]
Die geänderte Datei hatte 2 Probleme:  die letzte Zeile fing mit "[FM1]" anfing und alle Zeilenenden waren falsch.  Du hattest die UNIX-Zeilenenden durch DOS bzw. Windows-Zeilenenden ersetzt.
Ich habe die beiden Probleme behoben und Johannes Riedl hat sie wieder eingespielt.

**Comment by thefass** [comment]
@Mannsperger Zum Öffnen von UNIX Dateien bitte in Zukunft den Editor Notepad++ verwenden, der auf jedem Ub-Rechner installiert ist.
Bitte einmal ausprobieren und die Datei @ruschein zur Kontrolle schicken

**Comment by Mannsperger** [comment]
Die Suche "1-2 Kön" funktioniert immer noch nicht.
![1-2 kon](https://cloud.githubusercontent.com/assets/16759964/14427128/66cbdd92-fff3-11e5-88c0-1f8ed7f26b1d.png)

**Comment by Mannsperger** [comment]
Die Suche "1-2 Kor" funktioniert, aber liefert immer noch die gleichen Ergebnisse wie die Suche nach "2 Kor"

**Comment by ruschein** [comment]
#157 ist das Issue für die Suche über mehrere Bücher gleichzeitig.  Suchen wie "Esd 3" und "Hi" funktionieren.
