### ISSUE TITLE
Rezensionsfelder werden nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#177]
787 taucht nicht in der Anzeige auf.
https://ptah.ub.uni-tuebingen.de/Record/393714217

(Nebenbemerkung: die nicht verknüpften, also nur verbal erfassten Titel werden gar nicht ausgeliefert.)

**Comment by thefass** [comment]
Die Volltitelanzeige muss noch überarbeitet werden. Vielen Dank schonmal für diese Beobachtung
Die Auslieferung der nur verbal erfassten Titel muss das BSZ korrigieren

**Comment by thefass** [comment]
https://ptah.ub.uni-tuebingen.de/Record/393714217
So sieht das obige Beispiel in defr WinIBW aus:
787 08$iRezension von$aMcClure, John S., 1952$tMashup religion$w(DE-576)360496067$w(DE-600)1022387626
787 08$iRezension von$aBroken Hallelujahs: why popular music matters to those seeking God / Christian Scharen
787 08$iRezension von$aWatkins, Ralph Basui$tHip-hop redemption$w(DE-576)365319821

Rez 1 und 3 sind verknüpft (deswegen auch Identnummern
Rez 2 ist nicht verknüpft, sondern der rezensierte Titel ist einfach verbal in $a eingetragen (Broken Hallelujahs: why ...)

Im Internformat ist Rez 2 zwar angelegt, aber $a nicht vorhanden, sondern einfach leer:
787 	0 	8 	|i Rezension von  

Ebenso auch z.Bsp hier: 
https://ptah.ub.uni-tuebingen.de/Record/109847148

@Olli: kannst Du prüfen, ob das in den Datenleiferungen enthalten ist oder vom BSZ nicht ausgeliefert wird?

**Comment by oobenland** [comment]
Die Daten aus den BSZ Daten sind identisch zu dem im Internformat angezeigten Daten. Das Unterfeld fehlt auch da.

**Comment by thefass** [comment]
@Olli :: bitte im BSZ monieren!

**Comment by IxTheoKm** [comment]
Die verbal erfassten Rezensionen werden immer noch nicht angezeigt/geliefert.

Ist es Absicht, dass in der deutschen Version die Anzeige der Rezensionen jetzt mit "Reviewed:" statt mit "Rezension von:" eingeleitet wird?

**Comment by thefass** [comment]
Bitte dafür sorgen, dass alle Rezensionen in 787 Felder angezeigt werden

**Comment by ruschein** [comment]
Anscheinend werden zur Zeit nur die Rezensionen angezeigt die wir verlinken können.  Sollen die nicht verlinkbaren auch auch angezeigt werden?

**Comment by ruschein** [comment]
Sollte vielleicht noch hinzufügen, dass verlinkbar heißt, dass wir die Datensätze für die Rezensionen haben.

**Comment by IxTheoKm** [comment]
Ja, bitte unbedingt auch die nicht verlinkbaren anzeigen!
Es ist ja nur Zufall, wenn zum Zeitpunkt der Katalogisierung das rezensierte Werke auch schon im SWB vorhanden ist oder nicht. In anderen Datenbeständen kann das fehlende Werk vorliegen. Wenn die Beschreibung der rezensierten Publikation angezeigt wird, kann ein Nutzer danach recherchieren, auch wenn sie im IxTheo (noch) nicht vorhanden ist.

Bsp.: 
Hier sind zwei Rezensionen verlinkt, eine noch nicht, weil der Titel im SWB noch nicht vorhanden ist (in mindestens 5 anderen deutschen Verbünden ist er aber vorhanden):
https://ptah.ub.uni-tuebingen.de/Record/393714217#details

Wenn nur zwei rezensierte Werke angezeigt werden, ist die Titelbeschreibung zudem unvollständigt, also inhaltlich nicht korrekt.

**Comment by ruschein** [comment]
Ich vermute, dass die Rezensionsfelder oft falsch belegt sind.  Ein Beispiel ist https://ptah.ub.uni-tuebingen.de/Record/473962365#details  Da sind die Title mal im Unterfeld $t, und mal im Unterfeld $a.

**Comment by IxTheoKm** [comment]
Sie sind korrekt belegt, werden aber offensichtlich in Marc falsch ausgeliefert. $a wird geliefert, wenn es einen Autor gibt, $t steht für den Titel. Wenn es keinen Autor gibt, wird auch $a ausgeliefert. Da sollte wohl eher $t stehen. Ich gebe das ans BSZ weiter.

**Comment by IxTheoKm** [comment]
Rezensionsfelder werden gar nicht mehr angezeigt (nur im Internformat). Bsp.: 393714217

**Comment by IxTheoKm** [comment]
Ist noch nicht o.k.
Bsp.:
https://ixtheo-test.de/Record/393714217#details
Ein Rezensionsfeld fehlt dort. 

Die korrekte Auslieferung der Unterfelder wurde vom BSZ zwar angekündigt, ist aber noch nicht umgesetzt.

**Comment by ruschein** [comment]
@IxTheoKm Der 2. 787-Eintrag https://ixtheo-test.de/Record/393714217#details sieht falsch aus.  Das t-Unterfeld fehlt und steckt zusammen mit dem Autor im a-Unterfeld.  Deswegen zeigen wir den Eintrag nicht an.

**Comment by IxTheoKm** [comment]
Diese Version ist bisher für alte, Nicht-RDA-Aufnahmen korrekt! Wenn nicht mit SWB-PPNs verknüpft werden kann, werden/wurden Titel und Autor in dieser Form erfasst:
Rezension von: _Titel / Autor. - Ort : Verlag, Erscheinungsjahr_
oder
Bezugnahme auf: _Titel / Autor_.  - In: _Zeitschriftentitel. - Bandangaben_...
Beispiel: https://ixtheo-test.de/Record/453587259#details

Das Problem liegt aber bei den mit Unterfeld erfassten Feldern woanders und ist vom BSZ noch nicht behoben:
wenn es nur einen Titel und keinen Autor gibt, soll nicht $a sondern $t ausgeliefert werden. 
Das wird lt. BSZ-Meldung im Zuge der MARC-Anpassungen angkündigt und nach einer Frist umgesetzt. Das ist noch nicht passiert.

**Comment by ruschein** [comment]
@IxTheoKm Verstehe.  Danke für die Erleuterung.  Können wir das Issue dann zumachen da ja auf Seite der Entwickler kein Handlungsbedarf besteht.  Unser Code würde auch den fehlenden Eintrag anzeigen falls das $t-Feld besetzt wäre.

**Comment by IxTheoKm** [comment]
Ich behalte das im Auge und öffne das Issue wieder, falls die MARC-Auslieferung v.a. der Nicht-RDA-Aufnahmen nicht angepasst werden sollte
