### ISSUE TITLE
Unterschiedliches Verhalten JOP

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#178]
Bei der Suche außerhalb des Uninetzes nach 
https://ptah.ub.uni-tuebingen.de/Record/01482177X
wird "Verfügbarkeit prüfen" angezeigt
![jop1](https://cloud.githubusercontent.com/assets/14169098/13862383/3cdd8602-ec93-11e5-8f64-2a2c2908d90b.png)

Bei der Suche nach
https://ptah.ub.uni-tuebingen.de/Record/286500248
allerdings erscheint ein Ladefehler. 
Warum? 
![jop2](https://cloud.githubusercontent.com/assets/14169098/13862464/be613ebc-ec93-11e5-9c17-46637672c978.png)

**Comment by jriedl** [comment]
Das Problem hängt mit der ISSN zusammen. Für die Bestimmung der ISSN wird unter anderem zunächst das feld 22a und dann das Feld 29a ausgewertet und die erste gefundene ISSN wird dann zur Abfrage verwendet. Wie man im Internformat und auch schon bei den Screenshots erkennen kann, steht hier bei dem ersten Eintrag die (korrekte) 0044-216X, beim zweiten 2196713X, hier liefert der JOP-Dienst einen Fehler: Offenbar ist die Regel bei ISSNs, dass nach vier Ziffern ein Bindestrich kommen muss - eine Abfrage auf 2196-713X liefert auch das korrekte Ergebnis. Wir könnten grundsätzlich versuchen den Bindestrich durch das Programm einfügen zu lassen, allerdings wäre es vorher interessant zu wissen, warum die Daten hier bislang zum Teil ohne Bindestrich erfasst werden.

**Comment by jriedl** [comment]
Workaround-Code ist integriert

**Comment by thefass** [comment]
@jriedl Jetzt kommt bei dem oben als Fehler angegenben Link  (https://ptah.ub.uni-tuebingen.de/Record/286500248) übefrhaupt keine JOP anzeige mehr

**Comment by jriedl** [comment]
Ein Record kann nun mehrere Formate haben - in diesem Fall "Elektronisch" und "Artikel" und JOP wird wieder angezeigt

**Comment by thefass** [comment]
@jriedl laut Katalogisierungsregeln wird die ISSN in Feld 29 (=PICA 2005) mit Bindestrich eingegeben.
http://swbtools.bsz-bw.de/cgi-bin/help.pl?cmd=kat&val=2005&regelwerk=RDA&verbund=SWB
im Picaformat des Verbundes ist das acuh so zu sehen.
Anscheinend ist das ein Auslesefehler in MARC
Das müßtet Du beim BSZ nachfragen
Aber wenn Dein Code nun den Fall ohne Bindestrich abfangen kann, dann ist das Problem ja auch gelöst

**Comment by thefass** [comment]
So weit ich das sehe, funktioniert es nun.
