### ISSUE TITLE
Medienart "elektronisch" in der erweiterten und einfachen Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#184]
Warum finde ich die Online-Beiträge der Theologischen Literaturzeitung nicht, wenn ich in der erweiterten Suche mit Medienart "elektronisch" einschränke?
In der einfachen Suche finde ich auch keine Facette zum Einschränken.

**Comment by jriedl** [comment]
Sollte nach dem nächsten, heute Nacht laufenden Import behoben sein
