### ISSUE TITLE
Unterscheidung zwischen Aufsatz und Rezension

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#186]
Erklärung zum Hintergrund:
Momentan wird im VuFind nicht zwischen Aufsatz und Rezension unterschieden und alles unter "Artiekl/Article" subsummiert. 

Die Unterscheidung ist aber dringend nötig und muss in den Facetten abgebildet werden.

Rezension unterscheiden sich von den eigentlichen Aufsätzen duch das Abrufzeichen uwre in 935 $c. 
Mit dem Umstieg auf RAK ist (fakultativ) in der 655 7$aRezension dazu gekommen.
Es sollten beide Felder ausgewertet werden.
Ich schlage vor, dass die eigentlichen Artikel im Deutschen "Aufsatz" genannt werden. Im Englischen kann man bei article bleiben.
Die Rezensionen sollten in deustch "Rezension", in englisch "review" genannt werden.

**Comment by thefass** [comment]
wenn man in der normalen Suche im Suchaspekt Schlagwort nach Rezension sucht, dann wird in der Kurztitelanzeige auch 655 mit angezeigt. Allerdings noch nicht richtig, da überflüssige Unterfelder mit erscheinen:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=rezension&type=Subject&sort=year&filter[]=format%3A%22Article%22&page=2115

“Rezension (DE-576)209083166 gndcontent”
die überflüssigen Infos stecken in 655 $0 und $2. Beides soll nicht angezeigt werden

**Comment by ruschein** [comment]
Kleine Änderung: Auf Ptha ist es jetzt "Aufsatz" und die Übersetzung für "Review" ist auch schon eingetragen aber da muss noch Code angepasst werden.

**Comment by ruschein** [comment]
Code angepasst.  Jetzt warte ich noch auf einen Code-Review nächste Woche und danach einen neuen Datenimport.

**Comment by thefass** [comment]
momentan ist die Facette Rezension nicht zu sehen

**Comment by jriedl** [comment]
Die Facette Rezension wird jetzt wieder angezeigt. Nach dem nächsten Import sollten auch die überflüssigen numerischen Unterfelder bei der Anzeige der Schlagworte nicht mehr erscheinen

**Comment by thefass** [comment]
gelöst
