### ISSUE TITLE
Facetten Logik

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#191]
@ruschein : wir hatten ja schon darüber telefoniert. Hier nochmal in schriftlicher Form:

es gibt in der Facette "Medienart" die Facette Buch, e-book, Aufsatz und Elektronisch.
Das müßte logisch so geordnet werden:
Buch 
Aufsatz
wobei hier sowohl die print als auch online Bücher / Aufsätze subsummiert sind

und dann die Facette elektronisch, die in der Facette Buch die ebooks und in der Facette Aufsatz die eAufsätze filtert
das gilt aber für alle elektronisch vorhanden Fälle (z.B. auch für Schriftenreihen)

**Comment by thefass** [comment]
gelöst: 

- elektronisch / nicht elektronisch wurde in die Facette Medientyp ausgelagert

- Buch umfasst nun gedruckte und elektronische Bücher (auch e-books). Das gleiche gilt für Aufsätze

**Comment by socheres** [comment]
@thefass @ruschein Medientyp und Medienart ist synonym. Mein Vorschlag "Zugang" als Facetten-Überschrift und neben "Elektronisch"/"Nicht-Elektronisch" soll in dieser Facette noch Marc21-Feld 856 |z "kostenfrei" ausgewertet werden. Denn bei jedem kosten-/lizenzfreien Titelsatz steht im Pica3-Feld 0500 Oxxl [=Lizenzfreie elektronische Ressource (nur wenn "O" auf Pos. 1)]http://swbtools.bsz-bw.de/winibwhelp/Liste_0500.htm Damit wären alle Open Acess Zeitschriften und institutionellen Repositorien bei uns über diese Facette einschränkbar, zumal die OA-Zss., die mit Zotero katalogisiert werden als 0500 "Oxxl" erfasst werden.

**Comment by socheres** [comment]
@thefass wie wäre es mit Auswahl "Elektronisch", "Elektronisch-kostenfrei", "Nicht-Elektronisch"?

**Comment by thefass** [comment]
Der Zugang zu kostenfreien Titeln ist in der Facette Open Access umgesetzt.
