### ISSUE TITLE
Facette Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#192]
Im Gesamtbestand werden in der Facette "Verfasser" unter Benedikt XVI. ... nur 722 Treffer aufgeführt. Im SWB müssen aber allein schon 1737 Titel aus dem Allegro-IxTheo mit Benedikt als Verfasser migriert worden sein. Insgesamt sind es im SWB mit mteo über 2180.
Bei Johannes Paul II. sind es in der Facette nur 653 Treffer, im Allegro-IxTheo 1779. Im SWB sind es über 2500 mit mteo.
Was fließt in die Facette Verfasser ein und was nicht?

**Comment by oobenland** [comment]
Die Zahlen haben sich inzwischen angepasst. Aktuell:
Benedikt XVI.: 2211
Johannes Paul II.: 2900
