### ISSUE TITLE
Fehlende Verknüpfung zum übergeordnetem Werk

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#197]
Die ersten 7 Treffer haben eine Verknüpfung zum übergeordentem Werk, nicht aber die Treffer 8-12:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&sort=year&filter[]=format%3A%22Article%22
Link zu Treffer 8:
https://ptah.ub.uni-tuebingen.de/Record/456875018
Komisch ist, dass die 773 vorhanden ist und in diesen Fällen nicht ausgewertet werden.

**Comment by thefass** [comment]
das Problem besteht immer noch:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=journal_issue:456361898
im ersten Treffer ist die Überordnung angegeben:
_Krise des Gebets? : Protestantische Entwicklungen und Perspektiven
von Etzelmüller, Gregor 1971-
**in: Gebetslogik, (2016), S. 27-41**
“(DE-576)456361898”_
im zweiten (und den weiteren) Treffer jedoch nicht:
_"Christen sollen Beter sein, Baptisten aber ganz besonders" : Anmerkungen zur Gebetskultur im deutschen Baptismus
von Spangenberg, Volker 1955-
“(DE-576)456361898”_
Allerdings besteht das Problem nur in der Kurztitelanzeige. In der Volltitelanzeige ist die Angabe auch im zweiten Treffer da.

Ich habe mir mal das Internformat angeschaut:
für den ersten Treffer:
773 	0 	8 	|i Enthalten in  |a Gebetslogik  |d 2016  |g (2016), S. 27-41  |w (DE-576)456361898  
für den zweiten Treffer:
773 	0 		|i Enthalten in  |t Gebetslogik  |w (DE-576)456361898  |a Gebetslogik : Reflexionen aus interkonfessioneller Perspektive  

Das ist ja schon ziemlich unterschiedlich. 

Was ich allerdings nicht nachvollziehen kann, wenn ich mir die Marcfelder in der WinIBW anschaue:
für den ersten Treffer:
773 08$iEnthalten in$aGebetslogik$d2016$g(2016), S. 27-41$w(DE-576)456361898
für den zweiten Treffer:
773 08$iEnthalten in$aGebetslogik$d2016$g(2016), S. 118-139$w(DE-576)456361898

Das schaut ja von der Struktur völlig gleich aus.

Was geht da vor sich? Hat jemand eine Erklärung?

**Comment by IxTheoKm** [comment]
Jetzt wird in der Kurzanzeige überall nur noch “(DE-576)456361898” angezeigt. 
Es sollte aber der Titel des übergeordneten Werks angezeigt werden

**Comment by thefass** [comment]
(DE-576)456361898 scheint weg zu sein, das Hauptproblem besteht aber noch: siehe meinen obigen letzten Kommentar

**Comment by IxTheoKm** [comment]
Die PPN wird in manchen Fällen doch noch angezeigt:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter[]=authorStr%3A%22Neusner%2C+Jacob+1932-%22&sort=year
![ppn](https://cloud.githubusercontent.com/assets/17004223/16013693/bd797ab0-318e-11e6-9408-295c9f98144d.png)

**Comment by ruschein** [comment]
Könnte jemand bitte nochmal ein Beispiel verlinken.  Der Link im vorherigen Post tut leider nicht.

**Comment by IxTheoKm** [comment]
Der Hinweis in dem genannten Post bezieht sich nur noch auf die Anzeige der PPNs:
"(DE-...)..."
Bei Aufsätzen aus Zeitschriften wird die PPN der Zeitschrift nach der Seitenzahl angezeigt (s. Treffer 2):
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=neusner%2C+jacob&type=Author&filter[]=format%3A%22Article%22

Bei Aufsätzen aus Büchern ist es o.k. (siehe Treffer 1)

**Comment by ruschein** [comment]
@IxTheoKm Ist das immer noch ein  Problem?  Entweder ist es behoben oder ich habe etwas übersehen.

**Comment by IxTheoKm** [comment]
Sieht jetzt alles richtig aus
