### ISSUE TITLE
Verschwundene Facettenauswahl

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#198]
Nach Auswahl einer Facette in der Rubrik Medienart (z.B. Buch oder Aufsatz), verschwinden die anderen Facetten

**Comment by oobenland** [comment]
Das passiert, weil die anderen Facetten leer sind. Zum Beispiel gibt es keine Schriftenreihe, die gleichzeitig ein Buch ist. Wählt man Schriftenreihe als Medienart aus, so wird die Buch-Facette leer und nicht mehr angezeigt. Dadurch können anderen Facetten "nach rücken".

**Comment by thefass** [comment]
das klingt logisch und ist auch sinnvoll.
Vor kurzem ist aber auch die Facette Elektronisch mit verschwunden. Das ist aber jetzt nicht mehr der Fall.
Ist denn immer sicher gestellt, dass nach Auswahl einer Facette, die dann in den ausgewählten Titeln enthaltenen anderen Facetten noch angeziegt werden?

Unglücklich finde ich, dass die Auswahl buch die Facette e-book verschwinden läßt

Über die Facette elektronisch müssen wir nochmal diskutieren, wenn Johannes wieder da ist

**Comment by thefass** [comment]
gelöst: siehe #191
