### ISSUE TITLE
Facette Festschrift

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#214]
Festschrift wird sowohl als Schlagwort als auch als formale Kategorie verwendet.

Welche Felder werden für die Facette Festschrift momentan ausgewertet?
https://ptah.ub.uni-tuebingen.de/Search/Results?type=Subject&sort=year&limit=100&filter[]=genre_facet%3A%22Festschrift%22

Es sollten folgende Felder zusätzlich ausgewertet werden:
935 $cfe 
655 $aFestschrift

**Comment by thefass** [comment]
## Exkurs RDA und Festschrift
Nach RDA wird die Festschrift doppelt gemoppelt erfasst:
einmal nach 935 $cfe (=PICA 1140) und zum zweitenmal in 655 $aFestschrift (=PICA 1131, hier verlinkt mit einer PPN Nummer).
**Was ist der Vorteil?**
655 wird im VuFind als weiteres (d.h. nicht normiertes) Schlagwort durchsucht. Auf diese Weise werden die Festschriften nun auch gefunden, wenn jemand mit der Kategorie Schlagwort nach Festschrift sucht.
**Was muss noch getan werden (BSZ)**
Jetzt ist nur noch nötig, dass die mehr als 11.000 Festschriften im IxTheo mit 655 $a nach RDA nachkatalogisiert werden. Müsste vom BSZ aber leicht automatisch gemacht werden können.

**Comment by oobenland** [comment]
Ist dieses Issue für uns noch aktuell? Festschrift gibt es inzwischen als Facetteneintrag und kann als Schlagwort gefunden werden. Kann man das Issue somit schließen?

**Comment by thefass** [comment]
Issue könnte geschlossen werden, wenn sicher gestellt ist, dass die beiden Felder 935 und 655 ausgewertet werden. Bitte bestätigen.

**Comment by jriedl** [comment]
655 und 935 werden ausgewertet

**Comment by thefass** [comment]
funktioniert. Closed
