### ISSUE TITLE
alphabetisch browsen nach Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#215]
Welche Verfassernamen fließen hier ein? Sie scheinen nicht vollständig zu sein.
Bsp.:
Bei der Suche mit "Denffer, A" sind in der Liste zum Autor "Denffer, Ahmad von" nur 31 Titel nachgewiesen. Im SWB ist es mit mteo oder sgb 1 bzw. 0 ein Titel mehr:
PPN 463640802 fehlt, obwohl er in VuFind-IxTheo vorhanden ist.

Erklärung: die 31 Titel sind alle mit dem nicht individualisierten Namenssatz PPN 164467327 verknüpft. 
Der fehlende Titel ist mit dem individualisierten Personensatz PPN 290083680 verknüpft, der hier in der Liste scheinbar nicht berücksichtigt wird.

In der einfachen Suche finde ich alle 32 Titel.

Beim Browsen müssen alle Namens- und Personensätze berücksichtigt werden!

**Comment by oobenland** [comment]
Der Titel mit der PPN 463640802 ist unter dem Eintrag `Denffer, Ahmad von 1949-` der alphabetischen Suche zu finden.
Das Problem ist, dass in diesem einen Datensatz das Geburtsdatum eingetragen ist, bei allen anderen nicht. Somit wird ein anderer Autorenname generiert und somit unter unterschiedlichen Einträgen angezeigt.

**Comment by IxTheoKm** [comment]
Genau das Problem habe ich oben geschildert.
Im SWB gibt es viele Autoren, deren Titel mit unterschiedlichen Normsätzen verknüpft sind. Bereinigungen laufen, werden am in 100 Jahren bei der Datenmenge nicht fertig sein.  
Offensichtlich werden aber jetzt beim Browsen beide Sätze berücksichtigt. Damit ist das Problem gelöst.
