### ISSUE TITLE
URLs in Exemplardaten

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#217]
In den IxTheo-Daten wurden zum Teil URLs in den Lokaldaten erfasst (Feld 8564). Sollen die auch angezeigt werden?
Bsp.:
PPN 023352612
PPN 467678804
PPN 463165551
Es sind allerdings nur etwas weniger als 460 Aufsätze betroffen

**Comment by thefass** [comment]
erste PPN führt auf den Shop der DBK
dritte PPN auf einen Wikipediaartikel

Ich fürchte, dass die Links sehr uneinheitlich sind. Meine, es ist besser, die Links erstmal zu prüfen

**Comment by IxTheoKm** [comment]
Die Links _sind_ sehr uneinheitlich. Es gab keine Vorgaben für die Erfassung. Es wurden lediglich URLs erfasst, wenn es sinnvoll erschien, auf Online-Quellen hinzuweisen, die im Zusammenhang mit der Aufnahme standen.

**Comment by ruschein** [comment]
Bitte einigt Euch, so dass wir Entwickler entweder etwas implementieren können oder, dass man das Issue zumachen kann.  Danke.

**Comment by IxTheoKm** [comment]
Nach Rücksprache mit thefass _keine_ Implementierung! Es sind zu wenige migrierte Aufsätze betroffen, als dass sich der Aufwand lohnt.
