### ISSUE TITLE
Anzahl der Einträge in einer Facette

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#223]
Die Anzahl der Zeilen, die innerhalb einer Facette angezeigt werden, wenn auf "mehr" klicke, ist derzeit auf maximal 30 Zeilen beschränkt. Es gibt aber für manche Facetten deutlich mehr. 
Wenn ich z.B. den Gesamtbestand aufrufe, und hier mit der Facette "Sprache" einschränke, werden 30 Zeilen bei "mehr" angezeigt. In der erweiterten Suche gibt es aber ca. 100 Sprachen. Auch in anderen Facetten ist das der Fall.
Es sollte irgendwo zum Ausdruck kommen, dass es ggf. mehr als die angezeigte Auswahl gibt. 
Und vor allem sollte klar sein, wie ich auf die nicht angezeigten Einträge einschränken kann.

**Comment by thefass** [comment]
Die Limitierung in den Facetten ist ein großes Problem, da dort nach Häufigkeit sortiert wird.
In den meisten Fällen ist aber eine Sortierung nach Alphabet sinnvoller, am besten, man kann die sortierung nach Alphabet oder Häufigkeit selbst einstellen.
Aber selbst mit einer anderen Sortiermöglichkeit ist das Problem noch nicht behoben, da man in einigen Fällen an alle Facetten herankommen muss. Z.B. bei den Sprachen aber auch bei den Facetten
Wir haben das Problem schon diskutiert, es gibt aber mit den Bordmitteln von VuFind keine schnelle Lösung. deswegen muss das eigenständig programmiert werden.
Es ist gut, dass diese Aufgaber hier als Issue festgehalten wird.

**Comment by oobenland** [comment]
Die Idee mit einer erweiterten Anzeige, in der man eine Facette sortieren/durchsuchen kann haben ist in der Planung, wie Martin sagt.
Aber ich möchte hier nochmal darauf hinweisen, dass der Ablauf einer Suche in VuFind nicht so funktioniert. Diese Zeilenbeschränkung ist erst ein Problem, wenn man eine leere Suche startet um erst mit den Facetten einzuschränken, bevor man ein Suchwort eingibt. 
Aber bei einer Suche sollten erst ein oder zwei Suchworte eingetragen werden um dann die Treffermenge mit Facetten einzuschränken. Bei solch einer Suche gibt es das Problem nur selten. Und wenn ein Benutzter dieses Problem haben sollte, dann ist er damit gezwungen seine Suche spezifischer zu gestalten, oder mit einer anderen Facette voreinzuschränken.

**Comment by IxTheoKm** [comment]
Ist dieses Problem nicht inzwischen gelöst? Kann dies geschlossen werden?

**Comment by jriedl** [comment]
Durch die Verwendung des Ansatzes mit Lightbox (das ist das Fenster, das jetzt aufgeht, wenn man auf "Mehr" klickt), besteht keine prinzipielle Beschränkung der Anzahl der anzeigbaren Facetten mehr.
