### ISSUE TITLE
Funktion Email

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#225]
kann man in die Email funktion einbauen, dass man mehrere Adressaten eingibt?

**Comment by thefass** [comment]
Als Betreff einer Email wird folgendes generiert:
Sprachauswahl **deutsch**
Datensatz Bibliothekskatalog: Claude Raison: Was ich Jesus fragen würde
Sprachauswahl **englisch**
Library Catalogue Record: Popular music in conversation with Christian faith

Der erste Teil ist wohl feststehend. Nach dem Doppelpunkt kommt Autor und Titel des Datensatzes, den man verschickt.
Bitte den feststehenden Teil so abändern:
in deutsch
IxTheo Datensatz: 
in englisch
IxTheo Record:

**Comment by oobenland** [comment]
Ich nehme an, dass man mehrere E-Mail Adressaten durch Kommata getrennt angeben kann. Aber es gibt zurzeit ein Problem mit der Konfiguration von der E-Mail Funktion, so dass die E-Mails wahrscheinlich nicht ankommen...

**Comment by thefass** [comment]
wenn ich zwei Adressen eingebe, getrennt durch Kommata oder durch Semikolon oder nur duch Leerzeichen, dann kommt die Fehlermeldung:
"Bitte geben Sie eine E-Mail-Adresse ein"

Das Versenden an nur eine Adresse funktioniert momentan.

**Comment by oobenland** [comment]
Ok, ich habe eine Einstellung gefunden, welche unter anderem die Anzahl von E-Mail-Adressen beschränkt.

Aus Sicherheitsgründen (um nicht zu einer Spamverteilerplattform zu werden) werde ich die Einstellungen so abändern, dass die Absenderadresse auf die Benutzer-Adresse voreingestellt sein wird, ohne dass man diese ändern kann. Außerdem werde ich bis zu 10 Empfänger-Adressen erlauben.

**Comment by thefass** [comment]
Heißt das Einstellen der Absenderadresse auf die Benutzer-Adresse, dass man eingeloggt sein muss (also auch auch ein Konto angelegt haben muss), um eine Mail verschicken zu können?

**Comment by oobenland** [comment]
Ja, aber das war vorher auch schon so.

**Comment by thefass** [comment]
ok. man wird ja auch direkt auf die Login MAske weitergeleitet.
Dass die Absenderadresse dann direkt eingetragen ist, ist ja sehr praktisch. Ich würde aber trotzdem zulassen, dass eine andere Adresse nachträglich eingetragen werden könnte.
Wenn man eine Mail nur nach Login verschicken kann, dürfte das Sicherheitsrisisko für Spam mißbraucht zu werden, doch sehr gering sein. Oder sehe ich das falsch?

**Comment by thefass** [comment]
funktioniert
