### ISSUE TITLE
Zählung im Browsingmodus

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#226]
Die Zählung der Datensätze im Browsingmodus ist falsch. 
![bildschirmfoto 2016-05-31 um 21 11 03](https://cloud.githubusercontent.com/assets/14169098/15687319/64186dba-2774-11e6-870f-e0a1bf0a284a.png)

dort werden bei der SW Folge folgende Zahlen angegeben
 Bergpredigt / Aufsatzsammlung 	3 	Datensätze ansehen
Bergpredigt / Aufsatzsammlung / Exegese 	1 	Datensätze ansehen 

Sieht man sich die Datensätze aber an, dann hat
 Bergpredigt / Aufsatzsammlung 8 Aufsätze
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Aufsatzsammlung%2FBergpredigt%22&type=Keywordchains
und
Bergpredigt / Aufsatzsammlung / Exegese 3 Aufsätze
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Aufsatzsammlung%2FBergpredigt%2FExegese%22&type=Keywordchains

Ursachen?
evt: mehrere SW Folgen
oder evt:
die richtige SW Folge steht nicht an erster Stelle in der 689 0

**Comment by jriedl** [comment]
Sollte nach Abschluss des Imports heute Abend behoben sein

**Comment by thefass** [comment]
erledigt.
