### ISSUE TITLE
Sortierungsproblem Trefferliste und nicht recherchierbare Erscheinungsjahre

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#227]
Der Nutzer kann nach Neuesten oder Ältesten Titeln sortieren. Das ist nicht nur praktisch, sondern in vielen Fällen besser und entscheidender als die Relevanzsortierung.

**Problem**
Es gibt in den Metadaten 2 verschiedene Datumsangaben: Es muss zwischen dem Datum _Erscheinungsjahr_ und dem Datum _Berichtsjahr_ unterschieden werden.
Was ist der Unterschied?
Ein Aufsatz erscheint gedruckt in 1978. In diesem Fall ist Erscheinungsjahr und Berichtsjahr identisch.
Nun wird 2009 der gedruckte Aufsatz elektronisch erneut veröffentlicht. Berichtsjahr bleibt 1978, Erscheinungsjahr ist aber 2009. Beim Sortieren erscheint der 1978 geschriebene Aufsatz dann aber unter 2009. Dieser Effekt ist natürlich unerwünscht, da der Nutzer bei der zeitlichen Sortierung die neuest oder ältest produzierte Literatur finden will und nicht, wann ein bestimmter Aufsatz als Medientyp veröffentlicht wurde.

**Iststand**
Momentan wird nur nach Erscheinungsjahr sortiert

Beispiel, das die unerwünschte Sortierung zeigt:
![bildschirmfoto 2016-06-01 um 09 45 09](https://cloud.githubusercontent.com/assets/14169098/15702009/cfee10da-27dd-11e6-864f-99a4392bf78b.png)

**Comment by thefass** [comment]
Ich kopiere den Kommentar von @IxTheoKm hier:

Das Erscheinungsjahr muss bei **Monographien** Sortierungskriterium sein.

Wenn bei **Aufsätzen** das Berichtsjahr als Sortierkriterium gelten soll, kommt m.E. nur 4070 $j (MARC: 936 |j) in Frage.

Für Ihr Beispiel:
4070 $v69$j1978$h1-2$p36-72
936 u w |d 69  **|j 1978**  |e 1-2  |h 36-72 

Ob das für VuFind umzusetzen ist, kann ich nicht beurteilen.

Es gibt auch Fälle mit Doppeljahrgängen, oder in denen das Erscheinungsjahr stark vom Berichtsjahr abweicht. Aber bei Zeitschriftenaufsätzen halte ich das Berichtsjahr für vorrangig.

Beim Doppeljahrgang müsste dann definiert werden, welches für die Sortierung zu verwenden ist. In älteren Daten wird das zweite Jahr in $j auf zwei Stellen verkürzt. Das spricht dafür ggf. immer das erste zu nehmen. In neueren Aufnahmen sind die Jahrgänge beide vierstellig.

 Bsp. 330161512
4070 $v73/74$j1973/74$p63-84
936 u w |d 73/74  **|j 1973/74**  |h 63-84

358301947
4070 $v88/89$j2009/2010$p179-198$y88/89.2009/10 (2011), S. 179-198
936 u w |d 88/89  **|j 2009/2010**  |h 179-198  |y 88/89.2009/10 (2011), S. 179-198

Es könnte theoretisch auch mal Fälle geben, in denen $j fälschlicherweise nicht erfasst wurde. Das ist mir bei den „Adv-Sätzen“ manchmal aufgefallen: Zeitschriften, die in der ZDB mit Satztyp Schriftenreihe erfasst wurden. In diesen Fällen werden Aufsätze mit den Bandsätzen, nicht mit der übergeordneten Zeitschriftenaufnahme verknüpft, und da kam das manchmal vor. Ich habe es dann korrigiert, aber es könnte trotzdem noch Fälle geben. Da wäre ein VuFind-Fehlerprotokoll gut, so dass man das berichtigen kann.

**Comment by thefass** [comment]
**Umsetzungsregel**

1. Standardsortierung bleibt das Erscheinungsjahr
260 $c

2. Bei Aufsätzen und Rezensionen wird nach Berichtsjahr sortiert
936 $j

3. In den Fällen eines Doppeljahrgangs wird nach dem ersten ersten Jahr sortiert

4. Fehlt bei Aufsätzen / Rezensionen das Berichtsjahr (936 $j) greift die Standardsortierung
Diese Fälle sollten protokolliert werden, so dass sie bereinigt werden können

**Comment by IxTheoKm** [comment]
Weiteres Beispiel für "unerklärliche" Sortierung:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&limit=10&filter%5B%5D=publishDate%3A%22%5B1912+TO+2012%5D%22&sort=year

Einschränkung nach Erscheinungsjahren 1912-2012, Sortierung nach "Neueste zuerst".

Der erste Treffer 378502980 wird mit Erscheinungsjahr 2002 angezeigt, dann folgen die Titel mit 2012.
Erklärung: in 534 |c ist die Sortierform eines anderen Erscheinungsjahres angegeben (2013 hier möglicherweise nicht korrekt). 
Abweichende Sortierformen können häufiger vorkommen. Sie sollten dann auch angezeigt werden.

**Comment by IxTheoKm** [comment]
Weiteres Sortierungsproblem: abweichende Zeitrechnungen
https://www.ixtheo-test.de/Record/257944389
Hier wird nach dem Hidschra-Jahr 1345 sortiert. Es sollte aber unter 1966 sortiert werden.

Erfassung in PICA:
1100 _1966_$n[1345 h.š. = 1966]   
Erscheinungsjahr in _Sortierform_$nErscheinungsjahr in Vorlageform

Marc-Export bei alten Aufnahmen in 008, 260 usw.
s. http://swbtools.bsz-bw.de/cgi-bin/help.pl?cmd=kat&val=1100&verbund=SWB&regelwerk=RAK
Marc-Export bei RDA-Aufnahmen in 264 usw.
s. http://swbtools.bsz-bw.de/cgi-bin/help.pl?cmd=kat&val=1100&verbund=SWB&regelwerk=RDA

**Comment by IxTheoKm** [comment]
Weiteres Sortierproblem:
scheinbar ordnen die nach RDA katalogisierten neuen Titel am Ende der mit "neueste zuerst" sortierten Liste: https://ixtheo-test.de/Search/Results?lookfor=superior_ppn:015192091

**Comment by IxTheoKm** [comment]
Das letzte geschilderte Problem liegt möglicherweise an der Erfassungsart der meisten RDA-Aufnahmen, und es führt dazu, dass diese Titel bei der Suche in Kombination mit dem Erscheinungsjahr gar nicht gefunden werden. Bsp.: https://ixtheo-test.de/Record/474050319#details
Die Erfassungsform in der WinIBW lautet 1100 2016$n[2016]
In der Trefferliste der verknüpften Aufsätze stehen sie ganz am Ende.

Ich sehe allerdings keinen Unterschied im Marc-Format zwischen den Aufnahmen mit und ohne Klammern:
Bsp. ohne Klammern: https://ixtheo-test.de/Record/446280399#details

**Comment by IxTheoKm** [comment]
Grundsatzproblem bei Unterschieden zwischen Berichts- und Erscheinungsjahren für Aufsätze und Rezensionen:
will jemand eine Gesamtmenge auf bestimmte Jahre einschränken, hat er nur die Facette für Erscheinungsjahre zur Verfügung. 
Sucht also jemand nach einem bestimmten Jahrgang einer Zeitschrift, wird er nicht wissen, dass Berichts- und Erscheinungsjahre voneinander abweichen können und seine Suche über die Facette "Erscheinungsjahr" einschränken.

Weitere Facette für Jahrgänge/Berichtsjahre von Zeitschriften einrichten?

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Welcher Zusammenhang besteht konkret zum Thema #240?

**Comment by IxTheoKm** [comment]
Siehe bei #240 meinen Kommentar vom 17.11.2016.
Ich konnte nicht feststellen, ob/welche Aufsätze zum Erscheinungsjahr fehlten:
"_Die 15 fehlenden Aufsätze ließen sich doch einigermaßen schnell über die Titel-Differenz bei den Erscheinungsjahren ermitteln,
(außer bei Erscheinungsjahr 2015: s. #227 !
[2015] in eckigen Klammern lässt sich nicht recherchieren und taucht bei der entspr. Facetteneinschränkung nicht auf).
Alle fehlenden Aufsätze und die Rezension haben Erscheinungsjahr 2014._"

**Comment by jriedl** [comment]
Gibt es hier mit Ausnahme der offenen Frage nach einer weiteren Facette noch offene inhaltliche Punkte?

**Comment by IxTheoKm** [comment]
Ich habe die verschiedenen Fälle nochmal getestet: das funktioniert nun alles korrekt.
Offen ist tatsächlich nur noch die Frage nach der Facette für Berichtsjahre. Ich lege dafür ein neues Issue in tuefind an.
