### ISSUE TITLE
Suche über "Alle Felder"/Benutzungshinweis?

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#229]
Titel, die noch nicht über das Feld 801 für die Bibelstellensuche erfasst werden, aber bereits im WinIBW mit der Bibelstelle verschlagwortet sind, findet man nicht, wenn man in der Suche über "Alle Felder" das Kürzel für die Bibelstelle eingibt, z.B. "Mt 15,21-29"(PPN 465220061). 
Man kann diesen Titel jedoch über die Eingabe "Matthäusevangelium 15,21-29" über die "Alle Felder"-Suche finden. 
Bei Titeln, deren Bibelstelle im Feld 801 erfasst ist, bzw. die Abkürzung im Titel steht (z.B. Mt 10 (PPN 453207936)) sind auch über die Eingabe des Abkürzung über die "Alle Felder"-Suche auffindbar.

Bis alle Titel, die Bibelstellen behandeln, über die Bibelstellensuche auffindbar sind, würde ich vorschlagen, in den Benutzungshinweisen zu vermerken, dass man nicht nur nach den Bibelstellen-Abkürzungen suchen sollte, sondern auch nach den ausgeschriebenen Büchern, also z.B. "Markusevangelium 15" statt "Mk 15".

**Comment by thefass** [comment]
@Mannsperger :: die öffentliche Freischaltung soll ja erst am 25.7.2016 erfolgen. Bis dahin ist das Problem hoffentlich gelöst und die Benutzungshinweise würden sich erübrigen.
Wenn nicht, dann denken wir Ende Juli darüber nach, wie man das an den Nutzer bringt.

**Comment by IxTheoKm** [comment]
Das Problem scheint auf anderer Ebene zu liegen:
für einige Bibelstellen mit neuer RDA-Struktur wird das Feld 801 erzeugt, für andere dagegen nicht.
Ich kann keine Unterschiede feststellen, die das unterschiedliche Verhalten erklären. 
Bsp.:

443182132
689 	0 	0 	|D u  |0 (DE-588)1069929050  |0 (DE-576)429610432  |2 gnd  |t Bibel  |p Markusevangelium  |n 13,30

689 	1 	0 	|D u  |0 (DE-588)4037658-8  |0 (DE-576)209025816  |2 gnd  |t Bibel  |p Markusevangelium

801 			|a 0200000_0299999

**Comment by thefass** [comment]
den einzigen Unterschied, den ich erkenne, ist der Indikator 0 in der 689. Der Fall, der umgesetzt wird, hat den Indikator 1. Hier wird ja die 689 durchgezählt, das ist aber zerobasiert
@ruschein : kannst Du Dir das bitte mal anschauen?

**Comment by thefass** [comment]
gelöst
