### ISSUE TITLE
Medienart "Schriftenreihe"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#230]
Woher kommt bei ID 109403185 ATLA religion database die Medienart "Schriftenreihe"?
https://ptah.ub.uni-tuebingen.de/Record/109403185

Ich finde im Internformat keinen Hinweis darauf. Nur auf Datenbank oder Bibliographie.

Weitere ATLA-RDB-Beispiele s. 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=atla+religion+database&type=AllFields

**Comment by IxTheoKm** [comment]
Warum wird bei der Vollanzeige eines Stücktitels einer Zeitschrift "Schriftenreihe" verwendet?
https://ptah.ub.uni-tuebingen.de/Record/398082456

Kann man bei Bänden, die entweder mit Schriftenreihen oder Zeitschriften verknüpft sind, nicht unterscheiden?
In den Gesamtaufnahmen der verknüpften Zeitschriften ist der Typ m.W. in 008 zu finden.
Im genannten Beispiel:
008 880819c18259999xx **p** 0ger c   

**p** steht wohl für periodical, **m** für monographic series. Ich habe aber keine MARC-Formatdokumentation, um das belegen zu können. Ich schließe das nur aus diesem Dokument:
http://files.dnb.de/pdf/marc_bd.pdf

Wenn nicht unterschieden werden kann, sollte vielleicht ein neutraler Begriff statt "Schriftenreihe" verwendet werden. Evtl. "Quelle"?

**Comment by jriedl** [comment]
Zu 109403185: Im Leader an der Stelle 7 (Zählung ab 0) steht ein 's', deshalb die Zuordnung zu Schriftenreihe.

Zu 398082456: Auf ptah wird es derzeit als Buch/Festschrift geführt

**Comment by IxTheoKm** [comment]
Zu 398082456:
ich meine die Bezeichnung "Schriftenreihe" nach dem Feld "In" (s. 490 und 830):

In: 	Homiletisch-liturgisches Korrespondenzblatt
Schriftenreihe: 	Homiletisch-liturgisches Korrespondenzblatt 30 = 112/113

**Comment by IxTheoKm** [comment]
zu 109403185:
verstehe ich nicht. 
Weitere Beispiele:
Im Leader von PPN 015918653 steht auch an Stelle 7 ein 's'. Da ist die Zuordnung korrekt (Zeitung)
Oder bei PPN 334013682. Trotz 's' hier korrekt Zeitschrift.

**Comment by jriedl** [comment]
zu 398082456: Warum ist hier der Terminus "Schriftenreihe" falsch, wenn es sich um ein Buch handelt?
Würde es Sinn machen, die Bandangabe nach "In" zu verschieben und den Reihentitel als "Schriftenreihe" zu fassen?

**Comment by jriedl** [comment]
zu 015918653: Hier steht im Gegensatz zu 109403185 im Feld 008 an der Stelle 21 ein 'n', bei 334013682 ein 'p'. Für das 'u' von 015918653 gibt es keinen Fall und es wird deshalb als "Serial" = Schriftenreihe gefasst.

**Comment by IxTheoKm** [comment]
zu 398082456: 
Dieses Buch ist ein Stücktitel einer **Zeitschrift**. 
Korrekt wäre
**Zeitschrift**: 	Homiletisch-liturgisches Korrespondenzblatt 30 = 112/113

Vgl. Sie PPN 015712052
https://ptah.ub.uni-tuebingen.de/Record/015712052

Oder 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=homiletisch-liturgisches+korrespondenzblatt&type=Title

Hier ist in der Kurztitelanzeige im ersten Eintrag korrekt "Zeitschrift" angegeben.
Daher verstehe ich nicht, warum in der Vollanzeige des damit verknüpften Stücktitels "Schriftenreihe" steht.

**Comment by ruschein** [comment]
@IxTheoKm : Frau Kellmeyer, wäre es akzeptabel anstatt "Schriftenreihe" "Schriftenreihe/Zeitschrift" anzuzeigen?  Ich habe mir das mal genauer angeschaut.  Das Problem ist, es ist eine Übersetzung von statischem Text aus dem Englischen und dort lautet es dann "Series".  Wir haben zur Zeit kein Feld für den Medientyp des übergeordneten Werks im untergeordneten Werk und das könnte sonst etwas aufwendig werden.

**Comment by IxTheoKm** [comment]
Ich finde die Anzeige so akzeptabel.

Was mir aber immer noch unklar ist (s. erster Eintrag in diesem Issue):
https://ptah.ub.uni-tuebingen.de/Record/109403185
Woher kommt bei der Datenbank die Bezeichnung "Medienart: ... | Schriftenreihe | ..." ?
Ist das dann auch das Übersetzungsproblem von "Series"?

**Comment by ruschein** [comment]
@IxTheoKm : Ja, das war anscheinend eine andere Übersetzung.  Im Englischen heißen die "Series" und "Serial".  Ich habe jetzt beide angepasst.

**Comment by IxTheoKm** [comment]
M.E. nach jetzt so akzeptabel.
