### ISSUE TITLE
Schreibfehler

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#231]
Hier (https://www.ixtheo-test.de/Browse/Home) steht "Klassification" statt "Klassifikation" - ich denke man sollte die Benennung in "Klassifikation" umändern:
![klassfic](https://cloud.githubusercontent.com/assets/16759964/15959942/9c9fec7c-2efd-11e6-825a-9bb1a9897887.png)

**Comment by Mannsperger** [comment]
Auch in der erweiterten Suche steht "DDC-Klassification" statt "DDC-Klassifikation"
![schreibf](https://cloud.githubusercontent.com/assets/16759964/16148274/cedd28fe-3488-11e6-84d0-57f79d5fbf5d.png)

(https://www.ixtheo-test.de/Search/Advanced)

**Comment by thefass** [comment]
erledigt
