### ISSUE TITLE
fehlende Suchergebnisse

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#235]
Wenn man im Moment über "Katalog browsen" über nach "Thema (Schlagwort)" und dann "nach Verfasser" auswählt, erhält man gerade keine Ergebnisse (https://www.ixtheo-test.de/Browse/Topic?findby=publisher&query_field=topic_facet). 
"Nach Verlag", "Alphabetisch" und "nach IxTheo-Klassifikation" liefert jedoch Ergebnisse.
![nach verfasser](https://cloud.githubusercontent.com/assets/16759964/16145460/fef7e192-3478-11e6-8714-d0047e4764dd.png)

**Comment by Mannsperger** [comment]
Klickt man auf "unzugewiesen" bzw. "unassigned", so erhält man keine Ergebnisse.
Über die Suche über die DDC-Klassifikation passiert gar nichts wenn man auf das Feld klickt:
![unzug](https://cloud.githubusercontent.com/assets/16759964/16146642/753018c4-347f-11e6-92bf-dd048114d526.png)(https://www.ixtheo-test.de/Browse/Dewey?findby=%22[Unassigned]%22&query_field=dewey-hundreds)
bei der Suche über die anderen Kategorien (IxTheo-Klassifikation, Thema (Schlagwort), Verfasser, Verlag) wird jeweils die Meldung "keine Ergebnisse" angezeigt, wenn man auf "unzugewiesen" klickt.
![no res](https://cloud.githubusercontent.com/assets/16759964/16146670/9f0a25ae-347f-11e6-931e-49689417c91b.png)

**Comment by Mannsperger** [comment]
Will man eine Suche einschränken, so funktioniert es, z.B. auf „elektronisch“ zu klicken.
https://www.ixtheo-test.de/Search/Results?join=AND&bool0[]=AND&lookfor0[]=mohr&type0[]=publisher&filter[]=mediatype%3A%22Electronic%22

Will man aber bei einer erweiterten Suche das Material auf „elektronisch“ oder eBook beschränken und lässt den Suchschlitz frei, erhält man keine Ergebnisse. 
![ebook](https://cloud.githubusercontent.com/assets/16759964/16148036/459dab0a-3487-11e6-8f2d-a9f95b22a780.png)
![elektronisch](https://cloud.githubusercontent.com/assets/16759964/16148069/768a063c-3487-11e6-905d-1f7731c8a68f.png)
Wenn man aber zum Beispiel nach „Zeitschrift“ oder „Buch“ einschränkt, erhält man Ergebnisse.
![book](https://cloud.githubusercontent.com/assets/16759964/16148074/7ac65f2a-3487-11e6-87c5-94ebd8ab6449.png)

**Comment by Mannsperger** [comment]
Beim Browsen des Katalogs über die Ixtheo-Klassifikation nach Thema werden als "Unassigned" 1.519.008 Titel angezeigt, klickt man jedoch auf dieses Feld, so erhält man die Meldung "keine Ergebnisse". 
![keinerg](https://cloud.githubusercontent.com/assets/16759964/15960706/4c3dcc50-2f01-11e6-8ce8-e0060c2e59f2.png)(https://www.ixtheo-test.de/Browse/IxTheo-Classification?findby=topic&category=&query=%22[Unassigned]%22&query_field=topic_facet&facet_field=ixtheo_notation_facet)

**Comment by Mannsperger** [comment]
Dasselbe passiert, wenn man nach "Verlag" auswählt:848.575 (Unassigned)
![nachverlkeinerg](https://cloud.githubusercontent.com/assets/16759964/15960790/be451452-2f01-11e6-98e2-7ab2a87822c8.png)

**Comment by IxTheoKm** [comment]
Habe die Suchanfragen, soweit ich sie verstanden habe und soweit es überhaupt noch so aussieht wie in der urspr. getesteten Version, nachvollzogen. Das funktioniert jetzt.

Die letzten beiden Einträge/Probleme "_Will man aber bei einer erweiterten Suche das Material auf „elektronisch“ oder eBook beschränken und lässt den Suchschlitz frei, erhält man keine Ergebnisse._"  und "_Wenn man aber zum Beispiel nach „Zeitschrift“ oder „Buch“ einschränkt, erhält man Ergebnisse._" verstehe ich nicht wirklich.

**Comment by thefass** [comment]
die Medienart eBook gibt es nicht mehr, da wir das allegemeiner aufgesetzt haben. Insofern hat sich das Problem aufgelöst
