### ISSUE TITLE
Zurücktaste?

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#238]
Wenn man eine Recherche betreibt, ist es manchmal gut, wenn man zur Übersicht zurückspringen kann. Momentan kann man nur zwischen der Anzeige der Titel hin- und herwechseln, so wie ich es verstehe.
Deswegen kann man bislang nur zur vorherigen Übersichtwechseln mit der "Zurück-Taste" im Internet-Browser, wodurch jedoch das Dokument erlischt.
![erloschen](https://cloud.githubusercontent.com/assets/16759964/16147478/9cfd95bc-3483-11e6-8d30-842abb8fae5e.png)
Deswegen meine Anfrage: Könnte man eine Zurück-Taste einrichten, wie es sie zum Beispiel hier im Katalog der WLB gibt:
![zuruck](https://cloud.githubusercontent.com/assets/16759964/16147491/b5a360d8-3483-11e6-9fd7-e0f0945f866b.png)
(https://wlb.ibs-bw.de/aDISWeb/app;jsessionid=ECB6FDC3D57EC4A64CFAEEB3BEEB0964)

**Comment by oobenland** [comment]
Dass das Dokument erlischt, ist komisch. Aber es gibt auch ein Zurückknopf, der oben rechts zu finden ist. Wenn man da auf "Suchen" in der grauen Box klickt.
![bildschirmfoto vom 2016-08-11 14 59 17](https://cloud.githubusercontent.com/assets/1352796/17589307/43af0e4c-5fd4-11e6-8d42-9597811bdce6.png)
