### ISSUE TITLE
Nicht gelieferte Titel, Korrekturen, Löschungen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#240]
Titel, an denen zu viele Lokalsätze hängen, werden nicht geliefert, da der MARC21-Export mit allen Lokalsätzen zu groß ist. die Folge: der Link aus untergeordneten Titeln (Aufsätzen) führt ins Leere.
Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/453206131
https://ptah.ub.uni-tuebingen.de/Record/094480885

PPN 094480885 Zeitschrift für die neutestamentliche Wissenschaft (Online-Ausgabe)

_**[Lieferung jetzt o.k.]**_

**Comment by ruschein** [comment]
Ich habe mittlerweile eine Teillösung die demnächst (evtl. morgen) aktiviert sein sollte.  Die SRU-Schnittstelle, welche das BSZ zur Verfügung stellt ist leider sehr fehlerhaft.  Immerhin schaft mein neuer Code 187 der 217 nicht ausgelieferten Objekte damit bei uns einzuspielen.

Die Liste der PPNs die mein neues Tool nicht herunterladen kann ist wie folgt:
466721854
190208481
1901751097
1902026297
1902304957
1902514767
1902922887
1903695077
1905096357
1911568847
1911599807
1911787997
1912732957
1915538247
1919048057
1921229917
19240489X7
1925399817
1933842807
1938698107
1939340867
19409913X7
19546009X7
1955063327
1959082797
1966892527
1968038107
1974277747
1983736197
1986340997

**Comment by thefass** [comment]
mir fällt folgendes auf:
außer den ersten 2 PPN haben alle anderen ein 7 am Ende und dazu eine Stelle mehr als sonst üblich. Wenn man danach sucht, dann hat man in der WINIBW bei diesen 7er-PPN auch keine Treffer. 
Ich habe aber keine Idee, was hinter diesen seltsamen PPNs steckt

**Comment by ruschein** [comment]
Diese "PPNs" sind aus einer Fehlerliste die beim Datenexport beim BSZ entsteht und mir so vom BSZ geliefert worden.

**Comment by IxTheoKm** [comment]
Ich weiß nicht, ob dasselbe Problem dahinter steckt, darum vorsichtshalber zur Info:
Die Zeitschrift 014536625 mitsamt ihrer Bände und Aufsätze ist in ptah nachgewiesen, aber nicht im Test-IxTheo. Dort fehlt alles

**Comment by IxTheoKm** [comment]
Titel fehlen in ptah und ixtheo-test:
am 18.7.2016 wurden zu der Zeitschrift https://ixtheo-test.de/Search/Results?lookfor=superior_ppn:015192091 weitere Hefte katalogisiert. 49.2014,2 bis 51.2016,1. Die sind am 15.8. nicht nachgewiesen

**Comment by IxTheoKm** [comment]
Folgende Titel die am 25.7.2016 katalogisiert wurden, sind nicht im IxTheo nachgewiesen:
Es fehlen 66.2015 Hefte 2, 3 und 4 und 67.2016 Hefte 1 und 2 von Kerk en theologei https://ixtheo-test.de/Search/Results?lookfor=superior_ppn%3A015538842&type=AllFields&page=54

**Comment by IxTheoKm** [comment]
Von der Zeitschrift PPN 079877109 fehlen über 50 Aufsätze oder Stücktitel

**Comment by IxTheoKm** [comment]
Am Montag 8.8.2016 katalogisierte Titel sind nicht im IxTheo nachgewiesen. (Für diese Zeitschriften wollte ich den Alert-Service testen):
PPN 052644464 Contagion Hefte 20.2013 bis 22.2015
PPN 055886515 Horeb Heft 23.2014,3=69

**Comment by IxTheoKm** [comment]
Korrektur von Montag 8.8.2016 ist am 16.8. noch nicht umgesetzt: PPN 467089612

**Comment by IxTheoKm** [comment]
PPN 424766140: am 31.8.2016 wurde 5056 1 ergänzt. Der Titel ist noch nicht vorhanden.

Kann man irgendwo in der Datenbank einen Hinweis auf das letzte Importdatum verankern (so etwas wie "Stand: ..."). Dann ist wenigstens klar, ob die Suche nach einem bestimmten Titel einen Treffer geben müsste oder nicht bzw. ob bestimmte Korrekturen umgesetzt sein müssten.

**Comment by IxTheoKm** [comment]
Von PPN 01440236X  Ephemerides theologicae Lovanienses sind nur 755 Aufsätze und Rezensionen nachgewiesen. Im SWB sind 771 mit FID-Nummer 1 vorhanden.

**Comment by thefass** [comment]
Wir können das Probelem vermutlich nur lösen, indem wir die Datensätze finden, die fehlen.
@IxTheoKm Könnten Sie bitte aus der WinIBW die Datensätze (mit PPN) extrahieren und an ruschein schicken.
@ruschein Könntest Du bitte prüfen, welche der PPNs in IxThepo fehlen.

**Comment by IxTheoKm** [comment]
Aus den 60 Rezensionen konnte ich PPN 420150633 als fehlend ausfindig machen.

Die 711 Aufsätze kann ich nur sehr mühsam abgleichen, weil die Sortierung im IxTheo nicht stimmt. Man kann auch die Liste der Aufsätze als ganze nicht exportieren, so dass ich mit einer Exportliste arbeiten könnte. Das Ergebnis kann ich also nicht sehr schnell liefern

**Comment by IxTheoKm** [comment]
Die 15 fehlenden Aufsätze ließen sich doch einigermaßen schnell über die Titel-Differenz bei den Erscheinungsjahren ermitteln, 
(außer bei Erscheinungsjahr 2015: s. #227 ! 
[2015] in eckigen Klammern lässt sich nicht recherchieren und taucht bei der entspr. Facetteneinschränkung nicht auf).
Alle fehlenden Aufsätze und die Rezension haben Erscheinungsjahr 2014.

Fehlende Titel mit ihren Erfassungs- und Korrekturdaten:
420150633	27.11.2014/ korr. 3.12.2014 [Rezension]
420149945       - " -          /    - " -
420149821       - " -          /    - " -
420149074       - " -          /    - " -
420141871       - " -          /    - " -
42014109X       - " -          /    - " -
416447961       3.11.2014 / korr. 5.11.2014
416447368       - " -          /    - " -
416446590       - " -          /    - " -
416445063       - " -          /    - " -
416444733       - " -          /    - " -
416443265       - " -          /    - " -
416443028       - " -          /    - " -
416442765       3.11.2014 / korr. 4.11.2014
416442331       - " -          /    - " -
416442056       - " -          /    - " -

Es gibt aber auch Titel mit denselben Erfassungs- und Korrekturdaten, die im IxTheo vorhanden sind.

**Comment by IxTheoKm** [comment]
Der Datenstand auf ptah und IxTheo-Test ist schon seit Oktober abweichend:
PPN 014944790 Katechetische Blätter.
Auf ptah sind 4670 Aufsätze und Rezensionen (55 zuviel).
In IxTheo-Test sind es korrekt 4615.

Wird der Datenstand nicht regelmäßig angepasst?
Wo soll was eher getestet werden? Datenstand in IxTheo-Test, anderes auf ptah?

**Comment by IxTheoKm** [comment]
PPN 111552591 (=ISSN 1613-0928) fehlt im IxTheo. Wegen zu vieler Lokaldaten? War das Problem nicht schon mal gelöst?

**Comment by IxTheoKm** [comment]
https://ixtheo-test.de/Record/476291119
https://ixtheo-test.de/Record/476291046
...
sind schon lange aus den Primärdaten gelöscht und werden immer noch angezeigt.
Vgl. https://ixtheo-test.de/Search/Results?type=AllFields&sort=title
Treffer 16 bis 30 "Kein Titel verfügbar"

**Comment by IxTheoKm** [comment]
Wenn in Normdaten Änderungen/Ergänzungen erfolgen, werden die damit verknüpften Titel offensichtlich nicht entsprechend korrigiert/ausgeliefert. 
Bsp.: 
zum Test wurde im Schlagwortsatz PPN 213521458 "Samaniden" die englische Verweisung "Samanid Dynasty" ergänzt. Die beiden Titel PPN 383726832 und 04477804X sind darunter nicht recherchierbar, nur unter der bisherigen englischen Verweisung "Samanids" (27.2.2017).

Das Problem wird vermutlich bei jeder Änderung von Autoren- oder Schlagwortnormsätzen relevant:
Titel werden mit dem jeweils aktuellen Stand der verknüpften Normsätze geliefert.
Neue Titel, die _nach_ der Änderung eines Normsatzes verknüpft werden, werden abweichend von den früher gelieferten Titeln mit dem jeweiligen neuen Stand der verknüpften Normsätze geliefert.

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Zu gelöschten PPNs (z.B. 476291119):
Diese tauchen aktuell nicht mehr auf. Das hat vermutlich damit etwas zu tun, dass wir am 9. März einen neuen Komplettabzug erhalten haben. Falls das Problem erneut auftritt, bitte mit aktueller PPN in einem separaten Issue melden.

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Zum Thema "Kein Titel verfügbar":
Es gibt aktuell immer noch Titel bei denen das auftritt. Trotzdem haben wir bei Stichproben festgestellt dass es tatsächlich Datensätze gibt bei denen auch vom BSZ kein Titel mitkommt, z.B. PPN 484258222. Da sollte dann aber eher der Titel nachgetragen werden. Hier die Liste der PPNs die geprüft werden sollten (ermittelt da 245a leer):

091402956
091402964
28735363X
287353648
287382907
315720166
318401959
318401967
400929481
416953697
417241674
484258222
484262416
484262777
484263080
487881087
487881109
487882245
488278120

(Hinweis: Die Suchergebnisse sind übrigens aktuell auf ptah anders sortiert als auf ixtheo-test.de. Die PPNs sollten sich per Direktsuche nach ID aber auf beiden Systemen finden lassen)

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Zum Thema PPN 111552591 (ISSN 1613-0928 ) fehlt (vermutlich wegen zu großer Lokaldaten):
Wir können die PPN auch in den Originaldaten vom BSZ nicht finden. Allerdings gibt es mehrere Einträge die sich auf die ISSN beziehen. Wurde der alte Datensatz evtl in der Zwischenzeit gelöscht + mit neuer PPN neu angelegt? 
Falls das Problem noch besteht, bitte mehr Informationen zum Datensatz + ggf. neue PPN angeben, optimalerweise in separatem Issue.

**Comment by IxTheoKm** [comment]
Zum Thema "Kein Titel verfügbar":
die Titel der genannten PPNs (= Teile von mehrbändigen Werken) stehen in **245 $p**.
Die anderen werden gelöscht:
091402956	245 13$pLa quatrième campagne de fouilles à Ras-Sahmra : (printemps 1932)…
091402964	245 13$pLa cinquième campagne de fouilles à Ras-Sahmra : (printemps 1933)…
28735363X	245 10$p[Hauptbd.]
287353648	245 10$p[Hauptbd.]
287382907	245 10$pReligion
315720166	245 10$pBuch I bis VI
318401959	245 10$pFürbitten und Einführungsworte für die Wochentage 
318401967	245 10$pFürbitten und Einführungsworte für die Wochentage im Jahreskreis
400929481	245 14$pDie wirkliche Gegenwart des Leibes und Blutes Jesu Christi ...
416953697	245 10$pAllgemeine Korrespondenz : 2
417241674	245 10$pEinleitung und das erste Hauptstück

484258222	[habe mtex gesetzt; muss gelöscht werden, da dublett zu PPN 046693475]
484262416	[habe mtex gesetzt; ist maschinell von der Erzabtei Beuron ohne Titel und Jahr eingespielt]
484262777	[habe mtex gesetzt; muss gelöscht werden, da dublett zu PPN 046277285] 
484263080	[habe mtex gesetzt; ist maschinell von der Erzabtei Beuron ohne Titel und Jahr eingespielt]
487881087	[gelöscht; imwa-Einspielung]
487881109	[gelöscht; imwa-Einspielung]
487882245	[imwa-Einspielung; Nachbearbeitung erfolgt noch]
488278120	[gelöscht; imwa-Einspielung]

**Comment by jriedl** [comment]
https://github.com/ubtue/ixTheo/issues/240#issuecomment-282655032 Die Verweisungsformen der IxTheo-Übersetzungen Schlagwörter ("Samanid Dynasty") wird jetzt gefunden.

**Comment by IxTheoKm** [comment]
Die Verweisung "Samanid Dynasty" für das Schlagwort "Samaniden" wird vermutlich nur deswegen gefunden, weil die Titel mittlerweile durch einen neuen Gesamtabzug erneut geliefert wurden. Wenn in _Norm_sätzen eine weitere Änderung/Ergänzung erfolgt, werden die schon gelieferten _Titel_ nicht mit diesen Änderungen/Ergänzungen versehen, es sei denn sie werden irgendwann wieder neu geliefert.

Ich habe zum Test am 17.5.2017 die französische Form "Samanides" im Normsatz erfasst. Sie wird vermutlich nur durch die sog. Sekundärkorrekturen ausgeliefert.
Ggf. lege ich für diesen Komplex ein neues Issue an.

**Comment by jriedl** [comment]
Die Augentierung der Schlagworte mit Synonymen und Übersetzungen aus den Normdaten wird bei uns lokal vorgenommen. Hier werden die jetzt auch Verweisungsformen ausgewertet. Deshalb ergibt sich auch ein Unterschied bei der Suche nach "Samanid Dynasty" auf ixtheo (alter Stand) und ptah (neuer Stand).

**Comment by mtrojan-ub** [comment]
Auch hier fürs Protokoll: https://github.com/ubtue/ixTheo/issues/240#issuecomment-273794175 : Die PPN 111552591 (Der Islam) taucht jetzt ebenfalls auf, also 1 Problem weniger

**Comment by IxTheoKm** [comment]
Erledigt. Für die offenen Punkte sind eigene Issues angelegt
