### ISSUE TITLE
Funktionsbezeichnungen in der Kurzanzeige und in der Vollanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#255]
In den Funktionsbezeichnungen der beteiligten Personen fehlt die Großschreibung:
(mitwirkender) 
(herausgeberin)
(verfasserin)
(übersetzerin)
...

**Comment by IxTheoKm** [comment]
... und in der Vollanzeige bei den "weiteren Verfassern":
https://www.ixtheo-test.de/Record/446659711
Vgl.
https://www.ixtheo-test.de/Search/Results?type=AllFields&page=2
(Treffer 40)

**Comment by mtrojan-ub** [comment]
Ist vermutlich bereits behoben bzw. konnte es nicht reproduzieren => ready for testing.
Falls es doch noch drin ist, bitte Screenshot anhängen

**Comment by IxTheoKm** [comment]
Ist o.k.
