### ISSUE TITLE
Verknüpfung zum übergeordnetem Werk

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#291]
In diesem Fall gibt es eine Fehlermeldung, wenn man auf das übergeordnete Werk klickt (Zeitschrift für die alttestamentliche Wissenschaft)
https://ixtheo-test.de/Record/453180302

man findet komischerweise auch nicht den Datensatz mit der PPN
id:09453330X
https://ixtheo-test.de/Search/Results?lookfor=id%3A09453330X&type=Title&limit=20&sort=year

Das ist insofern komisch als die Gesamtaufnahme im SWB ist und dort auch unser Abzugszeichen SSg 1 hat
http://swb.bsz-bw.de/DB=2.1/SET=2/PRS=HOL/SHW?FRST=1&COOKIE=U998,Pbszgast,I17,B0728+,SY,NRecherche-DB,D2.1,Ef53dec36-620,A,H,R193.197.31.15,FY

**Comment by oobenland** [comment]
Ein Datensatz mit der PPN 09453330X ist nicht in unserem aktuellen Komplettabzug enthalten

**Comment by IxTheoKm** [comment]
Das dürfte wieder so ein Titel sein, der wegen zu vieler Lokaldaten nicht geliefert wird

**Comment by mtrojan-ub** [comment]
Datensatz ist wohl mittlerweile vorhanden + Fehlerverhalten nicht mehr reproduzierbar. schließen?

**Comment by thefass** [comment]
ok
