### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#30]
Die Links unter einem Titel werden missverständlich dargestellt:
als kostenfrei oder Volltext

Beispiel (erster Titel): http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Ave+sanctissima+Maria&type=AllFields&limit=20&sort=year

in der Detailansicht des Titels werden Sie zum Teil anders dargestellt (unter der Rubrik Online)
http://ptah.ub.uni-tuebingen.de/Record/36830485X

Im Internformat 856
Der erste Link ist die URL
Der zweite die Resolving der URN
Der dritte auch eine URL und funktioniert nicht
Der letze Link ist die urn. Wenn man draufklickt, hat man die Fehler meldung 404.
Resolvt ist die urn in link 2 (URN Resolving-System). Eigentlich reicht dieser Link

Der letzte sollte als URN angezeigt werden und nicht klickbar sein

In anderen Fällen verbirgt sich hinter "Volltext" das IHV oder der Klappentext. In beiden Fällen sollte das auch entsprechend benannt werden. Volltext ist missverständlich.

**Comment by ruschein** [comment]
Und, wie sieht es jetzt aus?  (Übrigens "Links" ist kein guter Titel für ein Issue.)

**Comment by thefass** [comment]
viel besser. 
Ungelöst ist aber noch die Anzeige der urn, die als Link "ubekanntes Material" ausgegeben wird.
Diskussion: Ist es nicht besser, in diesem Fall die urn anzuzeigen (meinetwegen auch als anklickbarer Link, d.h. resolvt, obwohl die Resolving der urn ja im zweiten Link steckt) anstatt "unbekanntes Material"?
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Ave+sanctissima+Maria&type=AllFields&limit=20&sort=year
Dann wäre die Info wenigstens die persistente Id an sich, die man sonst nur im intern Format sieht.

**Comment by ruschein** [comment]
Was sollen unsere Anwender mit der persistenten ID?  Wissen die überhaupt was das ist?  Und, damit wäre die Anzeige uneinheitlich.

**Comment by ruschein** [comment]
@thefass : Hallo Martin, was meinst Du zu meinem letzten Kommentar?  Können wird das Issue zumachen oder doch nicht?

**Comment by thefass** [comment]
An dieser Stelle wäre das tatsächlich uneinheitlich, da ja in der Volltitelanzeige "Online Zugang" angegeben ist.
