### ISSUE TITLE
Links 2 - neues Fenster

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#31]
Wenn man unter der Rubrik Online auf den Link klickt öffnet er sich im selben Fenster.

Bitte in einem neuen Fenster aufgehen lassen, so dass die VuFind Seite nicht überlagert wird

Beispiel: http://ptah.ub.uni-tuebingen.de/Record/416737390

**Comment by oobenland** [comment]
Darüber hatten wir in einer Montagssitzung gesprochen, dass wir das nicht machen.
