### ISSUE TITLE
Sonderzeichen in den Facetten

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#319]
Auf der englischen und französischen Oberfläche werden in den Facetten für DDC und IxTheo-Klassifikation manche Zeichen (Klammern?) nicht dargestellt:
https://ixtheo-test.de/Search/Results?lookfor=&type=AllFields&limit=20&sort=year

Vgl. #67

**Comment by IxTheoKm** [comment]
Offensichtlich besteht das Problem unabhängig von der Sprache: auf der deutschen Oberfläche ist auch bei den Verlagen das kaufmännische und "&" falsch angezeigt

**Comment by thefass** [comment]
Es handelt sich um HTML Tags wie &lt; &gt; etc.

**Comment by thefass** [comment]
hier nochmal mit leerraum dazwischen dargestellt, da es in GitHub sonst umgewandelt wird:
& g t ;

**Comment by oobenland** [comment]
Fixed -> siehe ptah.

**Comment by IxTheoKm** [comment]
Jetzt o.k. in ptah
