### ISSUE TITLE
Buchkapitel

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#32]
Warum ist dieser Datensatz eine Buchkapitel?
Welche Felder werden ausgelesen?
Beispiel: http://ptah.ub.uni-tuebingen.de/Record/42631512X

**Comment by ruschein** [comment]
Im Leader "01172naa a2200349 4500" steht an Position 7 (Es wird ab 0 gezählt.) ein kleines "a".  Im Standard (http://www.loc.gov/marc/bibliographic/bdleader.html) steht, dass ein kleines "a" für " 07 - Bibliographic level" die Bedeutung "Monographic component part" hat.  Das wurde dann in "Buchkapitel" übersetzt.

**Comment by thefass** [comment]
danke! das Problem ist allerdings komplexer. Ich eröffne ein neues Issue
