### ISSUE TITLE
seltsame Searchergebnisse

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#323]
die Suche nach "International yearbook for Tillich research" im Aspekt "Alle Felder" findet kein Ergebnis:
https://ixtheo-test.de/Search/Results?lookfor=International+yearbook+for+Tillich+research&type=AllFields&limit=20&sort=year

Das ist  seltsam, da die Zss vorhanden ist:
https://ixtheo-test.de/Search/Results?lookfor=id%3A357960254&type=AllFields&limit=20&sort=year

**Comment by socheres** [comment]
mit dem Suchbegriff(alle Felder) "Tolerant because Christianity itself
is a hybrid tradition" bekomme ich kein Trefferergebnis. Bei weniger
Zeichen bis "i", also "Tolerant because Christianity i" klappt die Suche.

**Comment by oobenland** [comment]
@socheres Der Fehler lag an einer falschen Behandlung von Stopwords. Wenn man "is a" aus der Suche nimmt, dann findet er auch die Ergebnisse. Das habe ich angepasst. Nun dauert es natürlich bis nächsten Mittwoch, bis die Änderung eingespielt ist und dann noch ein Tag, bis der Import durchgelaufen ist.

**Comment by oobenland** [comment]
@thefass Bei deiner Suche scheint es das selbe Problem zu sein. Wenn man das Wort 'for' aus der Suche nimmt bekommt man 64 Treffer. Der letzte Treffer ist der gesuchte.

Das ist bis jetzt wohl kaum aufgefallen, da nur wenige englische Stopwords gefiltert wurden.

**Comment by thefass** [comment]
das Problem ist nicht behoben.

**Comment by thefass** [comment]
das Problem ist auf ptah behoben, dort funktionieren die obigen Suchanfragen. Allerdings funktioniert das noch nicht auf ixtheo-test.de

**Comment by ruschein** [comment]
Sollte jetzt auch auf IxTheo-Test.de funktionieren.

**Comment by thefass** [comment]
funktioniert
