### ISSUE TITLE
Auswahl aus einer Trefferliste

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#324]
Ein Benutzerdesiderat aus dem Feedback:
Es sollte möglich sein, aus einer Trefferliste mehrere Treffer gleichzeitig oder die ganze Trefferliste auszuwählen.
Derzeit muss jeder Titel einzeln zu den Favoriten abgelegt werden.

**Comment by oobenland** [comment]
Ich sehe gerade nicht, dass VuFind das vorsieht. Daher wüssten wir das selbst implementieren.

**Comment by thefass** [comment]
Die Auswahl einzelner Titel oder aller Titel auf einer Seite geht im Villanova Katalog. 

Siehe
https://library.villanova.edu/Find/Search/Results?lookfor=religion&type=AllFields

dort sind Auswahlkästchen vor dem einzelnen Titel und für die Titel einer Seite " Select Page | with selected: Add to Book Bag" (unterhalb der Page-Funktion)

@oobenland : bitte nachfragen

**Comment by thefass** [comment]
weiteres Beispiel, wo man die Einzelnen Treffer in eine Merkliste übernehmen kann (müssen einzelnen angeklickt werden). Dann kann aber die gesamten Titel der Merkliste witerbearbeitet werden (z.b. zu den Favoriten übernehmen oder aber auch per mail verschicken):

https://katalog.tub.tuhh.de/Search/Results?lookfor=religion&submit=In+tub.find+suchen&localonly=1&mylang=de&shard%5B%5D=GBV+Central

**Comment by IxTheoKm** [comment]
Das Benutzerdesiderat hebt wohl eher auf die "Villanova-Möglichkeit" ab. Einzelne Treffer kann man derzeit auch schon in die Favoriten übernehmen und diese Liste dann weiter verarbeiten. Das ist ziemlich aufwändig.

**Comment by mtrojan-ub** [comment]
Aktuell auf ptah ist es möglich, im Suchergebnis mehrere Treffer oder alternativ die ganze Liste auszuwählen, und dann mittels "Speichern"-Knopf auf die Favoritenliste zu setzen.
(nur möglich wenn eingeloggt)

![grafik](https://user-images.githubusercontent.com/26873381/34484415-d09317dc-efc4-11e7-9ce7-2990691599a8.png)

![grafik](https://user-images.githubusercontent.com/26873381/34484464-0f001a24-efc5-11e7-99a2-68132646b29d.png)

Deckt das die Anforderung ab?

**Comment by IxTheoKm** [comment]
Ich denke ja.
Die ganze Liste kann aber wohl nur ausgewählt werden, wenn sie 100 Treffer nicht übersteigt, da bis zu 100 Treffern auf einer Seite angezeigt werden können.
@thefass Das ist aber wohl auch so vorgesehen, weil nicht unbegrenzt exportiert werden soll, oder?

**Comment by thefass** [comment]
ja, diese Einschränkung ist so gewollt.
Ansonsten ist die Anforderung abgedeckt
