### ISSUE TITLE
EndNote Importfilter

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#325]
Ein Benutzerdesiderat aus dem Feedback:

der Filter www.ub.rub.de/digibib/tutorial/Index%20Theologicus.enf der über die Seite www.ub.rub.de/informationen/endnote.html bereit gestellt wird, muss aktualisiert werden.

**Comment by ruschein** [comment]
Verstehe ich nicht.  Was haben diese externen Seiten mit uns zu tun?

**Comment by socheres** [comment]
der Importfilter [http://www.ub.rub.de/digibib/tutorial/Index%20Theologicus.enf](url) wurde im alten IxTheo als "Notlösung" benutzt, da wir im alten IxTheo keine Schnittstelle fürs Exportieren der Datensätze angeboten hatten (lediglich Downloaden der Datensätze in IxTheo-Format). Beim neuen IxTheo exisitiert zwar standardmäßig (Vufind) diese Exportfunktion, allerdings muss diese Filter angepasst werden, da es beim Exportieren der Datensätze in ein Literaturverwaltungsprogramm als RIS- od. BibTex-Format die bibliografischen Angaben nicht vollständig rüberkommen. Z.B. bei Aufsätzen fehlen Band- und Heftnummer

**Comment by socheres** [comment]
@ruschein an dieser Stelle[https://github.com/ubtue/ixTheo/blob/0534cd59f1190521f70b31ef62cf93f0a874e3d9/themes/root/templates/RecordDriver/AbstractBase/export-ris.phtml](url) muss das Marc-Mapping definiert werden.

**Comment by socheres** [comment]
@oobenland habe auf ptah getestet, aber das Exportergebnis wie bisher ohne Änderung.

**Comment by ruschein** [comment]
@socheres Welches Beispiel hast Du ausprobiert?

**Comment by socheres** [comment]
@ruschein 
jetzt wird alles richtig importiert. Noch eine kleine Bemerkung:
1. bitte Filter für Schlagwörter bzw. Abstrcts anpassen.
2. in folgendem Bsp. wird auch Geburtsjahr mit geladen. Hier bitte ohne Zahlen: https://ptah.ub.uni-tuebingen.de/Record/462661148

**Comment by socheres** [comment]
@ruschein kannst du auch andere Exportformate freischalten? https://github.com/socheres/ixTheo/pull/1

**Comment by thefass** [comment]
Momentan sind die drei Formate eingebunden: EndNote, BibTeX, RIS.

@socheres : welche Formate sollten noch eingebunden werden?

**Comment by mtrojan-ub** [comment]
@socheres: Was genau soll bei den Filtern bzw. Schlagwörtern für Abstracts angepasst werden?

**Comment by socheres** [comment]
@mtrojan-ub : abstract und keywords sind in den drei o.g. Exportformate nicht enthalten, daher kann der issue geschlossen werden. wünschenswert wäre csl Integration für vordefinierte zitierformen als erweiterte exportfunktion.
