### ISSUE TITLE
tooltip einbinden

### ISSUE THREAD

**Issue by socheres** [ubtue/ixTheo#328]
an der schwarz markierten Stelle bitte Tooltip-Funktion beim Drüberfahren oder beim Halten des Mausanzeigers folgende Meldung einblenden: 

**"Mehrfachauswahl mit Strg/⌘ od. Shift"** (mouseover1)

![mouseover1](https://cloud.githubusercontent.com/assets/1545743/18118665/9061fc22-6f56-11e6-8de3-e6efb5b3dd4e.PNG)

**"Ein-/Auswählen mit Shift"** (mouseover2)

![mouseover2](https://cloud.githubusercontent.com/assets/1545743/18120853/15a512f6-6f62-11e6-9898-e9713ffc7d25.PNG)

<div class="container">
  <h3>Tooltip Example</h3>
  <p>bitte unten testen</p>
  <ul class="list-inline">
        <li><a href="#" data-toggle="tooltip!" data-placement="right" title="Mehrfachauswahl mit Strg/⌘ od. Shift">AA Religionswissenschaft</a></li>
  </ul>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip!"]').tooltip();  
});`

![mouseover2](https://cloud.githubusercontent.com/assets/1545743/18118669/947a6db2-6f56-11e6-9e68-0213f30a9d19.PNG)

**Code-Bsp. Bootstrap.(mouseover)**

**Comment by socheres** [comment]
@oobenland macht man dies mit bootstrap? http://www.w3schools.com/bootstrap/bootstrap_tooltip.asp

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden

**Comment by mtrojan-ub** [comment]
@socheres : kann das geschlossen werden?

**Comment by socheres** [comment]
@mtrojan-ub :sieht gut aus. der tooltip-text muss eventuell noch angepasst werden. @IxTheoKm @thefass Idee?

**Comment by IxTheoKm** [comment]
Da das weitgehend übliche Bezeichnungen sind, habe ich keine Idee, die die Sache deutlicher macht.
Hier die Vorschläge:
Bei Thema browsen: "Hinzufügen/Entfernen mit Shift-Taste"
In den Auswahllisten: "Mehrfachauswahl mit Strg- oder Shift-Taste"

Für die englische Übersetzung muss ich passen.

**Comment by thefass** [comment]
Ist m.E so voll wie es ist gut verständlich.
