### ISSUE TITLE
Facetten Sprache

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#33]
Warum sind trotz deutscher Spracheinstellung hier englische Formate (book ...)?

Beispiel:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Augustinus%2C+aurelius&type=Author&limit=20&sort=title

**Comment by ruschein** [comment]
Da war ein Bug im Original-VuFind.  Habe ich behoben.

**Comment by thefass** [comment]
Nicht ganz gelöst:

hier ist es gelöst:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=&type=AllFields&limit=20&sort=title

Wenn ich nun aber auf die Facette "Buch" klicke, kommt wieder die englische Bezeichnung
http://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&sort=title&filter[]=format%3A%22Book%22

**Comment by ruschein** [comment]
Vielleicht ist es jetzt ganz gelöst.  Es kann aber immer noch irgendwo Probleme geben...

**Comment by thefass** [comment]
doch noch nicht gelöst.
Es kommt immer noch die englische Bezeichnung, wenn man die Suche mittels der Facetten einschränkt

**Comment by ruschein** [comment]
Mir ist nicht klar wo.  Aber ich habe noch eine Stelle gefunden und das Problem dort behoben.  Hoffentlich war das jetzt die letzte Stelle.  Falls ja, bitte den Bug zumachen.  Falls nein, bitte beanstanden.  Danke!

**Comment by Mannsperger** [comment]
Wenn ich bei einer Suche auf "Buch" klicke
![bild 1 - sprache auswahl](https://cloud.githubusercontent.com/assets/16759964/12552483/555962d6-c372-11e5-8353-71378c5534fe.png)
dann steht plötzlich bei Format:book
![bild 2 - sprache markiert](https://cloud.githubusercontent.com/assets/16759964/12552493/6ddb5634-c372-11e5-8280-81a2fa185a39.png)

**Comment by Mannsperger** [comment]
Und die unter "Signatur" aufgeführten Auswahlmöglichkeiten sind englisch:
![signatur](https://cloud.githubusercontent.com/assets/16759964/12552585/f07e35ca-c372-11e5-9a35-b9f43ab01b6d.png)

**Comment by ruschein** [comment]
On 25/01/16 14:50, Mannsperger wrote:
>
> Und die unter "Signatur" aufgeführten Auswahlmöglichkeiten sind englisch:
>
Habe ich jetzt korrigiert.
>
> signatur
> <https://cloud.githubusercontent.com/assets/16759964/12552585/f07e35ca-c372-11e5-9a35-b9f43ab01b6d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/33#issuecomment-174514440>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by ruschein** [comment]
Behoben.

On 25/01/16 14:47, Mannsperger wrote:
>
> Wenn ich bei einer Suche auf "Buch" klicke
> bild 1 - sprache auswahl
> <https://cloud.githubusercontent.com/assets/16759964/12552483/555962d6-c372-11e5-8353-71378c5534fe.png>
> dann steht plötzlich bei Format:book
> bild 2 - sprache markiert
> <https://cloud.githubusercontent.com/assets/16759964/12552493/6ddb5634-c372-11e5-8280-81a2fa185a39.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/33#issuecomment-174513752>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de
