### ISSUE TITLE
Subito: falsche Übergabe von Metadaten

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#357]
Bei der Übergabe von Metadaten aus dem IxTheo an Subito wird auch bei Büchern immer eine Zeitschriftensuche ausgelöst. Wegen dieser falschen Übergabe ist das Ergebnis immer negativ: "Es wurden leider keine Ergebnisse zu Ihrer PreOrder-Anfrage gefunden werden"
[Subito_Zss.pdf](https://github.com/ubtue/ixTheo/files/535509/Subito_Zss.pdf)

Der Nutzer muss nun wissen, dass er manuell in subito eine neue Buchsuche auslösen muss. Das ist natürlich schwierig zu wissen, da er davor ja mitgeteilt bekam, dass nichts gefunden wurde.

Deswegen wäre es wichtig, dass bei der Übergabe der Metadaten eines Buches (mit Hilfe der ISBN?) direkt die richtige Suche in Subito ausgelöst wird:
https://www.subito-doc.de/search/books

**Comment by ruschein** [comment]
Ein Beispiel, bitte.

**Comment by thefass** [comment]
@ruschein : hast Du dieses Problem schon gelöst?
Jetzt funktioniert die Übergabe der ISBN:
Beispiel: https://ixtheo.de/Record/477912001
Beispiel hat die ISBN: 9789004322394
Subito:
![subito](https://user-images.githubusercontent.com/14169098/28087288-373b2d70-6682-11e7-967a-afe54f3a3cf3.jpg)

**Comment by ruschein** [comment]
@thefass Mir ist nicht bewusst, dass wir da etwas getan haben.  Trotzdem, kann man das jetzt zumachen?

**Comment by ruschein** [comment]
@thefass Bitte kontrollieren und das Issue zumachen falls es jetzt funktioniert.  Danke.

**Comment by thefass** [comment]
funktioniert
