### ISSUE TITLE
Header :: an Position 07: a

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#36]
# Problem

In Position 07 steht das a für:
"Monographic component part
Monographic bibliographic unit that is physically attached to or contained in another unit such that the retrieval of the component part is dependent on the identification and location of the host item or container. Contains fields that describe the component part and data that identify the host, field 773 (Host Item Entry).
Examples of monographic component parts with corresponding host items include an **article in a single issue of a periodical**, a chapter in a book, a band on a phonodisc, and a map on a single sheet that contains several maps."
Quelle: http://www.loc.gov/marc/bibliographic/bdleader.html

Hier stecken also alle Aufsätze und Rezensionen. Dadurch erklärt sich die hohe Zahl an "Buchkapitel".

Wir müssen das Trennen.

Ich schätze mal, dass diese Kategorie sich quantitativ so aufteilt (spätestens nach dem Einspielen der ca. 550.000 Aufsätze aus dem jetzigen IxTheo):
1. Aufsätze aus Zeitschriften
2. Rezensionen
3. echte Buchkapitel (dürften verschwindend klein sein, da Kapitel in der Regel nicht katalogisiert werden) 

**Wie können wir das Problem lösen?**
### Aufsatz als Standard

Ein Ansatz könnte sein, standardmäßig die größte Gruppe als Namen zu verwenden: Position 07 a würde dann nicht mehr Buchkapitel, sondern "Aufsatz" (article) heißen.
Die anderen Kategorien müßten dann entsprechend gefiltert werden:
### Rezensionen

Filterkriterien: Position 07a und 935 $c "uwre"
Beispiel: http://ptah.ub.uni-tuebingen.de/Record/375940510
NB: uwre steht für **U**nselbständiges **W**erk **Re**zension
## Lösungsansatz 2

Wir versuchen alle Kategorien über die Zuordnung zur übergeordneten Einheit zu filtern
### Aufsätze aus Zeitschriften

Filterkriterien: Position 07 a UND NOT 935 $c uwre UND 773 $w [PPN > Header Position 07 s]
Beispiel: http://ptah.ub.uni-tuebingen.de/Record/423961349
### Aufsätze aus Monographien

Filterkriterien: Position 07 a UND NOT 935 $c uwre UND 773 $w [PPN > Header Position 07 m]
Beispiel: http://ptah.ub.uni-tuebingen.de/Record/373823495
### Rezensionen

Filterkriterien: Position 07a und 935 $c "uwre"
Beispiel: http://ptah.ub.uni-tuebingen.de/Record/375940510
### Rest

was aus Position 07 a übrigbleibt wird "Rest" benannt (nur zum Testen) und kann dann analysiert werden.

Aus Analytischen Gründen tendiere ich zu Ansatz 2. Wenn herauskommen sollte, dass es keinen Rest "echte Buchkapitel" gibt, könnte man Ansatz 1 umsetzen, der mir von der Syntax einfacher erscheint

Was denkt Ihr?

**Comment by ruschein** [comment]
Ich habe heute ein C++ Programm geschrieben um dieses Problem zu analysieren.  Wenn ich die beiden Lösungsansätze vergleiche, finde ich beim Lösungsansatz 1 werden 530 Datensätze eventuell falsch klassifiziert.  Hier sind ein paar Dutzend der PPNs die eventuell falsch als Artikel klassifiziert wurden:

062621408
062776991
063088797
06689056X
067721346
070285527
062621408
062776991
063088797
06689056X
067721346
070285527
072824263
072923334
073027162
073544760
07426799X
074654233
074654810
074775723
07516549X
07525803X
076188140
085895423
085917877
086052462
087463571
087540010
087814781
087818337
088361055
088399923
088400018
088400107
088400190
088400301
088400360
088400506
08846816X
088485846
088485943
088873668
091134633
091286557
093463251
093955170
096261099
09814944X
098374737
098706845
099442159
099575108
099575205
099575256
099575310
072824263
072923334
073027162
073544760
07426799X
074654233
074654810
074775723
07516549X
07525803X
076188140
085895423
085917877
086052462
087463571
087540010
087814781
087818337
088361055
088399923
088400018
088400107
088400190
088400301
088400360
088400506
08846816X
088485846
088485943
088873668
091134633
091286557
093463251
093955170
096261099
09814944X
098374737
098706845
099442159
099575108
099575205
099575256
099575310

**Comment by ruschein** [comment]
Was vielleicht noch von Interesse ist:  Mein Programm fand 130683 die ein "a" in Position 07 im Leader hatten.  Davon waren 62719 als Rezensionen gekennzeichnet.  Die 530, eventuell falsch klassifizierten Datensätze, sind also also ca. 0,4%.

**Comment by thefass** [comment]
Johannes, Danke für die Analyse
Hast du Lösungsansatz 2 ausprobiert?
Wenn ja, wieviele Sätze gibt es in den 4 Gruppen. Kannst Du pro gruppe eine Anzahl an Beispielen liefern?
Und sind die 530 aus der Gruppe Rest?

**Comment by thefass** [comment]
Johannes, Dein Programm findet 130683 Sätze mit a in Position o7 im Leader-
In ptah werden bei einer Suche nach alles 130,681 "Buchkapitel" angezeigt.

Unterschied sind nur 2 Sätze. Woran kann das liegen und deutet das auf ein Problem?

**Comment by ruschein** [comment]
On 09/09/15 21:16, thefass wrote:
>
> Johannes, Danke für die Analyse
> Hast du Lösungsansatz 2 ausprobiert?
>

Ich habe ja beides verglichen.  Die 530 würden eben beim 1.
Lösungsansatz als Artikel klassifiziert alles andere würde gleich
klassifiziert.

> Wenn ja, wieviele Sätze gibt es in den 4 Gruppen. Kannst Du pro gruppe
> eine Anzahl an Beispielen liefern?
>

Vermutlich heute noch.

> Und sind die 530 aus der Gruppe Rest?
>

Ja.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/36#issuecomment-139018878>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by ruschein** [comment]
On 09/09/15 21:26, thefass wrote:
>
> Johannes, Dein Programm findet 130683 Sätze mit a in Position o7 im
> Leader-
> In ptah werden bei einer Suche nach alles 130,681 "Buchkapitel" angezeigt.
>
> Unterschied sind nur 2 Sätze. Woran kann das liegen und deutet das auf
> ein Problem?
>

Keine Ahnung.  Leider nicht mal ein Verdacht.  Vielleicht gab es
Importprobleme.  Wenn es ein Problem beim Import von einem Datensatz
gibt macht das Importskript einfach weiter mit dem Nächsten.  Finde ich
nicht gut.  Überhaupt scheint es die Philosophie bei der
Softwareentwickung von Demian Katz gewesen zu sein.  Meine ist es bei
einem Problem sofort mit einer möglichst nützlichen Fehlermeldung
abzubrechen damit ein Problem auf keinen Fall übersehen werden kann.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/36#issuecomment-139021437>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by ruschein** [comment]
Ist vermutlich behoben.  Siehe meine Email an den IxTheo2-Verteiler.

**Comment by thefass** [comment]
@ruschein Die von Dir vermuteten evt. falsch als Artikel klassifizierten 530 Titel sind Artikel.
Es spricht also nichts dagegen -wie auch am Montag besprochen- Lösungsansatz 1 umzusetzen. (mit der Ausfilterung der Rezensionen in eine eigene Facette).

**Comment by thefass** [comment]
**Aufsatz und Rezensionen werden jetzt unterschieden.**

**Allerdings**: wenn ich die Facette Rezension auswähle, verschwindet die Facette "Elektronisch".
Es git jedoch tausende Rezensionen, die elektronisch vorhanden sind.
Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=journal_issue:094449406
ab Treffer 10 ist zwar der Link auf "kostenfrei" vorhanden, jedoch nicht die Kennzeichnung als Facette "Elektronisch"
Vergleich Treffer 1, in dem der Link auf "kostenfrei" x und die Kennzeichnung als Facette "Elektronisch" vorhanden ist.

**Comment by thefass** [comment]
@jriedl :: welche Felder werden als "Elektronisch" ausgewertet?

**Comment by jriedl** [comment]
Ja, vielleicht habe ich das heute morgen nicht klar genug betont: Die Einstufung als Rezension entfernt derzeit alle weiteren Formatlabels, also insbesondere auch die Einstufung als "Elektronisch". Sobald  die Unterscheidung "Elektronisch" / "Nicht Elektronisch"  aus der Facette "Medientyp" herausgelöst und in eine eigene  Facette (z.B. "Medienart") gewandert ist, lässt sich gezielt nach elektronischen Rezensionen suchen.
________________________________

**Comment by thefass** [comment]
@jriedl :: ok, dann gehen wir das nach Johannes Ru Rückkehr im Gesamten an

**Comment by ruschein** [comment]
Was ist hier der jetzige Stand?  Ich vermute, es tut so wie es soll.  Falls nicht bitte nochmals, mit PPN-Beispiel rückmelden.

**Comment by ruschein** [comment]
@thefass Martin, kannst Du dieses Issue bitte nochmal anschauen und, falls alles stimmt zumachen?

**Comment by thefass** [comment]
Ist ok.
