### ISSUE TITLE
Boolscher Operator NOT 

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#37]
die Suche im Feld Schlagwort nach "Festschrift" ergibt 2650 Treffer:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Festschrift+&type=Subject&limit=20&sort=relevance

die Suche im Feld Schlagwort nach "Festschrift NOT Rezension" ergibt 9018 Treffer:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Festschrift+NOT+Rezension&type=Subject&limit=20&sort=relevance

Wie kann das sein? Ich habe erwartet, dass die erste Treffermenge eingeschränkt und nicht erweitert wird.

**Comment by oobenland** [comment]
Das ist interessant. Die Einstellung für diese Art von Operationen ist aktiviert. Das müsste man mal näher prüfen.

Aber vielleicht ist das hier eine Alternative:
Das Vorstellen von `-` wird als NOT gewertet: "Festschrift -Rezension" (1.493 Treffer)

**Comment by thefass** [comment]
die Suche im Feld Schlagwort nach "Festschrift" ergibt nun 489 Treffer:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Festschrift%22&type=Subject&limit=20&sort=relevance
Haben wir nun einen andere Datenmenge?

Das Problem mit NOT besteht noch. Jetzt ergeben sich 8876 Treffer:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Festschrift%22+NOT+%22Rezension%22&type=Subject&limit=20&sort=relevance

Ollis Vorschlag mit dem - reduziert tatsächlich auf 460 Treffer:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22Festschrift%22++-%22Rezension%22&type=Subject&limit=20&sort=relevance

Ich dachte aber dass NOT dasselbe tut wie das -
Wenn das so ist, dann muss auch die Ergebnismenge gleich sein

**Comment by thefass** [comment]
**funktioniert!**

Ausprobiert an der Schlagwortsuche 
Dogmatik  >>>Treffer: 6171
Dogmatik AND Apologetik >>> Treffer: 8
Dogmatik NOT Apologetik >>> Treffer: 6163
Dogmatik  -Apologetik >>> Treffer: 6163
