### ISSUE TITLE
Titelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#38]
Am Ende eines Titels wird immer der / angezeigt:
http://ptah.ub.uni-tuebingen.de/Record/042023637
Sowphl beim Haupttreffer als auch in der Spalte "Ähnliche Einträge" 

Der schrägstrich steckt auch im Internformat. Entweder in 245 $a wenn es nur einen Hauptitel gibt oder in 245 $b wenn es noch eine Zusatztitel gibt
http://ptah.ub.uni-tuebingen.de/Record/373823495

Könnt Ihr das bitte unterdrücken?

Die Trennung zwischen Hauptitel und Zusatz zum Titel durch einen Doppelpunkt finde ich hingegen gut

**Comment by oobenland** [comment]
Könnte man das in der Marc-Pipeline machen? Sonst müsste man ein neues BeanShell-Skript für den Titel anlegen.

**Comment by ruschein** [comment]
Arbeite gerade an dem Problem.

**Comment by thefass** [comment]
Erledigt. Danke. Closed
