### ISSUE TITLE
Konto-Änderungen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#386]
Ich finde keine Möglichkeit, in den persönlichen Kontodaten die E-Mail-Adresse (oder ggf. den Benutzernamen) zu ändern. Übersehe ich das irgendwo?
Ich könnte ein neues Konto für einen neuen Benutzernamen anlegen, aber wenn sich nur die E-Mail-Adresse ändert, sollte dies auch durch die Änderung der persönlichen Angaben möglich sein. Dort kann man aber nur Titel, Name, Institution, Land und Sprache ändern.

Nach dem Logout kommt die Rückmeldung 
"Login"
"Bitte loggen Sie sich zuerst ein"
Das finde ich etwas irritierend

**Comment by oobenland** [comment]
Da #408 umgesetzt wurde ist auch dieses Issue fertig, oder?

**Comment by IxTheoKm** [comment]
Die Möglichkeit der E-Mail-Änderung ist erledigt.

Die Frage bzgl. Rückmeldung nach dem Logout aus den persönlichen Kontodaten ist noch offen:
Wenn nach dem Logout rot hervorgehoben die Meldung kommt "Bitte loggen Sie sich _zuerst_ ein", finde ich das irgendwie widersinnig (selbst wenn darüber "Login" steht).

Ohne das Wort "zuerst" wäre es m.E. weniger irritierend. "Bitte loggen Sie sich ein" würde bei jeder Aktion passen. Aber vielleicht sehe auch nur ich das so.

**Comment by IxTheoKm** [comment]
O.K. Jetzt kommt keine Meldung mehr.
