### ISSUE TITLE
Sortierungsproblem 2

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#387]
https://ixtheo-test.de/Record/455121044
Dieser Aufsatz hat in 936j 2015

Wenn ich die zeitliche Facette 2015-2015 eingestellt habe und dann nach dem Titel des Aufsatzes suche, bekomme ich kein Ergebnis. Ebenso nicht, wenn 2015- eingestellt ist.
Das verstehe ich nicht. 

Anders jedoch bei diesem Aufsatz:
https://ixtheo-test.de/Record/445012374#details
Dieser Aufsatz hatebenfalls in 936j 2015

Wenn ich die zeitliche Facette 2015-2015 eingestellt habe und dann nach dem Titel des Aufsatzes suche, bekomme ich das korrekte Ergebnis.

Was ist der Unterschied in den beiden Datensätzen?
der erst hat im Leader caa, der zweite naa. Kann das der Grund sein?

beim ersten fehlt auch die 260, beim zweiten steht 2015 auch in der 260. Kann das der Grund sein?

**Comment by IxTheoKm** [comment]
https://ixtheo-test.de/Record/009813497#details
Diese Gesamtaufnahme eines mehrbändigen Werks hat keine 936j.
Statt dessen: 
008 850101n**19uu**uuuuxx 00 0 ger c
260 $aGütersloh :$bMohn [u.a.],$c**19XX**

Bei mehrbändigen Werken wurde früher "XX" erfasst, wenn die Bände in verschiedenen Jahren erschienen sind, aber nur dieser wird sehr weit oben unter den neuesten Titeln angezeigt

**Comment by jriedl** [comment]
Ausgangsproblem scheint seit Einführung der angepassten Sortierstrategie mit Verknüpfung zum jüngsten untergeordneten Werk nicht mehr gegeben zu sein.
