### ISSUE TITLE
Sortierungsproblem 3 oder Zählproblem?

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#388]
Wenn man auf 2016-2016 einschränkt, dann bekommt man nur 3.615 Treffer.

In der WinIBW sind aber für das Jahr 2016 10.168 Treffer zu finden (f ejh 2016 (cod mteo OR sgb1 OR sgb0))

Ist das ein Sortierproblem, ein Zählproblem?

Was wird ausgewertet, wenn man die zeitliche Facette benutzt?

**Comment by jriedl** [comment]
Mittlerweile werden (auf ptah sichtbar) für die Zeit-Facetten und die Listensortierung die gleichen Felder ausgewertet. Damit erhöht sich die Anzahl der Ergebnisse auf knapp 8800. Für die verbleibende Differenz wären Beispiele von fehlenden PPNs sehr hilfreich.

**Comment by IxTheoKm** [comment]
Könnten das die digitalisierten Titel sein, deren Originalerscheinungsjahr in 1100=260c steht und deren Digitalisierungsjahr 2016 ist? Das wird in der WinIBW auch mit ejh gefunden.

Bsp. 46930037X, 469068078, 468890254 ...

Die sind in der Ergebnismenge 2016 nicht enthalten (und sollen es wohl auch nicht).

**Comment by ruschein** [comment]
Da es eine Erklärung für die Diskrepanz gibt, mache ich das Issue zu.
