### ISSUE TITLE
Überspringen von Titeldaten beim Weiterblättern

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#397]
Beim Test der Sortierung aufgefallen (#387):

Beim Weiterblättern in einer Titelmenge über den Schalter "Nächster" aus der Vollanzeige werden - nach anfänglich korrekter Anzeige der Treffer - viele Titel übersprungen. Die Nummer des anzeigten Treffers stimmt dann auch nicht mehr überein mit der Nummer des Treffers, den man über das Weiterblättern am unteren Rand der Kurzanzeigeliste erhält.

**Comment by jriedl** [comment]
Fix auf ptah eingespielt.

**Comment by IxTheoKm** [comment]
In Stichproben geprüft. Jetzt O.K.
