### ISSUE TITLE
Sortierungsproblem 3

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#398]
Eine nach Titeln sortierte Treffermenge https://ixtheo-test.de/Search/Results?type=AllFields&sort=title&filter[]=publishDate%3A%22[2016+TO+2016]%22&filter[]=format%3A%22Article%22 enthält zwischendurch immer wieder "Ausreißer". Im Folgenden Treffer 81, 108, 191 ...
![sortierung1](https://cloud.githubusercontent.com/assets/17004223/21258151/fab9ee94-c37b-11e6-9178-20fdaa3799f2.png)
![sortierung2](https://cloud.githubusercontent.com/assets/17004223/21258154/ff3d0762-c37b-11e6-886d-836076be6932.png)
![sortierung3](https://cloud.githubusercontent.com/assets/17004223/21258158/02ee7be8-c37c-11e6-9809-56e9887a51f1.png)

**Comment by mtrojan-ub** [comment]
Ist das aktuell immer noch so?

Es sind viele neue Datensätze dabei. Führt man die o.g. Suche erneut aus lässt es sich aber nicht mehr reproduzieren.

Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&sort=title&page=26&filter[]=publishDate%3A%22[2016+TO+2016]%22&filter[]=format%3A%22Article%22
107 Die ägyptische Rezension des Josua LXX im Lichte der sahidischen Überlieferung => jetzt 510
**108 "Der fähige Mensch" und das  "Mehr als Mögliche" => taucht nicht mehr auf, dafür 3 andere die jedoch passen**
109 Akademische Debatte trifft Praxis => jetzt 514

![grafik](https://user-images.githubusercontent.com/26873381/34569994-c846b708-f16a-11e7-9507-0ddebc35cafc.png)

bitte nochmal testen

**Comment by IxTheoKm** [comment]
Scheint nicht mehr aufzutauchen. 
Die anderen Sortierungsprobleme (auch in dieser Trefferliste) siehe
https://github.com/ubtue/tuefind/issues/167
https://github.com/ubtue/ixTheo/issues/434
