### ISSUE TITLE
Unterschiedliche Ergebnisse in der einfachen und der erweiterten Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#399]
Ich bekomme für dieselbe Suchanfrage mittels Boolscher Operatoren in der einfachen Suche und mittels kombinierter Suchfelder/Suchgruppen in der erweiterten Suche unterschiedliche Trefferzahlen:

**Einfache Suche: 221 Treffer**
(Religi* OR Spiritu* OR Mysti* OR Meditation* OR God* OR Gott*) AND (Suicid* OR Suizid* OR Selbstmord*)

https://ixtheo-test.de/Search/Results?lookfor=%28Religi*+OR+Spiritu*+OR+Mysti*+OR+Meditation*+OR+God*+OR+Gott*%29+AND+%28Suicid*+OR+Suizid*+OR+Selbstmord*%29&type=AllFields&limit=20&sort=title

**Erweiterte Suche: 454 Treffer**
"(Alle Felder:religi* ODER Alle Felder:spiritu* ODER Alle Felder:mysti* ODER Alle Felder:meditation* ODER Alle Felder:god* ODER Alle Felder:gott*) UND (Alle Felder:suicid* ODER Alle Felder:suizid* ODER Alle Felder:selbstmord*)"

https://ixtheo-test.de/Search/Results?sort=title&join=AND&lookfor0[]=religi*&type0[]=AllFields&lookfor0[]=spiritu*&type0[]=AllFields&lookfor0[]=mysti*&type0[]=AllFields&lookfor0[]=meditation*&type0[]=AllFields&lookfor0[]=god*&type0[]=AllFields&lookfor0[]=gott*&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&bool0[]=OR&lookfor1[]=suicid*&type1[]=AllFields&lookfor1[]=suizid*&type1[]=AllFields&lookfor1[]=selbstmord*&type1[]=AllFields&bool1[]=OR&daterange[]=publishDate&publishDatefrom=&publishDateto=&limit=20

**Comment by jriedl** [comment]
Der Unterschied ergibt sich, da die beiden Anfragen nicht identisch sind:
Im ersten Fall wird auf  für jedes Feld in der Liste aller Felder überprüft, ob sowohl die vorderen als auch die hinteren Oder-Bedingungen erfüllt sind.
Im zweiten Fall werden die überprüft, ob eines der Felder die vorderen Bedingungen erfüllt und zusätzlich noch eines der Felder die anderen - die Suche ist also feldübergreifend.
Das erkennt man, wenn man sich die explizit an Solr gesendeten Suchanfragen ansieht
[simple_query.txt](https://github.com/ubtue/ixTheo/files/694020/simple_query.txt)
[advanced_query.txt](https://github.com/ubtue/ixTheo/files/694021/advanced_query.txt)
