### ISSUE TITLE
Umlautindexierung

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#400]
Die Recherche und Indexierung der Umlaute in Titeln deutscher Sprache führt zum Auseinanderdriften von älteren und neuen Titeln.
Indexiert wird offensichtlich unter 
_ä = a_
_ö = o_
_ü = u_

Ältere Titel liegen aber auch häufig in der Form
_ae_
_oe_ 
_ue_
vor, was der im Deutschen üblichen Sortierung entspricht.

Umlaute sollten daher zusätzlich mit der aufgelösten Form indexiert und auch darunter soertiert werden.

Bsp.: 
https://ixtheo-test.de/Alphabrowse/Home?source=title&from=g%C3%B6ttlich
https://ixtheo-test.de/Alphabrowse/Home?source=title&from=goettl

**Comment by oobenland** [comment]
@IT-Abteilung:
Eine MappingCharFilterFactory sollte helfen. Siehe http://lucene.472066.n3.nabble.com/How-to-search-for-special-chars-like-a-from-ae-td2444921.html

**Comment by mtrojan-ub** [comment]
Das sollte ja eigentlich bereits so sein... für die Textfelder wie titel usw. ist Stemming im Einsatz. Genauere Infos dazu gibts z.B. hier: https://github.com/ubtue/tuefind/issues/82

Eine Auflösung von z.B. ä nach ae usw. ist also bereits im Einsatz.

Falls es aktuell Probleme gibt, dann bitte nochmal mit konkreten Beispielen in TueFind einen neuen Issue öffnen.
