### ISSUE TITLE
Persönliche Angaben ändern

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#408]
In den Persönlichen Angaben im eigenen Konto soll es ermöglicht werden, die E-mail Adresse zu ändern

**Comment by IxTheoKm** [comment]
Siehe Issue #386

**Comment by oobenland** [comment]
Ist inzwischen umgesetzt: https://ixtheo-test.de/MyResearch/Profile

**Comment by IxTheoKm** [comment]
Funktioniert
