### ISSUE TITLE
Login via Shibboleth

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#423]
Ein Login kann auch über Shibboleth realisiert werden:

Shibboleth-Konfiguration in VuFind (config.ini):

[Authentication]
method = Shibboleth

; Whether or not to hide the Login Options
hideLogin = 0

[Shibboleth]
username = REDIRECT_eppn
login = https://<domainname>/Shibboleth.sso/Login
cat_username = REDIRECT_eppn 

Wir sollten das einmal in der Testversion ausprobieren und Vor- und Nachteile abwägen.

Erhalten bleiben muss auf jeden Fall auch ein direkter Login durch Anlegen eines Nutzerkontos. Wenn ich das richtig interpretiere, kann das aber mit hideLogin = 1 eingestellt werden?

**Comment by obrandt** [comment]
Hallo Martin,

ein Shibboleth-Login ist mit dem SSL- Zertifikat und der jetzigen 
Serverstruktur nicht machbar. Von daher gibt es keine wirtschaftliche 
Möglichkeit für Shibboleth-Logins.

Viele Grüße

Olaf

Am 01.03.2017 um 09:43 schrieb thefass:
