### ISSUE TITLE
Verknüpfungen zwischen Webseiten und untergeordneten Sätzen werden nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#424]
https://ixtheo-test.de/Record/469083549

Bei den untergeordneten Sätzen PPN 470970367, 47404680X, 474054233, 476391695, 477086969, 480312621 fehlt die Verknüpfung zum übergeordneten Satz PPN 469083549.
Beim übergeordneten Satz PPN 469083549 wird keine Verknüpfung zu den untergeordneten angezeigt.

**Comment by ruschein** [comment]
Auf Ptah eingespielt.

**Comment by IxTheoKm** [comment]
Auf prah jetzt o.k.

**Comment by IxTheoKm** [comment]
Im IxTheo auch o.k.
