### ISSUE TITLE
Persistent Identifier

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#425]
Problemanzeige:
Elektronische vorhandene Aufsätze haben heutzutage meist einen persistent identifier. Diese werden sowohl in der elektronischen als auch in der print-Version abgedruckt.
Es gibt im Prinzip zwei Arten: DOI und URN (Doi sind mittlerweile weiter verbreitet)
Die persistent identifier sind quasi die ISBN der Aufsätze. Damit können sie eindeutig identifiziert werden. Insofern ist das abdrucken in der e- als auch in der print-Ausgabe sehr sinnvoll.

Wir sollten diese identifier nicht nur als link auflösen (was wir momentan machen), sondern die DOI oder die URN unter dem Reiter Beschreibung" anzeigen. Dort werden bei Büchern auch die ISBN untergebracht.
Beispiel: https://ixtheo-test.de/Record/267626533

**Comment by thefass** [comment]
Wo stehen die Infos?

DOI >>> Marc 024 $a (PICA 2051)

DOI in Druckwerken >>> Marc 024 $a (PICA 2053)

**Comment by mtrojan-ub** [comment]
PPN wird nicht mehr gefunden, andere Beispiel PPN mit 024a: 007759371

**Comment by IxTheoKm** [comment]
Da die o.g. Beispiele 007759371, 000649074, 462959929, [267626533: mtex=gelöscht] keine Aufsätze sind zusätzlich geprüft an den Aufsätzen: 
https://ptah.ub.uni-tuebingen.de/Record/488387124
https://ptah.ub.uni-tuebingen.de/Record/453166083
https://ptah.ub.uni-tuebingen.de/Record/488329698

Anzeige ist überall o.k.
