### ISSUE TITLE
Falsche Anzeige von Titelstichwörtern als "Nebentitel"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#432]
Einzelne Titelstichwörter werden bei Bedarf in einem bestimmten Feld recherchierbar gemacht, stellen aber keinen vollständigen Sachtitel dar. Diese sollen nicht als Nebentitel angezeigt werden.

Bsp.:
https://ixtheo-test.de/Record/455093008#details
![nebentitel](https://cloud.githubusercontent.com/assets/17004223/24043747/69c6c972-0b18-11e7-89f1-785b0fec619f.png)

246 	**3** 	**0** 	|a Festschrift sechzigsten

Die Felder 246 mit erstem Indikator 3 und zusätzlich mit zweitem Indikator **0** sollen nicht angezeigt werden!

Beispiele für Nebentitel, die angezeigt werden sollen:
https://ixtheo-test.de/Record/48370928X
246 	**3** 		|a Gefühlt ist alles?

https://ixtheo-test.de/Record/485115298
246 	**1** 		|i Rubrikentitel  |a Walker Percy: pathologist, philosopher, and novelist

**Comment by mtrojan-ub** [comment]
Hinweis: Ist keine reine Sache des Frontends, sondern muss ggf. in der Solr Suchabfrage angepasst werden

`other_titles = custom(de.unituebingen.ub.ubtools.solrmarcMixin.TuelibMixin), getOtherTitles`

weiter an ruschein

**Comment by IxTheoKm** [comment]
Anzeige ist jetzt o.k.
