### ISSUE TITLE
Journal Online Print JOP Anzeige-Fehler

### ISSUE THREAD

**Issue by socheres** [ubtue/ixTheo#435]
Beim Aufrufen der Volltitelanzeige taucht der Icon der JOP
kurz auf (Ampelfarbe), aber er verschwindet dann wieder. Dann steht anstelle der Icon-Anzeige nur noch in Textform "Verfügbarkeit prüfen". Z.B.: https://ixtheo-test.de/Record/470666455

**Comment by mtrojan-ub** [comment]
Hinweis: Tritt laut ersten Tests nur dann auf, wenn vom Dienst bei Electronic oder Print das Result 4 (nicht lizensiert/nicht vorhanden) oder 10 (Unbekannt, z.B. bei unbekannter ISSD) zurück kommt.

siehe auch http://www.zeitschriftendatenbank.de/fileadmin/user_upload/ZDB/pdf/services/JOP_Dokumentation_XML-Dienst.pdf

**Comment by mtrojan-ub** [comment]
https://ptah.ub.uni-tuebingen.de/Record/470666455

**Comment by socheres** [comment]
stichprobenartig getestet und es werden überall jop-icons angezeigt.

**Comment by thefass** [comment]
erledigt
