### ISSUE TITLE
Sortierung von Reproduktionen nach Erscheinungsjahr

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#438]
Wenn Reproduktionen (Digitalisierungen, Nachdrucke) das Erscheinungsjahr der Originalausgabe in Feld **534 $c** enthalten, muss dieses in die Facette einfließen und nach diesem sortiert werden.

Bsp.:
https://ixtheo-test.de/Search/Results?lookfor=predigten+handschriften&type=Title
Treffer 1 (Reproduktion): https://ixtheo-test.de/Record/470890150#details
Treffer 20 (Original): https://ixtheo-test.de/Record/027202941#details

https://ixtheo-test.de/Record/309939410#details

**Comment by mtrojan-ub** [comment]
Aktuelle Änderung hat Seiteneffekte, siehe #496

**Comment by IxTheoKm** [comment]
Wird jetzt korrekt sortiert
