### ISSUE TITLE
Sonderdrucke von Aufsätzen in der Facette Medienart "Buch"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#449]
Im SWB werden Sonderdrucke von Aufsätzen mit dem Satztyp für eine Monographie erfasst. 
Sie bekommen das Abrufzeichen "sodr" (Marc 935 $c**sodr**).
Bsp.:
https://ixtheo-test.de/Record/084854200#details

Sie sollten in die Facette Medienart "**Aufsatz**" einfließen.

Problem 1: es gibt einige - allerdings sehr wenige - Sonderdrucke von Monographien.
Bsp.:
https://ixtheo-test.de/Record/46816653X#details
https://ixtheo-test.de/Record/057589259#details
https://ixtheo-test.de/Record/05830956X#details

Die würden dann auch bei den Aufsätzen landen, das halte ich aber für unproblematisch. Derzeit gibt es ca. 5770 Sonderdrucke, die für den IxTheo ausgezeichnet sind.

Problem 2: es gibt Beiträge, die wie Sonderdrucke erfasst werden, in denen aber 1140 "sodr" nicht erfasst ist. Die lassen sich nicht herausfischen.
Bsp.: 
https://ixtheo-test.de/Record/478108745#details

**Comment by IxTheoKm** [comment]
Scheinbar funktioniert es nicht in Fällen, in denen in 935 $c weitere Begriffe vorkommen, z.B. in RDA-Aufnahmen 935 $ctext$csodr

https://ixtheo-test.de/Record/488592119#details

**Comment by mtrojan-ub** [comment]
Ist das nicht bereits gefixt? Die Änderung hierzu erfolgte schon Ende Mai

**Comment by IxTheoKm** [comment]
Jetzt o.k.
