### ISSUE TITLE
Fehlende Autoren im Titelsatz

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#455]
https://www.ixtheo.de/Record/481144900

es fehlt der Autor in der Anzeige des Titelsatzes. obwohl er in 100 vorhanden ist.
Wird das Feld evt. in Abhängigkeit zu $4 aut ausgewertet?

Siehe Liste mit möglichen Beziehungen:
http://swbtools.bsz-bw.de/winibwhelp/Liste_3010_3110_AnhangI.pdf

**Comment by mtrojan-ub** [comment]
Kommt von Solr nur als "author_synonyms" zurück, das wird aber im Frontend scheinbar nicht benutzt.

Hinweise zu beteiligten internen Feldnamen (da zusammengesetztes Feld),
laut SolrDefault->getDeduplicatedAuthors

main (primary):
- author
- author_role
secondary:
- author2
- author2-role
corporate:
- author_corporate
- author_corporate_role

@ruschein: bitte prüfen ob da solr-seitig was schief läuft (vermutlich author oder author_role da 100)

**Comment by ruschein** [comment]
@thefass  Das Feld 100 enthält hier keinen Author.  Da steht KommentarverfasserIn und ÜbersetzerIn.

**Comment by IxTheoKm** [comment]
"KommentarverfasserIn und ÜbersetzerIn" ist in diesem Fall falsch erfasst. Es ist nicht für Feld 100 erlaubt, sondern nur für 700. Der genannte Datensatz wird daher wohl immer noch ohne beteiligte Person angezeigt. Ich habe die Titelkorrektur im SWB veranlasst.

**Comment by IxTheoKm** [comment]
Der Titel wurde korrigiert und die beteiligte Person wird nun mit ihrer **ersten** Funktion angezeigt.
Im Internformat sind beide:
700 	1 		|a Knauf, Ernst Axel  |d 1953-  |e **ÜbersetzerIn**  |e **KommentarverfasserIn**  |0 (DE-588)110297555  |0 (DE-576)161750222  |4 trl  |4 wac

@thefass:
Ich meine, das kann so bleiben. Oder sollten immer alle erfassten Funktionen auch in der Kurzliste und Vollansicht angezeigt werden?

**Comment by thefass** [comment]
in der Kurztitelliste reicht die erste Funktion, in der Volltitelliste sollten alle Funktionen angezeigt werden. Ins Internformat werden nur die Spezialisten schauen.
Wenn dieses differenzierte Vorgehen zu kompliziert ist, dann bitte alle Funktionen anzeigen

**Comment by IxTheoKm** [comment]
Die erste Person in 100 (ZusammenstellendeR) wird nicht angezeigt (nur im Internformat):
https://ptah.ub.uni-tuebingen.de/Record/495862967#details
https://www.ixtheo.de/Record/495862967#details

**Comment by mtrojan-ub** [comment]
Ist das Beispiel "ZusammenstellendeR" nun auf ptah korrekt? (es gab eine Änderung am 19. Dezember)

**Comment by IxTheoKm** [comment]
Auf ptah jetzt in Ordnung. Danke!
