### ISSUE TITLE
Suche nach lokalem Abrufzeichen 935 a

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#461]
Soll möglich sein, um direkt nach Datensätzen zu suchen die z.B. als "ixbt" markiert sind.

**Comment by mtrojan-ub** [comment]
kann jetzt auf ptah gesucht werden.

Beispiel-Suche: "record_selector:ixbt"
![grafik](https://cloud.githubusercontent.com/assets/26873381/25528165/a816a88a-2c1c-11e7-9cd7-d9cf843eae47.png)

**Comment by IxTheoKm** [comment]
Nicht alle lokalen Abrufzeichen sind suchbar, z.B. "ixmi". Gibt es Einschränkungen?
Unter "gkix" finde ich nur einen Titel, erfasst ist es aber in 1700 Titeln. 

Wie lautet die Suche nach Kombinationen von Abrufzeichen?

Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/433430834#details
LOK 			|0 935   |a ixst  |a ixfs  |a ixks 

https://ptah.ub.uni-tuebingen.de/Record/47938245X#details
LOK 			|0 935   |a gkix  |a ixrz 

https://ptah.ub.uni-tuebingen.de/Record/467441634#details
LOK 			|0 935   |a ixrz  |a ixmi

**Comment by mtrojan-ub** [comment]
sieht so aus, als ob aktuell nur der erste 935a Wert in solr ankommt, ich kümmere mich drum

**Comment by mtrojan-ub** [comment]
ist behoben, Beispiel-PPN 47938245X (gkix + ixrz)

@IxTheoKm 
> Wie lautet die Suche nach Kombinationen von Abrufzeichen?
record_selector:gkix AND record_selector:ixrz

Aktuell kommt nur dieser Datensatz raus, ab dem nächsten Komplettimport (also ab morgen) funktioniert es dann für alle.

**Comment by thefass** [comment]
@mtrojan-ub : wäre es möglich anstelle record_selector einen Alias zu nutzen, z.b. rs

Da wir das oft brauchen, ist das doch ziemlich lang

**Comment by mtrojan-ub** [comment]
bitte mal auf ptah testen (z.B. "rs:ixbt")

**Comment by IxTheoKm** [comment]
Alle lokalen Abrufzeichen werden jetzt gefunden, auch die mit mehreren Abrufzeichen.
Ich weiß allerdings nicht, wie ich sie kombiniert suchen kann.

**Comment by thefass** [comment]
>>> expertensuche: jeweils ein Suchfeld
z.B. 
rs:ixmi
rs:ixzs
Suchbedingung auswählen

Anderes Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?sort=year+desc%2C+issue+desc%2C+start_page+asc&join=AND&lookfor0%5B%5D=rs%3Aixzs&type0%5B%5D=AllFields&bool0%5B%5D=OR&lookfor1%5B%5D=rs%3Aixmi&type1%5B%5D=AllFields&bool1%5B%5D=NOT&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20

**Comment by IxTheoKm** [comment]
O.K.
