### ISSUE TITLE
Erweiterte Suche: Medienarten im Deutschen falsch sortiert

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#470]
Beispiel Englisch:

![grafik](https://cloud.githubusercontent.com/assets/26873381/25663066/fc37d6a2-3016-11e7-9be7-20635ca085e0.png)

Beispiel Deutsch:
![grafik](https://cloud.githubusercontent.com/assets/26873381/25663151/33f59e94-3017-11e7-9ae2-27727d935f01.png)

Wäre es nicht besser, wenn die Werte unabhängig von der Sprache alphabetisch sortiert sind?

**Comment by thefass** [comment]
Momentan wird nach der englischen Sprache alphabetisch sortiert. Es wäre aber tatsächlich gut, wenn in **Abhängigkeit** der jeweilig gewählten Sprache sortiert würde.

**Comment by mtrojan-ub** [comment]
Stimmt, das hatte ich eigentlich auch gemeint ;-)

Ist in Arbeit. Die Sortierung wird dann auf alle 3 Felder angewendet werden.
Mir ist übrigens aufgefallen, das es im Feld "IxTheo-Notationen" Werte gibt die mit "ixtheo-" anfangen, hier z.B. "ixtheo-AH". Die Felder tauchen auf, wenn man eine andere Sprache als Deutsch wählt. Vermutlich ist dafür keine Übersetzung vorhanden.

![grafik](https://cloud.githubusercontent.com/assets/26873381/25747946/a0b40730-31a9-11e7-82a2-92c61b6dc03c.png)

Die Felder tauchen übrigens auch in Relbib auf, da ebenfalls mit dem Prefix "ixtheo-".

Nach der Änderung der Sortierung werden diese dann ebenfalls gesammelt unter "i" auftreten. 

![grafik](https://cloud.githubusercontent.com/assets/26873381/25748073/1c759cda-31aa-11e7-92cd-89d8b760bccd.png)

**Comment by IxTheoKm** [comment]
Die IxTheo-Notationen werden gerade revidiert. Die mit "ixtheo" beginnenden Notationen sind diejenigen, die neu eingerichtet wurden. Wenn die Revision - einschl. Übersetzungen - abgeschlossen ist, müssen die Notationen im IxTheo und RelBib neu geladen werden.

Die Notationssätze sollten dann auch als Normsätze angezeigt werden können.

**Comment by mtrojan-ub** [comment]
OK - das ist dann aber ein separates Thema das mit der Sortierung nichts zu tun hat. Falls das nach Abschluss der Übersetzungen noch ein Thema ist, bitte neuen Issue aufmachen.

Ich setze diesen Issue jetzt auf Ready for Testing, da das Update heute auf ptah eingespielt wurde

**Comment by IxTheoKm** [comment]
Sortierung ist jetzt in beiden Sprachen o.k.

Die neuen Notationen werden im IxTheo und RelBib (abweichend von ptah) schon korrekt ohne das Präfix "ixtheo" angezeigt. Die neuen Notationen sind also dort schon verankert.
Das vollständig revidierte Notationsschema kommt dann später mit neuem Issue.
