### ISSUE TITLE
Author-Klassifizierung: Neue Aliase

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#471]
Die BSZ Daten enthalten neue Aliase, darunter auch folgende:

Aufn.
Einf.
Einl.
Forts.
Komment.
Nachr.
Vorr.

@IxTheoKm: Wie sollen diese klassifiziert werden?

Verfügbare Klassifizierungen siehe: [author-classification.ini.zip](https://github.com/ubtue/ixTheo/files/973803/author-classification.ini.zip)

**Comment by mtrojan-ub** [comment]
wie gewünscht, hier noch Beispiel-PPNs (Feld 700):

Aufn. => 107768798
Einf. => 000666750
Einl. => 000959502
Forts. => 021818673
Komment. => 009413286
Nachr. => 010216987
Vorr. => 007240147

**Comment by IxTheoKm** [comment]
Nach den Titelbeispielen hier die Umsetzung:
Aufn.              --> FotografIn
Einf.                --> VerfasserIn einer Einleitung
Einl.                --> VerfasserIn einer Einleitung
Forts.              --> [_Würde ich ganz weglassen, weil es nach RDA keine Entsprechung mehr für den "Fortführer" in Analogie zum "Begründer" gibt._] 
Komment.      --> KommentatorIn
Nachr.             --> VerfasserIn eines Nachworts
Vorr.               --> VerfasserIn eines Vorworts
