### ISSUE TITLE
Hilfetext "Personalisierung, Alerting-Funktion"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#485]
Der folgende Text auf der Startseite stimmt nicht:

"Die Alerting Funktion unterrichtet Sie über neu erschienene Aufsätze aus Zeitschriften und neu erschienene Bände in Reihen _und Fortsetzungen_. "

"_und Fortsetzungen_" muss gestrichen werden.

Bei mehrbändigen Werken funktioniert das Alerting nicht (s. Mail vom 27.7.2016).

**Comment by mtrojan-ub** [comment]
@IxTheoKm : Müssen hier auch bestimmte Passagen in anderen Sprachen bereinigt werden?

**Comment by IxTheoKm** [comment]
Nein, die englische und französische Version ist korrekt. In den anderen Sprachen steht derzeit die englische Übersetzung.

**Comment by IxTheoKm** [comment]
Auf ptah o.k.
