### ISSUE TITLE
Mailversand auf noreply-Adressen umstellen und Footer anhängen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#488]
@IxTheoKm : Dieser Issue steht in Bezug zu Ihrer Anfrage zum Thema "VuFind-Konto zurücksetzen" E-Mail, zu der ein Autoresponder an ixtheo@ub.uni-tuebingen.de weitergeleitet wurde

Cronjobs verschicken aktuell mails mit noreply-Absender
VuFind verschickt aktuell mails ohne noreply-Absender

Alle Vufind-Mails sollen ebenfalls den noreply-Absender verwenden
Alle Vufind-Mails sollen einen Footer anhängen, in dem dann die korrekte Adresse referenziert ist (z.B.: Bei Problemen oder Fragen wenden Sie sich bitte an: ...)
Dabei soll natürlich zwischen ixtheo und relbib differenziert werden

**Comment by mtrojan-ub** [comment]
Umgesetzt (im code review)
Noch zu klären, ob ixtheo@ub.uni-tuebingen.de tatsächlich der richtige Verteiler ist, der im Footer angegeben werden soll (gedacht nur für Bibliothekare). Rücksprache halten + falls notwendig neuen Verteiler anlegen lassen (z.B. ixtheo-support@ub.uni-tuebingen.de)

**Comment by mtrojan-ub** [comment]
ready for testing (ptah)

ptah/ub16: local_overrides\ixtheo_site.conf + relbib_site.conf sind bereits angepasst
(greift auf ub16 erst nach pull + ggf cache leeren)

**Comment by thefass** [comment]
@mtrojan-ub : wie kann das von uns geteset werden?

**Comment by mtrojan-ub** [comment]
@thefass : z.B. über Testen der Alerting-Funktion oder Anlegen eines neuen Benutzers (oder Passwort zurücksetzen)

**Comment by thefass** [comment]
Funktioniert beim Test, das Passwort zurückzusetzen.
Die Absenderadresse lautet: ixtheo-noreply@ub.uni-tuebingen.de

Verbessert werden sollte:

- statt "Für ihr Konto bei ub16.uni-tuebingen.de ..." sollte es heißen "Für ihr Konto bei IxTheo ..."
- alles in Englisch (oder ist das sprachabhängig gestaltbar?). Dann müßte im Deutschen aber auch der Footer deutsch sein

**Comment by mtrojan-ub** [comment]
Das "ub16.uni-tuebingen.de" wurde jetzt durch "ixtheo.de" ersetzt, es war lediglich ein Konfigurationsfehler. Bei relbib steht hier übrigens korrekt "relbib.de".

Die Sprache des Mailtexts hängt davon ab, welche Sprache man in der Oberfläche ausgewählt hat wenn man die Funktion verwendet. Allerdings ist der Footer aktuell immer englisch. Ich schaue mir bei Gelegenheit an, ob sich dieser ebenfalls lokalisieren lässt.
