### ISSUE TITLE
Sprachbezeichnung "No linguistic content"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#489]
Bitte in der deutschen Oberfläche für Sprachecode zxx = no linguistic content die Übersetzung anzeigen:
Kein sprachlicher Inhalt
https://ixtheo-test.de/Search/Results?lookfor=bibliography&type=AllFields&limit=20&sort=year+desc%2C+issue+desc%2C+start_page+asc

Übersetzungen für die anderen Oberflächen?

**Comment by mtrojan-ub** [comment]
Müsste eigentlich schon gefixt sein oder zumindest in Arbeit, siehe https://github.com/ubtue/ixTheo/issues/67#issuecomment-301015921

**Comment by IxTheoKm** [comment]
Hier die Übersetzung für "no linguistic content" aus der offiziellen ISO 639 wie sie auch von den anderen Nationalbibliotheken verwendet werden:
s.a. http://www.loc.gov/standards/iso639-2/php/code_list.php

Kein linguistischer Inhalt 
Pas de contenu linguistique
Nessun contenuto linguistico
Sin contenido lingüistíco

Für chinesisch muss ich passen

**Comment by mtrojan-ub** [comment]
@IxTheoKm => eingespielt auf ptah

**Comment by IxTheoKm** [comment]
Jetzt o.k. auf ptah
