### ISSUE TITLE
Tooltip für Schlagwortfolgen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#491]
Kann für "B" ein Tooltip eingerichtet werden?
(Ich nehme an, es soll für "Browsen" stehen.)
![sw-folgen](https://cloud.githubusercontent.com/assets/17004223/26207789/ce8e55b8-3be8-11e7-91c8-d9901cdcc6eb.png)

**Comment by mtrojan-ub** [comment]
PPN: 383726832

**Comment by mtrojan-ub** [comment]
Ja, kann... Es verweist auf die Funktion "Thema browsen" bzw "Find topic". Das B selbst ist aktuell für alle Sprachen gleich.

Soll dann als Tooltip "Find Topic" + Übersetzungen angezeigt werden, und das B bleibt wie es ist?

**Comment by IxTheoKm** [comment]
Ja, so finde ich es sinnvoll.
Allerdings fehlt auf der spanischen Oberfläche unter "Buscar más" die Übersetzung für "Thema browsen". Dort steht noch "Find topic". 
Spanisch kann ich leider nicht. 

@thefass: gibt es für die span. Übersetzungen schon Partner? "Encontrar tema"?

**Comment by mtrojan-ub** [comment]
Übrigens: "Find Topic" hieß wohl ursprünglich "Browse Keywordchains", daher stammt wohl auch das B.

**Comment by mtrojan-ub** [comment]
Ist das auf ptah jetzt so zufriedenstellend?
https://ptah.ub.uni-tuebingen.de/Record/383726832

**Comment by thefass** [comment]
Ja, ist es. ok
