### ISSUE TITLE
Default Sortierung bei Bibelstellensuche

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#495]
Wenn die Nutzer den Aspekt "Bibelstellensuche" auswählen, muss die Default Sortierung bei der Ergebnisdarstellung geändert werden auf "Relevanz" (und nicht "Neueste zuerst")
Sonst greift die entsprechende Sortierung des Bibelstellenalgorithmus nicht.

**Comment by thefass** [comment]
Ein Beispiel für die richtige Sortierung mit Relevanz:
https://www.ixtheo.de/Search/Results?lookfor=Lk+15%2C1-10&type=BibleRangeSearch&sort=relevance

**Comment by mtrojan-ub** [comment]
Beobachtungen dazu (telefonisch mit thefass besprochen):
Fall 1)
* ptah öffnen
* Bibelstellensuche ausführen
* Sortierung nach "Relevanz" wird durchgeführt

Fall 2)
* ptah öffnen
* Suche auf Alle Felder durchführen
* Sortierung ändern (z.B.  Datum absteigend)
* Jetzt Bibelstellensuche ausführen
* Sortierung wird nicht zurückgesetzt, sondern ist noch auf "Datum absteigend"

**Comment by thefass** [comment]
Ideal wäre, wenn immer automatisch die Sortierung "Relevanz" gewählt wird, sobald jemand eine Bibelstellensuche durchführt. Egal, welche Sortierung er zuvor gewählt hat.

**Comment by thefass** [comment]
Fall 2) ist noch nicht gelöst

**Comment by thefass** [comment]
Gelöst ist der Fall, dass nach irgendeiner manuell veränderten Suche (Suchaspekt oder Sortierkriterium) im Suchaspekt "Bibelstelle" automatisch Relevanz eingestellt ist.

Allerdings sollte umgekehrt auch wieder die Sortierung "Neueste zuerst" automatisch aktiviert werden, sobald der Nutzer irgendeinen anderen Suchaspekt nach der Bibelstellensuche ausgewählt hat.

**Comment by thefass** [comment]
soweit ok. Fehlendes habe ich als neues Issue unter tuefind eröffnet
