### ISSUE TITLE
Sortierung "Älteste zuerst" liefert seltsame Ergebnisse

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#498]
![grafik](https://cloud.githubusercontent.com/assets/26873381/26308099/0c3e8920-3ef8-11e7-8161-6820aa1a595f.png)

**Comment by mtrojan-ub** [comment]
Fix auf ptah, Test nach nächstem Import

**Comment by mtrojan-ub** [comment]
Sortierung auf ptah jetzt wieder ähnlich wie auf ixtheo. Allerdings gibt es (auch auf ixtheo) derzeit noch Probleme mit bestimmten Datensätzen, im Kontext "19XX" oder "19uu":

Bei Sortierung nach "Älteste zuerst" sind mehrere tausend der ersten Ergebnisse falsch sortiert
https://ixtheo-test.de/Search/Results?type=AllFields&sort=year+asc&page=870

(Die ersten paar hundert Seiten enthalten gemischte Ergebnisse mit 17XX, 18XX, 19XX usw, bevor es dann wieder mit Werken ab 1400 losgeht)

Screenshot ixtheo:
![grafik](https://cloud.githubusercontent.com/assets/26873381/26342962/6d73406c-3f9a-11e7-90ed-af950bc815c9.png)

Wie gehen wir mit Datensätzen um die als Datum ein Format ähnlich "19XX" oder "19uu" haben?
Diese werden aktuell mit leerem Wert sortiert und stehen dann entweder ganz am Anfang oder ganz am Ende. 
* Handelt es sich um "falsche" Datensätze die korrigiert werden müssen? (Ist dies den Bibliothekaren überhaupt möglich ein genaueres Datum anzugeben?)
* Würde es mehr Sinn machen diese z.B. eher in Richtung 1900 oder 1999 zu sortieren?

**Comment by IxTheoKm** [comment]
Die XX-Angaben im Erscheinungsjahr sind Altdaten: bei mehrbändigen Werken hat man früher das Erscheinungsjahr in der übergeordneten Aufnahme nicht angegeben (s.a. Issue #387). Da das Feld für Erscheinungsjahre vorgeschriegen war, wurde m.W. anfangs maschinell, dann manuell immer mit XX katalogisiert.

Genau genommen müsste bei "älteste zuerst" nach dem Erscheinungsjahr des ersten verknüpften untergeordneten Werks sortiert werden, bei "neueste zuerst" nach dem letzten verknüpften untergeordneten Werk.
Oder man muss legt grundsätzlich das Erscheinungsjahr des _ersten_ verknüpften Bandes zugrunde, wenn das möglich ist.
Bsp.:
https://ixtheo-test.de/Record/03349195X
Erster verknüpfter Band **1989**: https://ixtheo-test.de/Record/019312776
Zweiter verknüpfter Band **2001**: https://ixtheo-test.de/Record/096698012

**Comment by thefass** [comment]
Bei den Gesamtaufnahmen sollte das Sortierjahr immer der erste verknüpfte Band sein. Mit dem ersten Band tritt ja eine Gesamtaufnahme (= Reihe oder Fortsetzung) zum erstenmal in Erscheinung. So ist es sachlich richtig, die Gesamtaufnahme mit dem Erscheinungsjahr des ersten Bandes zu verknüpfen.
@IxTheoKm : was ist 19uu? Identisch mit XX?

**Comment by thefass** [comment]
@IxTheoKm : sind Jahresangaben mit XX immer Gesamtaufnahmen oder kann das auch gesetzt werden, wenn man das genaue Jahresdatum nicht kennt, so dass 18XX auch für das 19. Jahrhundert stehen könnte?

**Comment by mtrojan-ub** [comment]
und was ist mit Werken die weder untergeordnete Werke noch verknüpfte Bände haben?
https://ptah.ub.uni-tuebingen.de/Record/029811457

**Comment by jriedl** [comment]
Für die oben genannte PPN 03349195X ist genau das der Fall. Die Sortierung erfolgt anhand des älteren untergeordenten Bandes, also 1989. Die Ausreißer bei "Älteste zuerst" sind offenbar die Titel, denen keine untergeordneten Werke für eine Jahreszahlbestimmung zur Verfügung stehen und deshalb kien sinvolles Sortierdatum ableitbar ist.

**Comment by thefass** [comment]
PPN 029811457 wurde automatisch für den IxTheo selektiert (erkennbar an mteo in 935 $a). Es hängen auch im Verbund Bände daran (z.B. PPN 045121648) , die aber nicht mit mteo ausgezeichnet wurden und so nicht an IxTheo ausgeliefert werden.
Wir bräuchten also eine Nachauszeichnung (Kaskade) auch der Bände mit mteo, wenn die Gesamtaufnahme mteo hat. 
Allerdings ist zu bedenken, dass wir nicht immer alle Bände einer Gesamtaufnahme im IxTheo haben wollen, da es Reihen gibt, in der nur einzelne Bände einen theologischen Bezug haben.

**Comment by thefass** [comment]
Wenn es ein untergeordnetes Werk gibt, wird das Erscheinungsjahr erzeugt und in 190 $j geschrieben. Siehe https://ixtheo-test.de/Record/03349195X 
@mtrojan-ub : wieviele Sätze mit XX oder uu gibt es, die kein Datum in 190 $j haben? 
Wenn wir das wissen, können wir das Problem von seiner Größe besser einschätzen.

**Comment by IxTheoKm** [comment]
Zur Frage 19uu: erfasst wird 19XX. Ich denke, mit 19uu ist das Marc-Format gemeint.

Zur Frage ...XX=Gesamtaufnahme: Es kommen auch Fälle mit unbekanntem Jahr vor. Es gibt insbesondere bei maschinellen Einspielungen nichts was es nicht gibt. 
Bsp.:
PPN 395692105: 19XX$n[o.J.]
PPN 484166271: 19XX$n[s.a.]
PPN 48416578X: 19XX$n19XX
PPN 484137999: 19XX
PPN 345681665: 19XX$n[199-?]
PPN 333037758: 19XX$nn.d.
PPN 318326299: 19XX$n1989-1992
PPN 273543970: 19XX$n[ca.1915]
PPN 272817279: 19XX$n[1975?]

**Comment by mtrojan-ub** [comment]
zu https://github.com/ubtue/ixTheo/issues/498#issuecomment-303335535
wieviele Sätze mit XX oder uu gibt es => ca 67000
die kein Datum in 190 $j haben => ca 12000

**Comment by mtrojan-ub** [comment]
Wie im Meeting besprochen => Verhalten ist für den Moment zufriedenstellend. Könnte weiter optimiert werden, aber die aufsteigende Suche nach Datum nutzt kaum jemand. Daher => "später".
