### ISSUE TITLE
Link Volltext

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#50]
Bei titeln, die den Link "Volltext" haben, funktioniert der Link nicht. Grund ist, dass dahinter nur die URN liegt, die müsste aber resolvt werden. Wenn nicht, bekommt man den 404 Fehler

Beispiel:
http://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter[]=format%3A%22eBook%22&filter[]=dewey-hundreds%3A%22200+-+Religion%22

Dort der erste Titel: "Der Königsweg der Apostel in Edessa, Indien und Rom "

**Comment by oobenland** [comment]
@ruschein Gab es dafür nicht einen Schritt in der Pipeline?

**Comment by thefass** [comment]
hier nochmal der Link direkt auf den oben genannten Titel:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Der+K%C3%B6nigsweg+der+Apostel+in+Edessa%2C+Indien+und+Rom+&type=Title&filter[]=format%3A%22eBook%22&filter[]=dewey-hundreds%3A%22200+-+Religion%22&limit=20&sort=relevance

**Comment by ruschein** [comment]
Sollte beim nächsten Datenimport hoffentlich behoben sein.

**Comment by oobenland** [comment]
Wir haben noch einen Bug gefunden und gefixt. Morgen sollten die Daten dann auch angepasst sein.

**Comment by oobenland** [comment]
Die Links sind jetzt bereinigt.

**Comment by thefass** [comment]
getestet. ok
