### ISSUE TITLE
Anzeige des Datenstands

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#501]
Insbesondere für Datentests sollte irgendwo ein Datum des letzten Imports angezeigt werden. Es muss nicht unbedingt auf den ersten Blick präsent für andere Nutzer sein, wenn dies nicht erwünscht ist.

**Comment by ruschein** [comment]
Ist bis auf wenn ein Fehler in der Pipeline stattgefunden hat, was auf dem Produktionssystem selten passiert immer letzte Nacht.

**Comment by IxTheoKm** [comment]
Siehe #517: die Korrektur vom 30.5. ist am 2.6. noch nicht angekommen. Die neuen Daten vom 1.6. sind am 2.6. nicht vorhanden

**Comment by IxTheoKm** [comment]
Datensatz vom 17.7. ist am 19.7. 9:10 Uhr im IxTheo, aber nicht in ptah und nicht in RelBib:

https://ixtheo-test.de/Search/Results?lookfor=id%3A49092557X&type=AllFields
https://134.2.67.9/Search/Results?lookfor=id%3A49092557X&type=AllFields
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A49092557X&type=AllFields

Weiteres Beispiel: 490918204 ...

In #517 steht dass, "RelBib und IxTheo Fenster die exakt gleichen Daten sind"

**Comment by jriedl** [comment]
Die Datenstände sollte spätestens morgen wieder synchron sein. Zur Auflösung des Wiederspruchs zwischen RelBib und ptah: relbib.de und ixtheo.de teilen sich einen Rechner und greifen auf den gleichen Datenbestand zu, ebenso wie ptah.ub.uni-tuebingen.de und 134.2.67.9. Es gibt also zwei Relbib-Instanzen, so wie es zwei ixtheo-Instanzen gibt.

**Comment by ruschein** [comment]
@jriedl Kann man dieses Issue wieder zu machen?

**Comment by jriedl** [comment]
Mittels der in #514 angebenen Abfrage der Form `first_indexed:[2017-05-30T00\:00\:00Z TO NOW]` lässt sich überprüfen, wann ein neue Titel hinzugekommen sind. Falls damit alle Aspekte der Ausgangsfrage abgedeckt sind, kann das Issue geschlossen werden.

**Comment by IxTheoKm** [comment]
Mit der Abfrage o.k.
