### ISSUE TITLE
Titel mit einleitendem Schrägstrich

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#502]
Teile von mehrbändigen Werken, deren Titel in 245 $p stehen:
die Titel werden nach einleitendem Schrägstrich angezeigt.
Das hat Konsequenzen auf die Sortierung nach Titeln:
https://ixtheo-test.de/Search/Results?lookfor=&type=AllFields&limit=20&sort=title
Die Schrägstriche sollten weder angezeigt noch für die Sortierung berücksichtigt werden.

091402956 245 13$pLa quatrième campagne de fouilles à Ras-Sahmra : (printemps 1932)…
091402964 245 13$pLa cinquième campagne de fouilles à Ras-Sahmra : (printemps 1933)…
28735363X 245 10$p[Hauptbd.]
287353648 245 10$p[Hauptbd.]
287382907 245 10$pReligion
315720166 245 10$pBuch I bis VI
318401959 245 10$pFürbitten und Einführungsworte für die Wochentage
318401967 245 10$pFürbitten und Einführungsworte für die Wochentage im Jahreskreis
400929481 245 14$pDie wirkliche Gegenwart des Leibes und Blutes Jesu Christi ...
416953697 245 10$pAllgemeine Korrespondenz : 2
417241674 245 10$pEinleitung und das erste Hauptstück

**Comment by mtrojan-ub** [comment]
Das ist beides auf ptah bereits behoben:
https://ptah.ub.uni-tuebingen.de/Record/091402956
* Das Prefix " / " wurde für die entfernt, da es keinen regulären Titel oder Untertitel gibt
* Die Sortierung kam daher, dass solrmarc beim Import in das title_sort Feld bisher nur 245er Subfelder a, b und k berücksichtigt hat. Dies wurde um p erweitert.

**Comment by IxTheoKm** [comment]
Jetzt o.k.
