### ISSUE TITLE
Korrektur im Normsatz kommt nicht im Titelsatz an

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#503]
Siehe auch #240 

Im Normsatz "Samaniden" wurde am 17.05.2017 zum Test die französische Verweisung
700 0 $a**Samanides**$2IxTheo$9L:fre$9Z:AF
ergänzt.
Diese Verweisung ist aber in den Titelsätzen, die schon vorher im IxTheo waren, in Feld 186 nicht vorhanden:
https://ptah.ub.uni-tuebingen.de/Record/383726832#details
https://ptah.ub.uni-tuebingen.de/Record/04477804X#details

(Zum Datenstand siehe #501)

**Comment by jriedl** [comment]
Die Übersetzung findet sich nicht in den aktuellen Normdaten (Stand 22.05)
> 001 213521458
> 003 DE-576
> 005 201702221629.0
> 008 990519n||aznnnaabn           | aaa    |c
> 024 7 $ahttp://d-nb.info/gnd/121067513$2uri
> 035   $z(DE-588c)4542663-6$9v:zg
> 035   $z(DE-588a)121067513$9v:zg
> 035   $a(DE-588)121067513
> 040   $aDE-576$bger$cDE-576$erakwb
> 043   $cXB-IR
> 065   $a16.5p$2sswd
> 079   $ag$bp$cv$qs$uw$vpiz
> 100 0 $aSamaniden
> 670   $aB 1986
> 678   $bIran. Dynastie
> 700 0 $aSamanids$2IxTheo$9L:eng$9Z:AF
> 700 0 $aSamanid Dynasty$2IxTheo$9L:eng$9Z:VW
> 913   $Spnd$i5$aSamaniden$0(DE-588a)121067513

**Comment by IxTheoKm** [comment]
Info lt. BSZ-Seite https://wiki.bsz-bw.de/doku.php?id=v-team:daten:datendienste:sekkor  
"Die Sekundärkorrekturen werden immer in der Nacht von Donnerstag auf Freitag erstellt, (Abzugszeitraum jeweils Donnerstag 23:59 Uhr) und stehen jeweils am Freitag zur Verfügung."
Demnach müsste die Ergänzung vom 17.5. in der Nacht vom 18. auf den 19. zur Verfügung stehen müssen. Anfrage beim BSZ läuft.

**Comment by IxTheoKm** [comment]
Info vom BSZ: die Änderung war in den Sekundärkorrekturen mit Datum 170519 im Dateinamen enthalten. Z.B. in der für Sie relevanten MARC-Datei: WA-MARCcomb-sekkor-170519.tar.gz im Verzeichnis sekkor auf unserem VFTP-Server

**Comment by ruschein** [comment]
Wenn man jetzt auf Französisch wechselt wird "Samanides" angezeigt.

**Comment by IxTheoKm** [comment]
Jetzt o.k.

**Comment by IxTheoKm** [comment]
Die Normsatzergänzungen (englische Übersetzungen in Feld 730) sind (noch?) nicht im IxTheo angekommen. Die Einspielung war am 18.10.2017.
(Zu den nicht recherchierbaren Verweisungen von Feld 430 siehe #126)

Beispiel:
cz a22 n 4500
001 433042443
003 DE-576
005 201710181111.4
008 150520n||aznnnaabn | ana |c
024 7 $ahttp://d-nb.info/gnd/1071362852$2uri
035 $a(DE-588)1071362852
040 $aDE-576$bger$cDE-576$erakwb
065 $a3.6a$2sswd
079 $ag$bu$cv$qs$uw$vwit
083 04$a262.52$9d:1$9t:2016-08-01$222/ger
130 0$a**Katakombenpakt**
377 7$aspa$2iso639-2b
430 0$aActo de las catacumbas de la iglesia sierva y pobre
430 0$aKatakombenpakt für eine dienende und arme Kirche
430 0$aDreizehn Selbstverpflichtungen ungenannter Bischöfe auf dem Zweiten Vatikanischen Konzil
548 $a1965$94:datj$wr$iErscheinungszeit
550 $0(DE-576)272690368$0(DE-588)7583378-5$aFreiwillige Armut$94:them$wr$iThema
550 $0(DE-576)21245174X$0(DE-588)4438928-0$aSelbstverpflichtung$94:obin$wr$iOberbegriff instantiell
670 $aWikipedia
670 $aStand: 20.05.2015$uhttp://www.pro-konzil.de/katakombenpakt-fur-eine-dienende-und-arme-kirche/
679 $aAm 16. November 1965, während des Zweiten Vatikanischen Konzils, in den Domitilla-Katakomben in Rom von einer Gruppe von Bischöfen unterzeichnete Selbstverpflichtung zu einem einfachen Lebensstil und zum Dienst an den Armen
730 7$a**Catacombs' Pact**$2IxTheo$9L:eng$9Z:AF
730 7$a**Catacombs' pact of the servant and poor church**$2IxTheo$9L:eng$9Z:VW

**Comment by jriedl** [comment]
Fremdsprachige Synonyme fließen auf ptah jetzt ebenfalls in die Auswertung ein.

**Comment by jriedl** [comment]
Welche Punkte sind hier noch offen?

**Comment by IxTheoKm** [comment]
Ich habe nochmal mit einer fiktiven Übersetzung im Normsatz getestet, ohne den Titel zu aktualisieren:
Sekundärkorrektur hat funktioniert. Damit jetzt o.k., danke!

**Comment by IxTheoKm** [comment]
Sekundärkorrekturen kommen wieder nicht an. Neues Issue in tuefind.

**Comment by thefass** [comment]
Da neues Issue unter tuefinde, schließe ich dieses Issue.
