### ISSUE TITLE
DNB Link in 856 bei "ixbt" Titel

### ISSUE THREAD

**Issue by socheres** [ubtue/ixTheo#506]
Der Link auf DNB führt ins Leere. Bitte dieses URL-Feld bei der Anzeige von "ixbt"-Titel ausschließen. Bsp.:
/Record/487043553

856 	4 	0 	|u http://d-nb.info/1122972296/34  |x Nationalbibliothek

**Comment by thefass** [comment]
dazu bräuchte es ja die Regel keine Links wenn |x Nationalbibliothek

@socheres : Können wir garantieren, dass solche Links generell mess data sind?

**Comment by socheres** [comment]
@thefass DNB-Links überprüft und größtenteils führt der Link zum Volltext. Daher generelle Regel leider nicht mögl.
