### ISSUE TITLE
Weitere Kriterien für die Sortierung nach "Neueste zuerst"

### ISSUE THREAD

**Issue by jriedl** [ubtue/ixTheo#514]
Derzeit erfolgt die Sortierung nach "Neueste Zuerst" nach Erscheinungsjahr, Bandnummer und Seitenzahl. Es ist nun der Wunsch aufgekommen, weitere Sortierkriterien einzuführen, um die Suchergebnisse bei einer leeren Suche "nachvollziehbarer" zu machen. Ein Vorschlag wäre, das Feld 005 (letztes Änderungsdatum) zu verwenden, allerdings hat sich im Zusammenhang mit dem new_journal_alert gezeigt, dass dies z.T. zu nicht intendierten und wenig nachvollziehbaren Ergebnissen führt. Sollte innerhalb der Records ein dauerhaftes Ersterfassungsdatum existieren, so kann dieses verwendet werden.

**Comment by obrandt** [comment]
Hm,

ich frage mich gerade ob wir ein Produkt überoptimieren und es damit zu komplex machen.

Viele Grüße

Olaf

Von: jriedl [mailto:notifications@github.com]
Gesendet: Dienstag, 30. Mai 2017 14:06
An: ubtue/ixTheo <ixTheo@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [ubtue/ixTheo] Weitere Kriterien für die Sortierung nach "Neueste zuerst" (#514)


Derzeit erfolgt die Sortierung nach "Neueste Zuerst" nach Erscheinungsjahr, Bandnummer und Seitenzahl. Es ist nun der Wunsch aufgekommen, weitere Sortierkriterien einzuführen, um die Suchergebnisse bei einer leeren Suche "nachvollziehbarer" zu machen. Ein Vorschlag wäre, das Feld 005 (letztes Änderungsdatum) zu verwenden, allerdings hat sich im Zusammenhang mit dem new_journal_alert gezeigt, dass dies z.T. zu nicht intendierten und wenig nachvollziehbaren Ergebnissen führt. Sollte innerhalb der Records ein dauerhaftes Ersterfassungsdatum existieren, so kann dieses verwendet werden.

**Comment by IxTheoKm** [comment]
Das Ersterfassungsdatum eines Datensatzes steht m.W. in 008:
Bsp.:
PPN 467156476 Ersterfassungsdatum **5.4.2016**, letzte Korrektur 29.5.2017
008 **160405**s2011 xx 00 0 eng c

Ich finde es aber nicht so sinnvoll, das Ersterfassungsdatum heranzuziehen. Das Berichts- und Erscheinungsjahr ist in diesem Fall 2011. Wem hilft es, dass als weiteres Kriterium das Erfassungsjahr 2016 herangezogen wird? Besonders bei Migrationen wie in diesem Fall!
Wenn überhaupt weitere Kriterien sinnvoll wären, dann diejenigen, die "offensichtlich" sind (z.B. Titel)

**Comment by Gazeller** [comment]
Es geht ja nur um ein zweites, sprich nachgeordnetes  Kriterium. Wenn etwas 2011 erschienen ist, wird es eben innerhalb der 2011er Titeln danach sortiert, wann es erfasst wurde, das tut bei den alten Titeln niemand weh. Sie bleiben ja innerhalb des 2011-Segment.
Das Ganze ist aber durchaus interessant bei den aktuellen Jahrgängen, wo ja im Moment so ziemlich alles Erscheinungsjahr 2017 trägt und es mir nicht ersichtlich ist, wonach es danach sortiert wird. Band-Nummer?, Heftnummer?, Seitenzahlen?
Es ist einfach merkwürdig und nicht richtig nachvollziehbar, wenn tagelang dasselbe auf der 1. Seite erscheint, obwohl täglich neues katalogisiert wurde.
Gruß Gaby


-----------------
Dr. Gabriele Zeller
Tel. 29-74030
Zi. H 228 - UB Hauptgebäude

Von: IxTheoKm [mailto:notifications@github.com]
Gesendet: Dienstag, 30. Mai 2017 14:34
An: ubtue/ixTheo <ixTheo@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/ixTheo] Weitere Kriterien für die Sortierung nach "Neueste zuerst" (#514)


Das Ersterfassungsdatum eines Datensatzes steht m.W. in 008:
Bsp.:
PPN 467156476 Ersterfassungsdatum 5.4.2016, letzte Korrektur 29.5.2017
008 160405s2011 xx 00 0 eng c

Ich finde es aber nicht so sinnvoll, das Ersterfassungsdatum heranzuziehen. Das Berichts- und Erscheinungsjahr ist in diesem Fall 2011. Wem hilft es, dass als weiteres Kriterium das Erfassungsjahr 2016 herangezogen wird? Besonders bei Migrationen wie in diesem Fall!
Wenn überhaupt weitere Kriterien sinnvoll wären, dann diejenigen, die "offensichtlich" sind (z.B. Titel)

**Comment by thefass** [comment]
Das Issue sollte auf jeden Fall im Kontext des noch ausstehenden Features "Neuerschscheinungsliste" betrachtet werden. Da müssen aber noch einige Vorüberlegungen getätigt werden.
Der "stehende" Eindruck ist nach meiner Beobachtung vor allem bei der Medienart Buch so, nicht aber bei den Aufsätzen. 
@Gazeller : wie ist Deine Beobachtung auf relbib?

**Comment by Gazeller** [comment]
Ich meine es auch bei den Artikeln beobachtet zu haben. Ich mache jetzt mal täglich einen Screenshot der ersten Seite, dann können wir das am ehesten vergleichen.
Gruß Gaby

-----------------
Dr. Gabriele Zeller
Tel. 29-74030
Zi. H 228 - UB Hauptgebäude

Von: thefass [mailto:notifications@github.com]
Gesendet: Dienstag, 30. Mai 2017 16:50
An: ubtue/ixTheo <ixTheo@noreply.github.com>
Cc: Gazeller <gabriele.zeller@ub.uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ubtue/ixTheo] Weitere Kriterien für die Sortierung nach "Neueste zuerst" (#514)


Das Issue sollte auf jeden Fall im Kontext des noch ausstehenden Features "Neuerschscheinungsliste" betrachtet werden. Da müssen aber noch einige Vorüberlegungen getätigt werden.
Der "stehende" Eindruck ist nach meiner Beobachtung vor allem bei der Medienart Buch so, nicht aber bei den Aufsätzen.
@Gazeller<https://github.com/gazeller> : wie ist Deine Beobachtung auf relbib?

**Comment by jriedl** [comment]
Als _interner_ Workaround für neu hinzugekommene Werke ließe sich eine Abfrage wie 
`first_indexed:[2017-05-30T00\:00\:00Z TO NOW]` verwenden.

**Comment by jriedl** [comment]
first_indexed fließt ja, wie vor einiger Zeit besprochen, mittlerweile mit in die Sortierung ein.Problematik sollte damit gelöst sein.
