### ISSUE TITLE
Mit mtex "ausgeschiedene" Titel werden noch angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#516]
Bsp.: 
935 $a mteo am 9.5.2017 zu mtex korrigiert
PPN 484258222
PPN 484262416
PPN 484262777
PPN 484263080

Werden die Sätze nicht bei den Korrekturen mitgeliefert, so dass sie durch "mtex" entfernt werden können?

**Comment by jriedl** [comment]
Mit mtex ausgezeichnete Titel werden nicht im Rahmen der Gesamt- und Differenzabzüge nicht ausgeliefert, so dass Löschungen auf diesem Weg nicht detektiert werden können. Wir werden in Zukunft gesonderte Abzüge mit den mtex-PPNs erhalten, so dass wir hier filtern können.

**Comment by IxTheoKm** [comment]
In welchen Abständen werden die mtex-PPNs zum Löschen geliefert?
Ich habe 025004808, 252296451, 014436256, 00737609X, 118145177 und 490560008 Anfang Juli mit mtex versehen. Sie sind alle noch da.

**Comment by jriedl** [comment]
Seit dieser Woche werden die mtex-Löschlisten vom BSZ wöchentlich zur Verfügung gestellt. Ab Anfang nächster Woche werden sich diese im Datenbestand niederschlagen.

**Comment by jriedl** [comment]
Ist auf ptah eingerichtet.

**Comment by IxTheoKm** [comment]
Alle mtex-Titel sind aus ptah entfernt.
