### ISSUE TITLE
Korrektur im Lokalsatz kommt nicht an

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#517]
https://ixtheo-test.de/Record/489078699#details
Das Abrufzeichen wurde am 30.5. korrigiert zu "ixbt", ist am 1.6. noch in der alten Version vorhanden:
![muster](https://cloud.githubusercontent.com/assets/17004223/26686369/001cf2d8-46ed-11e7-88af-d03d8e240858.png)

**Comment by IxTheoKm** [comment]
In RelBib ist der Datensatz im Gegensatz dazu in der korrigierten Version vom 1.6. vorhanden, im IxTheo hat er den Stand 29.5.

**Comment by ruschein** [comment]
@IxTheoKm Das kann gar nicht sein da RelBib und IxTheo Fenster in die exakt gleichen Daten sind.  Vielleicht haben Sie da auf 2 verschiedenenRechenern recherchiert?  (ptah vs. ub16)
Herr Riedel meinte das, dass mittlerweile vermutlich sowieso funktioniert.

**Comment by IxTheoKm** [comment]
Den obigen Fall kann ich nicht mehr rekonstruieren.

Die Korrektur der _Lokaldaten_ vom 4.7.2017 in PPN 490199895 ist am 5.7.2017 _nicht_ angekommen. (Ergänzung einer Notation zum Test.)
Die Korrekturen am selben Tag in verschiedenen anderen _Titelsätzen_ aber schon. (Ergänzung der Sprache in allen Aufsätzen von PPN 266226736.)

**Comment by IxTheoKm** [comment]
Wenn Korrekturen nur im Lokalsatz erfolgen und nicht noch zusätzlich im Titelsatz, kommen sie nicht im IxTheo an. Das bedeutet: alle Ergänzungen von Notationen im Lokalsatz, also die reine klassifikatorische Sacherschließung kommt nicht an, wenn nicht auch im Titel eine Korrektur erfolgt ist!
Bsp.: 
490153127
Titel- und Lokaldaten wurden am 23.6.2017 erfasst.
Die IxTheo-Notationen wurden am 5.7.2017 ergänzt.

490294529
Die Titel- und Lokaldaten wurden am 28.6.2017 erfasst.
Die Titeldaten wurden am 29.6.2017 korrigiert.
Die IxTheo-Notationen wurden am 30.6.2017 ergänzt.

**Comment by IxTheoKm** [comment]
Die fehlenden Notationen stehen in 936 $a
Beispiel _mit_ Notationen: 442599633, 442599676.

Betroffen wären aber alle Änderungen in Lokalsätzen, z.B. auch Korrekturen von Abrufzeichen in 935 $a.
Das Fehlen der Notationen ist allerdings besonders gravierend, da die betr. Titel dann keine Sacherschließung enthalten.

**Comment by IxTheoKm** [comment]
Korrekturen sind heute, 12.7.2017 14:09 (noch?) nicht angekommen. 
Allerdings finde ich auch keine neuen Daten, die am 11.7. erfasst wurden. 
Hat die Datenbank den Stand 10.7.2017?

**Comment by IxTheoKm** [comment]
18.7.2017 14:00 Uhr:
Korrekturen in den **Titel**daten von PPN 490153127 sind in ptah angekommen (in IxTheo noch nicht).
Korrekturen in **Titel**- und Lokaldaten von PPN 490294529 sind in ptah angekommen (in IxTheo noch nicht).

(IxTheo ist wohl noch nicht aktuell. Dort fehlt z.B. im Gegensatz zu RelBib PPN 488472563. In ptah vorhanden.)

**Comment by IxTheoKm** [comment]
Lieferung der Korrekturen in Lokaldaten nach Änderung der Abzugsroutine jetzt erledigt
