### ISSUE TITLE
Erweiterte Suche: Löschen der ersten Suchgruppe führt zu Fehlverhalten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#521]
Kürzeste Möglichkeit zum Reproduzieren:
* Erweiterte Suche öffnen
* Suchgruppe hinzufügen (erste Gruppe bleibt leer), und z.B. "Bibel" eintragen
* Erste (leere) Suchgruppe entfernen, so dass nur die zweite übrig bleibt
* Suche starten

=> jetzt wird der komplette Datenbestand angezeigt, und der Filter "Bibel" nicht angewendet.

unklar: handelt es sich um ein allgemeines VuFind-Problem?
(=> evtl nicht selbst fixen sondern an VuFind melden?)

**Comment by thefass** [comment]
ich konnte das Probelem reproduzieren. Gut, dass Sie das entdeckt haben

**Comment by mtrojan-ub** [comment]
Das Problem tritt aktuell auf ptah nicht mehr auf. Daher gehe ich davon aus dass es mit Vufind 4 behoben wurde und schließe den Issue.
