### ISSUE TITLE
Thema browsen: Angezeigte und tatsächliche Treffermenge weichen ab

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#522]
Sucht man mittels der Funktion "Thema browsen" nach "Isaak", werden mehrere Zeilen mit Treffern angezeigt, davon 12 in der ersten Zeile

![grafik](https://user-images.githubusercontent.com/26873381/27217138-eb44bb38-5278-11e7-9a73-52bb1fe665b0.png)

Klickt man auf "Datensätze ansehen" landet man jedoch in einer Liste mit 117 Treffern.

![grafik](https://user-images.githubusercontent.com/26873381/27217207-35bc8506-5279-11e7-9392-7671dfa48770.png)

**Comment by ruschein** [comment]
@mtrojan-ub ping
