### ISSUE TITLE
Zitieren: Lebensdaten von Autoren werden mit angezeigt

### ISSUE THREAD

**Issue by Gazeller** [ubtue/ixTheo#543]
![zitieren_problem](https://user-images.githubusercontent.com/16898788/27864721-0170d092-6190-11e7-880d-fcf611c53d48.PNG)

Lebensdaten von Autoren sollten in den Zitaten nicht erscheinen

**Comment by thefass** [comment]
Zitation auf Ptah richtig

**Comment by Gazeller** [comment]
Wirklich? Geburtsdatum wird auch jetzt noch angezeigt. RelBib test und Ixtheo geprüft. RelBib ptah im Moment nicht zugänglich für mich. 
![grafik](https://user-images.githubusercontent.com/16898788/28017315-fda20fca-6578-11e7-860b-7a657d0af2c4.png) - Vor allem APA sieht doch komisch aus mit der 1. als abgekürzter "Vorname"?!
