### ISSUE TITLE
Filter: Elemente verschwinden nach Auswahl

### ISSUE THREAD

**Issue by Gazeller** [ubtue/ixTheo#546]
Nach einfacher Suche: Bei Auswahl eines Elements aus dem ausklappbaren Menu eines Filters, verschwindet die Anzeige dieses Elements im Filter. Beispiele:  Medienart Zeitschrift. So auch bei DDC Auswahl ab 300.

![grafik](https://user-images.githubusercontent.com/16898788/27870922-7b421476-61a4-11e7-9464-7459854caa81.png)

**Comment by ruschein** [comment]
@Gazeller Kann ich nicht reproduzieren.  Geht das eventuell mittlerweile?

**Comment by relhei** [comment]
Das "Problem" besteht weiter. Möglicherweise VuFind-typisch, also Feature statt Bug?

**Comment by jriedl** [comment]
Es wurde jetzt eine neue Facettenlogik integriert (sichtbar auf ptah), bei der die Standardsortierung wieder nach Häufigkeit ist, weitere Facetten in einem gesonderten Fenster geöffnet werden (dadurch keine Beschränkung der Anzahl der Facetten mehr) und der Nutzer im Bedarfsfall selbst auf alphabetische Sortierung umstellen kann. Das Ausgangsproblem sollte damit auch gelöst sein.

**Comment by thefass** [comment]
Ausgangsproblem gelöst.
zum gesonderten Fenster eröffne ich ein neues issue

**Comment by relhei** [comment]
Können wir dan das issue schließen?

**Comment by ruschein** [comment]
@relhei Wir haben eigentlich ausgemacht, dass die Person, die ein Issue aufmacht es auch wieder zumachen soll.  Ich mache es mal ausnahmsweise selbst zu.
