### ISSUE TITLE
PDA erscheint bei E-Book

### ISSUE THREAD

**Issue by Gazeller** [ubtue/ixTheo#548]
der PDA Hinweis sollte nicht bei E-books erscheinen, weil ein "Kauf" durch Nutzer wohl nicht ohne weiteres möglich / sinnvoll (er könnte u.U dann trotzdem nicht drauf zugreifen!)
Zudem ist die Wendung "Ist in Deutschland nicht verfügbar..." falsch, das E-Book des Beispiels war in Mannheim lizenziert. (s Mail vom 6.7.17 mit Screenshots)

**Comment by thefass** [comment]
PDA Hinweis kommt bei eBooks nicht mehr
@Gazeller : bitte auch nochmal prüfen und Issue mit Klick unten auf Close an comment schließen, wenn es stimmt
