### ISSUE TITLE
Fehler in BEACON Datei

### ISSUE THREAD

**Issue by socheres** [ubtue/ixTheo#550]
zwei Auffälligkeiten:

1. in https://ixtheo.de/docs/ixtheo-beacon.txt fehlt die GND-ID 129044342 trotz damit verknüpfte Titel in https://ixtheo.de/Record/374742464

2. GND-ID 115684336 hat 324 verknüpfte Titel. In der BEACON-Datei sind es nur "115684336|236" Treffer.

@ruschein bitte überprüfen, ob alle IxTheo-Normdatensätze bei der automatischen Generierung der Liste berücksichtigt wurden und ob die Trefferzahl entsprechender GND-ID richtig sind.

**Comment by ruschein** [comment]
Das Problem ist, dass (DE-588)297464426 nicht im 035$a Feld eines Normdatensatzes vorkommt.

**Comment by socheres** [comment]
@ruschein für die Trefferanzahl bitte neben 100-Feld auch folgende Felder auswerten:
700$0 mit dem Sprachcode (DE-588) 
689 $0

**Comment by ruschein** [comment]
@socheres Chang-Wei, I brauche immer noch die Liste der Felder, die ich alle auswerten soll.

**Comment by ruschein** [comment]
@socheres ping

**Comment by socheres** [comment]
@ruschein für die Trefferanzahl sind folgende Felder aus Titeldaten auszuwerten:

100 a, 600a, 689a, 700a 
nach "(DE-588)" stehen dann die GND-ID.

**Comment by socheres** [comment]
@ruschein stimmt noch nicht ganz. welche felder werden alles ausgewertet? nur [035a](https://github.com/ubtue/ub_tools/blob/68bbcee4457f3c649fd326b82d6763e9e0f8ddb7/cronjobs/generate_beacon_file.py)?

**Comment by socheres** [comment]
bevor ich nochmal teste, schränken wir die beacon auf personen gnd-ids.
personen in normdaten sind erkennbar an marc21-feld` 008 Pos. 32` mit feldinhalt "a" oder marc21-feld `079 $b` feldinhalt "p" @ruschein kannst du diese logik noch in dein skript einbauen.

**Comment by socheres** [comment]
im 008 Pos 31 also nach dem Pipe und Blank steht "aaa". Das sind Personen-Normdaten. Schalagwortnormdaten haben "ana".  
Dein Anhang:
`<controlfield tag="008">040525n||aznnnabbn           | aaa    |c</controlfield>`

Anderes Bsp. für Schlagwort "Trinitätslehre":
`<controlfield tag="008">900329n||azznnaabn           | ana    |c</controlfield>`
@ruschein bitte die Logik für beacon datei anpassen.

**Comment by socheres** [comment]
@ruschein in der BEACON sind weiterhin sehr viele Sachschlagwörter mit "ana" enthalten: 
4011882-4
4078704-7
4006406-2

**Comment by ruschein** [comment]
Jetzt sind sie hoffentlich weg.  Deine Beispiele sind jedenfalls nicht mehr erhalten.

**Comment by socheres** [comment]
@ruschein es sind noch 40590 IDs, die "ana" enthalten.

**Comment by ruschein** [comment]
@socheres Kannst Du mir bitte ein oder mehrere Beispiele auf Ptah geben?

**Comment by socheres** [comment]
@ruschein per email geschickt 😄

**Comment by socheres** [comment]
auf Ptah 🤔 scheint alles 👍  zu sein. 😀
