### ISSUE TITLE
Notationsschema: KDH Christliche Sondergemeinschaften fehlt

### ISSUE THREAD

**Issue by Gazeller** [ubtue/ixTheo#551]
Bei RelBib: KDH fehlt, Begriff "Christliche Sondergemeinschaften" ist im Schema alphabetisch aufgeführt.
![grafik](https://user-images.githubusercontent.com/16898788/28062842-836cc3be-662f-11e7-8155-aaaf3d0a884d.png)

Bei IxTheo fehlt die Notation komplett
![grafik](https://user-images.githubusercontent.com/16898788/28062872-9f62bc0e-662f-11e7-8de8-3041742063c3.png)

**Comment by IxTheoKm** [comment]
Die Notationsliste ist m.W. noch nicht abschließend bearbeitet/besprochen. Nach meinem letzten Stand gab es noch einige Detailfragen. Wenn die geklärt sind, sollten die Notationssätze nochmal vollständig neu geladen werden.

**Comment by ruschein** [comment]
@IxTheoKm Wurden die Detailfragen mittlerweile gelöst?

**Comment by relhei** [comment]
Abschlusstreffen zur Detailklärung steht noch aus. Rundmail mit Fragenliste ist abgeschickt.

**Comment by ruschein** [comment]
Gibt es da Neues?

**Comment by relhei** [comment]
Noch nicht: Abschlusstreffen steht noch aus. Ich schreibe eine weitere Rundmail.

**Comment by mtrojan-ub** [comment]
Habe per Zufall entdeckt dass @socheres im "alten" IxTheo-Repository etwas hinzugefügt hat:
https://github.com/ubtue/ixTheo/commit/75e403c1a04fbae7e849dbffd8554e74c2f3cd81

(die Änderung ist übrigens noch nicht auf ub16 live, vermutlich da von uns Entwicklern niemand bescheid wusste)

Ist das damit erledigt? Soll ich die Änderung(en) auch nach TueFind übernehmen?

**Comment by thefass** [comment]
ja bitte übernehmen

**Comment by thefass** [comment]
In RelBib gelöst.

**Comment by thefass** [comment]
Im IxTheo gibt es ein unterschiedliches Bild.
1) bei einer Gesamtsuche und danach beim Anzeigen der Notationen ist KDH enthalten
![bildschirmfoto 2018-02-09 um 22 00 37](https://user-images.githubusercontent.com/14169098/36049898-bbbc0560-0de4-11e8-856e-246bacde18d4.png)

2) In der erweiterten Suche fehlt jedoch KDH
![bildschirmfoto 2018-02-09 um 22 02 14](https://user-images.githubusercontent.com/14169098/36049948-eeb7029e-0de4-11e8-86e5-f340e7a119d0.png)

**Comment by mtrojan-ub** [comment]
Es lag an einem Limit das in VuFind per Standard aktiv war, da wurden nur die 100 häufigsten angezeigt. Das Limit haben wir nun deaktiviert.

**Comment by thefass** [comment]
auf Ptah in Ordnung
