### ISSUE TITLE
Bibelstellensuche: nicht funktionierende Abkürzungen

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#552]
3 Ezra/3 Ezr/3 Esra/3 Esd/1 Esdras
erwartbare Treffermenge: 19 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/477242278

4 Ezra/4 Ezr/4 Esra/4 Esd/2 Esdras
erwartbare Treffermenge: 91 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/468011064

5 Ezra/5 Ezr/5 Esra/5 Esd
erwartbare Treffermenge: 7 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/467445907

6 Ezra/6 Ezr/6 Esra/6 Esd
erwartbare Treffermenge: 3 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/475596846

3 Makk/3 Mac/3 Mcc/3 Ma/3 M
erwartbare Treffermenge: 13 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/478995431

4 Makk/4 Mac/4 Mcc/4 Ma/4 M
erwartbare Treffermenge: 37 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/423626078

6 Makk/6 Mac/6 Mcc/6 Ma/6 M
erwartbare Treffermenge: 1 Titel
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/382402162

Achtung: in allen Fällen wird die Bibelstelle nicht in 801 umgesetzt.

**Comment by ruschein** [comment]
@thefass Bitte testen.

**Comment by thefass** [comment]
Keines der obigen Bücher funktioniert.
Der Grund liegt vermutlich darin, dass dies keine kanonischen Bibelbücher sind, sondern apokryphe Schriften. Sie werden anderes umgesetzt.

Bibelbuch
689 | 0 | 0 | \|d u    \|0 (DE-588)1070007587    \|0 (DE-576)429678304    \|2 gnd    \|t Bibel    \|p Römerbrief    \|n 12,5

Apokryphes Buch
bei Ezra:
689 | 0 | 0 | \|d u    \|0 (DE-588)4153040-8    \|0 (DE-576)209800240    \|2 gnd    \|t Esra    \|n 3.
bei Makk:
689 | 0 | 0 | \|d u    \|0 (DE-588)4436440-4    \|0 (DE-576)212428160    \|2 gnd    \|t Makkabäer    \|9 g:Buch    \|n 3.

Bei den echten Bibelbüchern steht das Buch in |p, bei den Apokryphen in |t
bei Makk gibt es noch eine zusätzliche Kennzeichnung in |9g. 

Die Zählung bleibt konstant in |n

**Comment by thefass** [comment]
es funktioniert:
3 Ezra/3 Ezr/3 Esra/3 Esd/1 Esdras
4 Ezr/4 Esra/4 Esd/2 Esdras 
4 Esra 1-2 / 4 Ezr 1-2 /  4 Esd 1-2
4 Esra 15-16 / 4 Ezr 15-16 /  4 Esd 15-16
3 Makk/3 Mac/3 Mcc/3 Ma/3 M
4 Makk/4 Mac/4 Mcc/4 Ma/4 M
6 Makk/6 Mac/6 Mcc/6 Ma/6 M

es funktioniert nicht:
4 Ezra
4 Ezra funktioniert jetzt. MF 2018-01

----------------
4 Ezra 1-2
4 Ezra  1-2 funktioniert jetzt. MF 2018-01-09

es funktioniert noch nicht. MF2018-01-09:
5 Ezra/5 Ezr/5 Esra/5 Esd
diese Gruppe ist alles dasselbe (4 Ezra 1-2 = 5 Ezra)

----------------
4 Ezra 15-16
4 Ezra  15-16 funktioniert jetzt. MF 2018-01-09

es funktioniert noch nicht. MF2018-01-09:
6 Ezra/6 Ezr/6 Esra/6 Esd
diese Gruppe ist alles dasselbe (4 Ezra 15-16 = 6 Ezra)

**Comment by ruschein** [comment]
@thefass Kannst Du mir bitte PPNs von ein paar Beispielsdatensaetzen liefern die gefunden werden sollten?  Ich vermute, dass das Problem, nach meinen letzten Aenderungen, nicht bei der Suche sondern beim Erzeugen der Codes in der Pipeline liegt.  Um das zu Beheben benoetige ich Beispielsdatensaetze.

**Comment by ruschein** [comment]
@thefass Kommando zurueck.  Die Beispiele sind ja schon im Issue.

**Comment by ruschein** [comment]
Der Beispieltitelsatz für "5 Ezra/5 Ezr/5 Esra/5 Esd" hat keinen GND-Code!

**Comment by thefass** [comment]
Der Beispieldatensatz wurde mit GND nachkatalogisiert, das löst allerdings nicht das Problem.
die anderen Datensätze hatten nämlich eine GND, werden aber auch nicht gefunden.
5 Esra ist Verweisungform vom GND Normsatz 4. Esra 1-2
Siehe Normdatensatz
PICA
![bildschirmfoto 2018-01-09 um 21 26 58](https://user-images.githubusercontent.com/14169098/34741748-f9eb86fe-f583-11e7-9d21-f3b65bda83d4.png)

MARC
![bildschirmfoto 2018-01-09 um 21 27 32](https://user-images.githubusercontent.com/14169098/34741759-0495ef04-f584-11e7-83c6-4111ad7a6573.png)

**Comment by thefass** [comment]
Vielleicht kann das Problem gelöst werden, wenn noch folgende Verweisungsform aufgenommen wird:
430 Esra$n5.

**Comment by thefass** [comment]
dasselbe gilt für 6 Esra
![bildschirmfoto 2018-01-09 um 21 49 28](https://user-images.githubusercontent.com/14169098/34742605-04b7b550-f587-11e7-84d1-6706ce9892dd.png)

![bildschirmfoto 2018-01-09 um 21 50 51](https://user-images.githubusercontent.com/14169098/34742656-34ec1310-f587-11e7-9c0c-f0495a78554d.png)

Lösung?
Verweisungsform: 430 Esra$n6.

**Comment by thefass** [comment]
soweit ok, die nicht funktionierenden Teile des Issues wurden in einem neuen Issue unter Tuefind eröffnet: https://github.com/ubtue/tuefind/issues/410
