### ISSUE TITLE
Bibelstellensuche: seltsames Verhalten

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#554]
Bibelstellensuche nach einer fiktiven Stelle: Ps, 22.2.6.10

führt zu folgendem Ergebnis:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ps+22%2C2.6.10&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc

Auch wenn es die Stelle so nicht gibt, müßte doch das Ergebnis etwas mit Ps 22,2 ausgeben und nicht Stellen zu völlig anderen Bibelbüchern

**Comment by ruschein** [comment]
@thefass Welcher Treffer ist denn falsch?

**Comment by thefass** [comment]
Jetzt kommt das gewünschte Ergebnis. Ich kann den Fehler nicht mehr nachvollziehen und schließe das Issue.
