### ISSUE TITLE
Bibelstellensuche: Trenner Alternative ermöglichen

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#556]
Im Deutschen werden Verse vom Kapitel durch ein , getrennt
Bsp: Röm 11,1

Im Englischen ist der Trenner der Doppelpunkt (:)
Bsp: Rm 11:1

**Comment by ruschein** [comment]
@thefass Bitte testen.

**Comment by thefass** [comment]
Funktioniert
