### ISSUE TITLE
Nicht gelieferte Titel

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#566]
Zu lange Titelsätze wegen zu vieler Lokaldaten wurden in einer Sonderlieferung bereit gestellt.
Was ist mit neuen Zeitschriften, mit deren Auswertung danach begonnen wurde/wird? 
Oder mit anderen Dokumenten, die nach der Sonderlieferung mit den entspr. Selektionskriterien ausgezeichnet werden (z.B. e-books u.a.)
Dass sie nicht geliefert wurden, fällt eher zufällig auf.
Bsp.: PPN 103746927

Gibt es eine Möglichkeit, zumindest für übergeordnete Zeitschriftenaufnahmen herauszufinden, welche in der Datenbank fehlen?
Wie können Sonderabzüge dafür organisiert werden?

Vgl. auch #240

**Comment by IxTheoKm** [comment]
PPN 099211033 fehlt im IxTheo, in RelBib und auf ptah (zu viele Lokaldaten). Hat es nicht schon einen Komplett- bzw. Sonderabzug gegeben?

**Comment by thefass** [comment]
@ruschein und ich haben heute telefoniert und überlegt uns nur die Lokaldatensätze von 21* und Tü 135 liefern zu lassen. Die anderen Lokalsätze verwenden wir sowieso nicht und mußten erst wieder entfernt werden. Sich nur diese ausgewählten Lokalsätze liefern zu lassen ebtspricht auch dem KrimDok Verfahren. Damit wären Titelverluste aufgrund von zu vielen daran hängenden Lokaldaten auch dauerhaft vermieden. 
@ruschein : wann ist es soweit? bitte Bescheid sagen
@IxTheoKm : bitte die PPN dieses Issues nach Umstellung des Verfahrens testen

**Comment by IxTheoKm** [comment]
Das Verfahren wurde inzwischen umgestellt, oder? Die o.g. Titel sind jedenfalls inzwischen überall vorhanden.

**Comment by ruschein** [comment]
Ja, das Verfahren ist umgestellt.  Habe ich mir gerade eben nochmal angeschaut.
