### ISSUE TITLE
Katalog Browsen: IxTheo-Klassifikation > Nach Thema > Datensätze nicht anzeigbar

### ISSUE THREAD

**Issue by relhei** [ubtue/ixTheo#570]
Beim Katalog Browsen im IxTheo nach Auswahl der Kategorie "Nach Thema" führt Klick auf "Datensätze ansehen" ins Leere. Beispiel - Auswahl des Schlagwortes "Bibel, Altes Testament":
https://ixtheo-test.de/Search/Results?lookfor=&filter[]=topic_facet%3A%22Bibel+Altes+Testament%22&filter[]=ixtheo-classification%3A[*%20TO%20*]

**Comment by thefass** [comment]
das geht bei mir:
https://ixtheo-test.de/Search/Results?filter[]=topic_facet:Bibel+Altes+Testament

Sie haben noch einen zweiten Filter gesetzt. &filter[]=ixtheo-classification%3A[*%20TO%20*]
Liegt es daran?

**Comment by jriedl** [comment]
Reproduzierbar über Katalog Browsen / IxTheo-Klassifikation / Thema / Datensätze ansehen.
Ist auf ptah behoben.

**Comment by ruschein** [comment]
@relhei Bitte nochmal das Issue anschauen und, falls alles i.O. ist, zumachen, ansonsten bitte erläutern was noch nicht korrekt ist.
