### ISSUE TITLE
505t (Titel beigefügter Werke) fehlen in der Detailansicht

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/ixTheo#580]
Beispiel: Suche nach Titel "ethisch Abhandlung" führt u.A zu folgendem Treffer:

![grafik](https://user-images.githubusercontent.com/26873381/28561142-7cba7072-711d-11e7-9e3e-4a44f9e8e473.png)

In der Detailansicht taucht dies aber gar nicht mehr auf (PPN 008871833)

![grafik](https://user-images.githubusercontent.com/26873381/28561212-c01d9196-711d-11e7-8514-0385b35bc7b4.png)

Es handelt sich um zusätzliche Felder aus dem Feld 505 t

Wir werden voraussichtlich eine Änderung durchführen, um diese Untertitel in der Detailansicht direkt unterhalb des Titels einzublenden (in kleinerer Schrift).

**Comment by IxTheoKm** [comment]
Es handelt sich um beigefügte oder enthaltene Werke (Untertitel stehen in 245 $b).
Es können mehrere sein. 
Beispiel mit besonders vielen: 488808065
https://ixtheo-test.de/Record/488808065#details
Es sollte noch generell geklärt werden, wie viele wo angezeigt werden sollen.

**Comment by mtrojan-ub** [comment]
@IxTheoKm : bitte mal auf ptah anschauen:
https://ptah.ub.uni-tuebingen.de/Record/488808065

**Comment by IxTheoKm** [comment]
Ich finde, das sieht sehr gut aus.
Als Bezeichnung schlage ich die eher neutrale Formulierung "**Weitere Titel**" vor.
Die Bezeichnung "enthaltenes Werk" oder "beigefügtes Werk" ist veraltetet RAK-Terminologie, 
die Bezeichnung "Haupttitel von Teilwerken bei Zusammenstellungen" aus der Online-Hilfe für das PICA-Feld legt "Teilwerk" nahe, aber wer versteht das?

Außerdem inzwischen entdeckt:
"Weitere Titel" werden auch im Feld **249 $a** geliefert, wenn das Werk keinen übergeordneten Titel hat! Die müssen genauso behandelt werden (neues Issue: #588)
https://ptah.ub.uni-tuebingen.de/Record/489507530#details
https://ptah.ub.uni-tuebingen.de/Record/489501338#details

**Comment by mtrojan-ub** [comment]
Es gibt ja bereits ein anderes Feld namens "Other Titles" (zu Deutsch: "Nebentitel")

sollen die o.g. Titel dann lieber ins Feld Other Titles mit aufgenommen werden?
Denn wenn wir das neue Feld "Weitere Titel" nennen, passt die Zuordnung zum Englischen "Other Titles" nicht mehr.

**Comment by IxTheoKm** [comment]
Der "Nebentitel" ist i.d.R. nur eine andere Fassung und zusätzlicher Sucheinstieg für den Haupttitel, daher würde ich das nicht in dieses Feld mit aufnehmen.

Dann plädiere ich eher dafür, doch "Enthaltene Werke" zu nehmen. Das ist m.E. verständlich für Nutzer und passt zum englischen "Enclosed titles".
(Und die Unterscheidung zwischen enthaltenen und beigefügten Werken ist ohnehin nur eine bibliothekarische Spitzfindigkeit.)

**Comment by thefass** [comment]
Ich schließe mich @IxTheoKm an. Das drückt auch am besten den Sachverhalt aus

**Comment by IxTheoKm** [comment]
Auf ptah korrekt
