### ISSUE TITLE
Gedruckte Bücher mit Online-Kataloganreicherung werden als Open Access angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#586]
Durch relhei zufällig entdeckt:
Gedruckte Bücher werden in der Facette "Open Access" angezeigt, wenn Kataloganreicherungsmaterial (wie z.B. Inhaltsangabe, Inhaltstext, Klappentext, Rezension, Cover ...) als lizenzfreie Ressourcen verlinkt sind.

https://ixtheo-test.de/Search/Results?type=AllFields&filter%5B%5D=is_open_access%3A%22open-access%22&filter%5B%5D=%7Eformat%3A%22Book%22&filter%5B%5D=%7Emediatype%3A%22Non-Electronic%22

Problem: in MARC wird dasselbe Feld für die Auslieferung der Kataloganreicherungsdaten verwendet wie für die URL der elektronischen Ressource selber. 
M.E. dürften Sätze mit "Buch", "Nicht-elektronisch" nicht in Open Access auftauchen.
Problem: ein gedrucktes Buch soll wohl in die Facette "Elektronisch" und ggf. "Open access" einfließen, wenn das gedruckte Buch mit der lizenzfreien Online-Ausgabe verlinkt ist.

Es wäre also m.E. allenfalls möglich, Marc-Feld 856 $zkostenfrei _nicht_ für die Facette "open access" zu berücksichtigen, wenn in **856 $3 Begriffe der Kataloganreicherung** folgen: Inhaltsverzeichnis, Klappentext, Inhaltstext, Rezension, Cover ... (weitere Begriffe s. www.dnb.de/SharedDocs/Downloads/DE/DNB/wir/agVerbundKataloganreicherungsobjekte2010.pdf Seite 5; Ausnahme: "Volltext")

Leider erwischt man damit nicht alle Fälle, wie z.B.
856 ohne Unterfelder: 
https://ixtheo-test.de/Record/257445692#details
https://ixtheo-test.de/Record/286156229#details
...

856 $3 mit nicht-normierten/selteneren Begriffen: 
https://ixtheo-test.de/Record/251857379#details
https://ixtheo-test.de/Record/266425976#details
https://ixtheo-test.de/Record/348611064#details
https://ixtheo-test.de/Record/32295679X#details
https://ixtheo-test.de/Record/306169878#details
https://ixtheo-test.de/Record/273568027#details
...

**Comment by socheres** [comment]
wie ist die Regel jetzt für die Facette open access? welche Felder werden ausgewertet?
Wenn man folgende Regel anwendet, werden dort nur Elektronische + kostenfreie Volltexte angezeigt:
007 cr uuu---uuuuu + 856 $zkostenfrei

**Comment by socheres** [comment]
@IxTheoKm hat recht. Gedruckte Katalogisate haben auch viele Links, die zum Volltext führen. Daher muss noch eine Bedingung formuliert werden, wenn im Feld 856 |3 Begriffe wie 

> Inhaltsverzeichnis, Klappentext, Inhaltstext, Rezension, Cover ... (weitere Begriffe s. www.dnb.de/SharedDocs/Downloads/DE/DNB/wir/agVerbundKataloganreicherungsobjekte2010.pdf Seite 5; Ausnahme: "Volltext")

` /** @return "true" if we have an open access publication, else "false". */
    public String getOpenAccessStatus(final Record record) {
        for (final VariableField variableField : record.getVariableFields("856")) {
            final DataField dataField = (DataField) variableField;
            final Subfield subfieldZ = dataField.getSubfield('z');
            if (subfieldZ != null && subfieldZ.getData().toLowerCase().startsWith("kostenfrei") )
                return "open-access";
        }
        return "non-open-access";`
@ruschein ist es so ok?

**Comment by ruschein** [comment]
@socheres: Ja, ist Okay.  Meine neue Version ist hier: https://github.com/ubtue/ub_tools/blob/24c742c79a1d3aab9cb3f0602601dfcb3e94fc96/solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibMixin.java#L1761

**Comment by socheres** [comment]
@IxTheoKm können Sie bitte testen?

**Comment by ruschein** [comment]
Nach meiner neuesten Anpassung sank die Anzahl der als Open-Access ausgezeichneten Titel von 78.206 auf 74.690.

**Comment by Gazeller** [comment]
Immer noch große (unerklärliche) Diskerpanz - Test in RelBib - 
https://relbib.de/Search/Results?type=AllFields   --> open access= 2.379
Filter auf "Elektronisch"
https://relbib.de/Search/Results?type=AllFields&filter[]=~mediatype%3A"Electronic"  --> Open access=846

**Comment by ruschein** [comment]
Liebe Gabi,


die neue Version ist bisher erst auf Ptah installiert.


Viele Grüße,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

________________________________

**Comment by Gazeller** [comment]
Auf RelBib ptah geprüft: Zahl bei "open access" gesunken (1414)
https://134.2.67.9/Search/Results?type=AllFields
aber immer noch "gap" wenn man den Filter "elektronisch" setzt (847)
https://134.2.67.9/Search/Results?type=AllFields&filter[]=~mediatype%3A"Electronic"

**Comment by ruschein** [comment]
Die Verwirrung ensteht dadurch, dass es Datensätze gibt, welche nicht als elektronisch ausgezeichnet sind aber trotzdem mit den frei zugänglichen Volltexten verlinkt sind.  Z.B. https://relbib.de/Record/492435707
