### ISSUE TITLE
Nicht-relevante Titel

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#592]
Bei PPN 443312931 (medizinische Zeitschrift aus dem 18, Jahrhundert) ist nicht ersichtlich, warum der Titel im IxTheo gelandet ist. Ich finde kein Kriterium (082, 084, 935)

https://ixtheo-test.de/Record/443312931#details

Der Datensatz wurde 10-05-17 korrigiert. Kann es in einem älteren Stand ein relevantes Kriterium im Datensatz gegeben haben? Sonst gibt es evtl. einen Fehler in der SWB-Datenselektion

**Comment by ruschein** [comment]
Ist offensichtlich nicht mehr in IxTheo.
