### ISSUE TITLE
Titel mit DDC 290 fehlen in RelBib

### ISSUE THREAD

**Issue by Gazeller** [ubtue/ixTheo#594]
Problem tauchte bereits früher auf, jetzt wieder aktuell ein Titel, der von Autorin gemeldet wurde:

0100 48878705X
0500 Aan
0501 Text$btxt
0502 ohne Hilfsmittel zu benutzen$bn
0503 Band$bnc
0575 mteo
0600 sf
1100 2016$n[2016]
1130 druck
1500 ger
1505 $erda
1700 XA-DE-HE
2000 978-3-8288-3706-5$fBroschur : EUR 24.95 (AT), EUR 24.95 (DE)
2000 3-8288-3706-9
2065 109844244X
2100 16,N19
2105 16,A20
2201 9783828837065
2240 BSZ: 48878705X
3000 Borse, Romina Alexandra$71100084878$BVerfasserIn$4aut
3010 !169003817!Schmitz, Bertram$BHerausgeberIn$4edt
4000 Islam in Japan$dein Forschungsaufenthalt in Tokio$hvon Romina Alexandra Borse
4030 Marburg$nTectum Verlag
4060 143 Seiten
4061 Illustrationen
4062 21 cm, 222 g
4089 $mB:DE-101$qapplication/pdf$uhttp://d-nb.info/109844244X/04$3Inhaltsverzeichnis
4170 Religionen aktuell ; Band 20
4180 $72403082X$lBand 20
5051 290
5100 !208977503!Japan
5101 !20897220X!Islam
5110 !209208309!Tokio
5111 !209042680!Muslim
5112 !20911262X!Situation
5400 [DDC22ger]297.0952
5401 297.09

Was kann da los sein?

**Comment by jriedl** [comment]
Kriterien für die Aufnahme wurden angepasst. Grundsätzlich werden jetzt alle Titel mit DDC aufgenommen, außer 220-289 und solche, die ausschließlich 400er oder 800er Notationen haben.

**Comment by ruschein** [comment]
@Gazeller Bitte nochmal das Issue anschauen und, falls alles i.O. ist, zumachen, ansonsten bitte erläutern was noch nicht korrekt ist.
