### ISSUE TITLE
Thema browsen: alternative Benennungen sind nicht berücksichtigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#608]
Wer über "Thema browsen" sucht, muss die Vorzugsbenennung der normierten Schlagwörter aus Feld 150 kennen. Wer nach einer Verweisung aus 450 sucht, geht leer aus.
Oder bekommt nur Titel, in denen zufällig der Verweisungsbegriff als nicht-normiertes Schlagwort erfasst ist. Das führt in die Irre (siehe vor allem die Beispiele "Sühnetod" und "Mullah")

Bsp.:
150 $a**Nephilim**
450 $aNefilim
450 $aNaphil
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=nephilim&type=KeywordChainSearch
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=nefilim&type=KeywordChainSearch
...

150 $a**Sühneopfer**
450 $aSühnetod
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=s%C3%BChneopfer&type=KeywordChainSearch
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=s%C3%BChnetod&type=KeywordChainSearch

150 $a**Molla**
450 $aMulla
450 $aMullah
450 $aMollah
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=molla&type=KeywordChainSearch
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=mullah&type=KeywordChainSearch
...

150 $a**Nusairier**
450 $aAlawiten
450 $aAlauiten
450 $aNossairier
450 $aNosseirier
450 $aNụsairī
450 $aNuṣayriyya
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=nusairier&type=KeywordChainSearch
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=alawiten&type=KeywordChainSearch
...

150 $a**Aleviten**
450 $aAlewiten
450 $aAlevis
450 $aAlewis
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=aleviten&type=KeywordChainSearch
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=alewiten&type=KeywordChainSearch
...

**Comment by jriedl** [comment]
Die Schlagwortfolgensuche basiert auf der Textähnlichkeit zu den gegebenen Begriffen einer Schlagwortfolge und damit auf den tatsächlich in der Volltitelanzeige angegebenen normierten und nicht-normierten Schlagwörtern. Synonyme lassen sich (anders als bei der Suche nach Schlagwörtern direkt) in diesem Ansatz nur einbeziehen, wenn man die entsprechenden Titel damit verschlagwortet.

**Comment by IxTheoKm** [comment]
Danke für die Erklärung.
Das ist dann ein Aspekt für einen Hilfetext zu "Thema browsen". 
Ich habe es in die Datei für die Hilfetext-Ideensammlung eingetragen.
