### ISSUE TITLE
SW Folge in Browsing gedoppelt

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#61]
Wenn man untenstehende Suche macht, findet man die SW Folge "Traditionalismus / Katholische Kirche" zweimal: einmal mit 2 Titeln, einmal mit 6 Titeln. Egal auf welche der beiden SW Folgen man dann klickt, bekommt man immer richtigerweise 8 Titel angezeigt:

http://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Results?lookfor=%22Traditionalismus%22&type=keywordChainSearch

Hat jemand Ahnung, warum das so ist?

**Comment by jriedl** [comment]
@thefass Die Schlagwortketten werden jetzt korrekterweise zusammengefasst. Problem war dass es sich ursprünglich in den Daten um zwei unterschiedliche Ketten gehandelt hat ("Traditionalismus / Katholische Kirche" und "Katholische Kirche / Traditionalismus")

**Comment by thefass** [comment]
Erledigt. Danke. Closed
