### ISSUE TITLE
Elektronische Publikationen werden als "Nicht-elektronisch" angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#616]
Zwei Beiträge der DeGruyter-Datenlieferung mit Abrufzeichen "gruy" werden als Nicht-elektronisch angezeigt, obwohl alle gelieferten DeGruyter-Daten für elektronische Ausgaben vorliegen.
Ähnlich bei drei Beiträgen von Brill.

https://www.ixtheo.de/Search/Results?lookfor=rs%3Agruy&type=AllFields&filter%5B%5D=%7Emediatype%3A%22Non-Electronic%22
https://www.ixtheo.de/Search/Results?lookfor=rs%3Abril&type=AllFields&filter%5B%5D=%7Emediatype%3A%22Non-Electronic%22

Ursache: in diesen alten RAK-Daten wurde nach dem Titel "Elektronische Ressource" nicht erfasst, es fehlt also **245 $h**Elektronische Ressource, die Reihenfolge der Unterfelder wurde vertauscht, oder die Angaben von RAK-WB- und RDA-Aufnahmen wurden vermischt.
 [habe heute korrigiert]
Mit der SWB-GBV-Kooperation wird 245 $h später gelöscht bzw. durch die Codierungen in 338 ersetzt!

Es gibt aber in den Datensätzen weitere Kriterien, die für die Anzeige als elektronische Publikation herangezogen werden können:

**935 $bcofz** [wird mit SWB-GBV-Kooperation ersetzt durch "Online-Ressource" in 338]

**300 $aOnline-Ressource** [in den alten RAK-Daten, also mit 040 $erakwb bzw. ohne 040 $erda]

**Comment by IxTheoKm** [comment]
In RDA-Aufnahmen ist _nie_ 245 $hElektronische Ressource vorhanden!

Bei o.g. Beispielen werden diese folgenden Brill-Titel als nicht-elektronisch angezeigt:
https://www.ixtheo.de/Record/49112032X#details
https://www.ixtheo.de/Record/491121725#details

Diese RDA-Aufnahmen enthalten nur
338 $aOnline-Ressource
935 $bcofz

Weitere Beispiele:
https://www.ixtheo.de/Search/Results?lookfor=superior_ppn:325341478
https://www.ixtheo.de/Search/Results?lookfor=superior_ppn:361845626
...
Offensichtlich wird auch bei RDA-Aufnahmen nur nach 245 $h gesucht.

**Comment by ruschein** [comment]
Langt in diesen Fällen die Auswertung von 935$b?



Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

________________________________

**Comment by IxTheoKm** [comment]
Momentan reicht 935 $b 
(für elektronische Ressourcen gibt es lt. Formatdokumentatin derzeit die Codes 
"cofz" = Online-Ressource, 
"disk" = Diskette, 
"crom" = CD-ROM, 
"dvdr" = DVD-ROM, 
"soerd" = Sonstige elektronische Ressource auf Datenträger)

Mit der Umstellung auf K10plus ist aber geplant, diese Codes zu löschen.
Dann gibt es nur noch 338 $a.
Ist es dann nicht sinnvoller, dies auch gleich mit zu berücksichtigen?

Computerchip-Cartridge | cb
Computerdisk | cd
Computerdisk-Cartridge | ce
Magnetbandcartridge | ca
Magnetbandkassette | cf
Magnetbandspule | ch
Online-Ressource | cr
Speicherkarte | ck
sonstige | cz

**Comment by ruschein** [comment]
<quote>Ist es dann nicht sinnvoller, dies auch gleich mit zu berücksichtigen?</quote>

Ja, sehe ich auch so und habe es auch so implementiert.  On das funktioniert hat werden wir frühestens morgen auf Path sehen.

**Comment by IxTheoKm** [comment]
Auf ptah jetzt o.k.
