### ISSUE TITLE
Zitieren: Aufsätze aus Zs und Sammelwerken unvollständig zititert

### ISSUE THREAD

**Issue by relhei** [ubtue/ixTheo#618]
Beim Zitieren von Aufsätzen (aus Zs oder Sammelwerken) werden diese bei Auswahl der Funktion "Zitieren" in allen drei Zitierstilen falsch als Monografien zitiert.

![grafik](https://user-images.githubusercontent.com/25769591/30861817-389d76ba-a2cc-11e7-9e2c-b9f9977f1dcf.png)

Zu den Zitierrichtlinien für APA, MLA und Chicago samt Beispielen: www.bibme.org

**Comment by jriedl** [comment]
Aktuelle Version findet sich auf ptah.

**Comment by relhei** [comment]
Passt noch nicht ganz:
![grafik](https://user-images.githubusercontent.com/25769591/31377263-bf433d2c-ada7-11e7-891f-4c6a4b738bd9.png)

Bei APA style wird vor den Seitenzahlen kein "pp." angegeben:
![grafik](https://user-images.githubusercontent.com/25769591/31377430-4f956a4e-ada8-11e7-8296-1139d5150559.png)

Bei MLA style fehlen noch mehr Angaben, hier ein Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/31377878-d57fc14e-ada9-11e7-8404-a38ed74ed8aa.png)

Bei Chicago style fehlen noch Bandangabe, URL und Zugriffsdatum:
http://www.bibme.org/citation-guide/chicago/journal-article/

**Comment by relhei** [comment]
**APA**: ist o.k.

**Chicago**: nach der Jahresangabe in Klammern folgt Doppelpunkt Leerzeichen Seitenangaben (ohne pp.)

Bsp. Romero López, Dolores. "El Transfondo Ocultista Del Cuervo: Desde Su Simbolismo Poético a Los Topoi Modernistas = The Occultist Background of the Raven : From Its Poetic Symbolism to the Modernist Topoi." Ílu 18 (2013): 201-218. doi:10.5209/rev_ILUR.2013.v18.43048

**MLA**: nach Zeitschriftenname folgt Komma Leerzeichen vol. 

Bsp. Romero López, Dolores. "El Transfondo Ocultista Del Cuervo: Desde Su Simbolismo Poético a Los Topoi Modernistas = The Occultist Background of the Raven : From Its Poetic Symbolism to the Modernist Topoi." Ílu, vol. 18, 2013, pp. 201-218. doi:10.5209/rev_ILUR.2013.v18.43048

**Comment by jriedl** [comment]
Auf ptah integriert

**Comment by relhei** [comment]
Passt - vielen Dank!
