### ISSUE TITLE
Medienart: Weblog?

### ISSUE THREAD

**Issue by relhei** [ubtue/ixTheo#619]
Bisher sind zwei Weblogs in RelBib, deren Zahl allerdings zunehmen wird. Bisher laufen Weblogs unter "Medienart: Zeitschrift (elektronisch)". Die Information "Weblog" stammt aus dem Marc-Feld 655 und wird zur Zeit im Volltitel als "weiteres Schlagwort" angezeigt. Wäre es möglich, Weblog als weitere anwählbare Medienart einzufügen?
![grafik](https://user-images.githubusercontent.com/25769591/30958104-6cc86f28-a43c-11e7-9102-ce486b94b6ef.png)

**Comment by relhei** [comment]
Daran schließt sich eine weitere Frage: In der Facette "Thema (Schlagwort)" landen bisher auch die formalen Schlagwörter (v. a. "Aufsatzsammlung"), sofern es sich beim Titel noch nicht um eine RDA-Aufnahme handelt. Ist das so gewollt? Sensu stricto gehören die ja nicht dahin (sondern zu "Genre / Schlagwort") und sind vielleicht auch für den Nutzer irreführend? 
Bsp.:
![grafik](https://user-images.githubusercontent.com/25769591/30958599-f49841ac-a43d-11e7-9b6c-9bbc9fe40726.png)

![grafik](https://user-images.githubusercontent.com/25769591/30958563-de9c2ea4-a43d-11e7-9412-005f18c4bf45.png)

**Comment by jriedl** [comment]
Es werden beim Import bereits einige elektronische Medienarten gesondert erfasst, dies erfolgt durch Auswertung des Feldes 935$c (z.B. für Websites und Datenbanken). Für die beiden erwähnten Blogs steht hier "cofz". Falls sich hier klären lässt, was das genau umfasst bzw. wie es aufgelöst wird, ließe sich eventuell dieses Kriterium verwenden, ohne auf das Schlagwortfeld 655 zurückfallen zu müssen.

**Comment by jriedl** [comment]
Für die Genre-Facette werden derzeit die Felder 600v:610v:611v:630v:648v:650v:651v:655a:655v ausgewertet, wobei es scheint, dass hier insbesondere das Feld 655a relevant ist. In den thematischen Schlagwörtern landet "Aufsatzsammlung", da es in den 689-Feldern Teil einer Schlagwortfolge ist. Eine thematische Differenzierung innerhalb der Schlagwortfolgen erfolgt derzeit nicht, hier wäre zu klären, ob das gewünscht ist.

**Comment by IxTheoKm** [comment]
"cofz" steht allgemein für "Online-Ressource, Elektronische Ressource im Fernzugriff" und differenziert nicht

**Comment by jriedl** [comment]
Ist auf ptah integriert. Momentane Bezeichnung "Blog", ab dem nächsten Import morgen "Weblog" um konsistent mit dem Genre-Schlagwort zu bleiben.

**Comment by relhei** [comment]
@ 1. Hab getestet: funktioniert auf ptah!
@ 2. Wäre Folgendes möglich: "Aufsatzsammlung" in Feld 689 trägt den Zusatz |q f (für Formschlagwort) - könnte man die Formschlagwörter aufgrund dieses Zusatzes, der sie von den "normalen" Thema-Schlagwörtern unterscheidet, auslesen und unter "Genre (Schlagwort)" eingruppieren?

**Comment by socheres** [comment]
zu@2: ja, das ist eindeutiges Merkmal "|f". Alle Formschlagwörter sollen unter "Genre" indexiert werden. 
Feld 689 |f [...] = Facette Genre

**Comment by jriedl** [comment]
689$q == f tauchen mittlerweile auf ptah in der Genre-Facette auf.

**Comment by socheres** [comment]
es sind noch 47.328 Treffer mit Formschlagwort "Aufsatzsammlung" in der Facette Thema(Schlagwort) zu finden. https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter%5B%5D=topic_facet%3A%22Aufsatzsammlung%22

**Comment by jriedl** [comment]
Ja, 689$abctnp fließt grundsätzlich  in "Thema (Schlagwort)" ein, gesamt sind das derzeit 600x:610x:611x:630x:648x:650a:650x:651x:655x:689abctnp. Insbesondere gibt es viele Titel, die "Aufsatzsammlung" in 655 haben.

**Comment by thefass** [comment]
Für die Problematik der Schlagwortfacetten soll es ja ein eigenes Issue geben.
Das Problem der Facette Weblog ist fast abgeschlossen. Es fehlt allerdings noch die Facette Weblog in der Erweiterten Suche im Ixtheo und Relbib

https://relbib.de/Search/Advanced

**Comment by relhei** [comment]
Weblog nun auch in der Medienart-Facette in Erweiterte Suche vorhanden. Danke!
