### ISSUE TITLE
Schlagwortfolgen durchstöbern

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#62]
Klickt man auf "Schlagwortfolgen durchstöbern", so erscheint keine Übersicht über die vorhandenen Schlagworte (http://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Home).
Eine solche Übersicht könnte wichtig sein, um einen Überblick zu erhalten, welche Schlagworte vorhanden sind.

**Comment by socheres** [comment]
auf der ersten Seite vom "Schlagwortfolgen durchstöbern" soll eine alphabetische liste analog zum "Thema durchstöbern" http://ptah.ub.uni-tuebingen.de/Browse/Topic?findby=alphabetical&category=&query=A%2A&facet_prefix=A&query_field=topic_facet&facet_field=topic_facet
angezeigt werden.

**Comment by Mannsperger** [comment]
Bislang wird mir auch über "Alphabetisch durchstöbern" noch keine Liste angezeigt. 
Und sowohl wenn man das Auswahlfeld freilässt, als auch wenn man ein Wort eingibt (ich habe es mit Apartheid, Kant, Jesus) bei nach Thema suchen versucht, erscheint folgende Fehlermeldung:
![alphabetisch stobern - thema](https://cloud.githubusercontent.com/assets/16759964/12507421/0c151fda-c0f6-11e5-8f61-339e026e5ff3.png)

**Comment by jriedl** [comment]
Ein automatisches Anzeigen des Anfangs könnte nicht anhand der Präfixsortierung erfolgen, da keine Suchterme existieren und würde eigentlich immer die gleichen Einträge anzeigen. Um relativ große Ergebnismengen als Überblick zurückzubekommen, könnte man z.B. eine Suche nach dem Anfangsbuchstaben ausführen (z.B. im Suchfeld "T*" - ohne Anführungszeichen - für alle Terme, die mit T anfangen) eingeben.
