### ISSUE TITLE
"Gefeierte" in der Facette "Verfasser"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#629]
Bei Festschriften und Nachrufen tauchen die gefeierten Personen in der Facette für Verfasser auf 
(das ist insbesondere bei Verstorbenen etwas makaber).
Bsp.:
https://www.ixtheo.de/Record/489119662#details
https://www.ixtheo.de/Record/412054027#details

**700 $eGefeierteR..._$4hnr_**                  bzw. 
**700 _$4hnr_** (bei RAK-Aufnahmen)     
sollte in der Facette "Thema ..." auftauchen.

Manchmal ist die Person - wie in den o.g. Beispielen - durch Erfassung als Schlagwort schon in der Facette "Thema ..." abgelegt, aber das ist nicht immer der Fall (vor allem nicht bei Festschriften).

**Comment by ruschein** [comment]
Sollte jetzt auf Ptah wie gewünscht funktionieren.

**Comment by IxTheoKm** [comment]
Die beiden Personen tauchen immer noch als Verfasser auf

**Comment by ruschein** [comment]
Auf Path?


--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

________________________________

**Comment by IxTheoKm** [comment]
Ja:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=+Von+der+Diakonisse+zur+Benediktinerin&type=AllFields
https://www.ixtheo.de/Search/Results?lookfor=Der+Liebe+Gottes+in+Jesus+Christus+begegnen&type=AllFields

**Comment by thefass** [comment]
auf ptah ist das m.E. in Ordnung:
1. Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A489119662&type=AllFields&limit=20&sort=year+desc%2C+issue+desc%2C+start_page+asc
2. Beispiel: 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A412054027&type=AllFields&limit=20&sort=year+desc%2C+issue+desc%2C+start_page+asc
@IxTheoKm : bitte nochmal prüfen

**Comment by IxTheoKm** [comment]
Die verstorbenen gefeierten Personen Abrahamsson und Bar stehen immer noch in der Facette Verfasser. Also noch nicht in Ordnung.

**Comment by ruschein** [comment]
@IxTheoKm Scheint behoben.

**Comment by IxTheoKm** [comment]
Tut mir leid, die beiden Damen firmieren immer noch zusätzlich als Verfasser:

![gefeierte](https://user-images.githubusercontent.com/17004223/33619824-76fae036-d9e6-11e7-86d8-718b0095ab69.png)

![gefeierte2](https://user-images.githubusercontent.com/17004223/33619845-81a8d876-d9e6-11e7-81c3-15291dfcf2d0.png)

**Comment by ruschein** [comment]
Ich vermute das ist jetzt auf Ptah wie gewünscht.

**Comment by IxTheoKm** [comment]
Funktioniert jetzt auf Ptah
