### ISSUE TITLE
Suchoption "Semesterapparat"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#63]
Wenn ich die Suchoption "Semesterapparat" anklicke, erscheint folgende Fehlermeldung:
![semesterapparat - fehleranzeige](https://cloud.githubusercontent.com/assets/16759964/12507518/906cd50c-c0f6-11e5-8f29-6720e2dd3ab5.png)
(s. http://ptah.ub.uni-tuebingen.de/Search/Reserves)

**Comment by socheres** [comment]
bitte alle unergiebige Funktionalitäten, die wir zurzeit noch nicht benötigen, ausblenden.

**Comment by oobenland** [comment]
Ich habe den Semesterapparat entfernt, da er für IxTheo keinen Sinn macht. (Wird demnächst auf ptah eingespielt.)
