### ISSUE TITLE
Sortierung innerhalb eines Jahrganges

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#633]
Die Sortierung innerhalb eines Jahrganges nach "Neueste zuerst" stimmt nicht.
Wenn es 12 Hefte gibt, dann ist so sortiert 9-1,12,11,10
Es müßte aber absteigend so sein: 12-1
https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A014498685&type=AllFields&filter%5B%5D=publishDate%3A%22%5B2016+TO+2016%5D%22

**Comment by jriedl** [comment]
Integriert auf ptah

**Comment by thefass** [comment]
auf ptah ok.
