### ISSUE TITLE
Felder ohne Anzeige/Weiterleitung

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#64]
Wenn ich auf "Fachauskunft der Bibliothek" oder "Häufig gestellte Fragen" klicke unter der Rubrik "Hilfe", so verändert sich nichts, die vorherige Auswahl wird weiterhin angezeigt. Es erfolgt also keine Weiterleitung, z.B. zur Fachauskunft der Bibliothek.

**Comment by oobenland** [comment]
Das sind Platzhalter, die wir noch nicht belegt haben.
@thefass @socheres werden diese Links noch belegt, oder soll ich die Links aus dem Footer entfernen?

**Comment by thefass** [comment]
Fachauskunft kann entfernt werden.

Häufig gestellte Fragen sollte als Platzhalter bleiben. Die kommen schon noch, wenn viele damit arbeiten :-)
@oobenland: kannst Du bitte den Link mit einer Seite "under construction" belegen. Dann wissen alle, die zukünftig darauf klicken, dass hier noch eine Baustelle ist.

**Comment by oobenland** [comment]
So, Fachauskunft ist entfernt und für die FAQ's gibt es jetzt einen .... ähm... Platzhalter ;-)
