### ISSUE TITLE
Medienart Lexikonartikel

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#640]
Bitte Datensätze mit 935 $a**uwlx** in der Facette Medienart als "Lexikonartikel" anzeigen.

Beispiel:
https://www.ixtheo.de/Record/493323570#details

**Comment by ruschein** [comment]
935$a ist ein seltsames Unterfeld.  Da stehen viele seltsame Codes drin:

a001
a002
a003
a007
a008
a009
bema
BGTS
BIDL
BIST
CICO
IFBR
INKA
leos
lzar
mkri
mteo
mtex
PAHA
PALA
SAXB
uwlx
uwzd
vona
WABU
zkor

Welche von diesen sind jetzt Medienarten und was bedeuten die?

**Comment by IxTheoKm** [comment]
Es ist ein Feld für Abrufzeichen unterschiedlichster Art, die z.T. auch nur lokale Bedeutung haben. Eine vollständige Liste findet sich hier: http://swbtools.bsz-bw.de/winibwhelp/Liste_0575.pdf
Nur uwlx ist relevant als Medienart

**Comment by IxTheoKm** [comment]
Ist noch nicht ganz o.k.: die Sätze werden nun sowohl als Aufsatz als auch als Lexikonartikel angezeigt.
Aufsatz muss entfallen.
Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:024070599

**Comment by IxTheoKm** [comment]
Ist jetzt okay. Siehe https://github.com/ubtue/tuefind/issues/408
