### ISSUE TITLE
Unterfeld $z im Schlagwort

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#641]
Das Unterfeld $z im Schlagwort Feld 689 wird nicht angezeigt und ist nicht recherchierbar.
In Feld 651 erfolgt die Anzeige ohne Klammern.
Bitte indexieren und die Anzeige des Schlagworts anpassen.

Beispiele:

https://www.ixtheo.de/Record/485955423#details
**689** 00$Dg$0(DE-588)4026754-4$0(DE-576)208967796$2gnd$a**Indien$zSüd**

https://www.ixtheo.de/Record/465754775#details
**651** 7$0(DE-588)4026754-4$0(DE-576)208967796$2gnd$a**Indien$zSüd**

Anzeige des Schlagworts muss lauten: **Indien (Süd)**

https://www.ixtheo.de/Record/116653442#details
**689** 00$Dg$0(DE-588)4072768-3$0(DE-576)20918812X$2gnd$a**Indien$zNord**

https://www.ixtheo.de/Record/466296975#details
**651** 7$0(DE-588)4072768-3$0(DE-576)20918812X$2gnd$a**Indien$zNord**

Anzeige des Schlagworts muss lauten: **Indien (Nord)**

**Comment by IxTheoKm** [comment]
Funktioniert jetzt. 

Allerdings ist bei PPNH 466296975 das Schlagwort "Indien (Nord)" in der Facette Region (Schlagwort) aufgeteilt in zwei Schlagwörter "Indien" und "Nord". Bei PPN 465754775 in "Indien" und "Süd"
Bei PPN 116653442 und 485955423 ist es korrekt.

**Comment by jriedl** [comment]
Ist für die beiden o.g. Datensätze auf ptah gefixt, für alle anderen im Rahmen des nächsten Imports.

**Comment by IxTheoKm** [comment]
Welche beiden Datensätze sind gemeint? Und wann ist der nächste Import?

Auf ptah ist das Schlagwort in der Facette "Region (Schlagwort)" immer noch auseinander gerissen.

Zudem kommt unter der Facette "Thema (Schlagwort)" nur _Indien_ ohne _Nord_.

Bsp.: 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=heart+ritual+body&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by IxTheoKm** [comment]
Facette "Region (Schlagwort)" ist jetzt o.k. 
Bei "Thema (Schlagwort)" steht weiterhin nur _Indien_ ohne Nord.

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=heart+of+ritual+is+the+body+anatomy&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by thefass** [comment]
ist ok
