### ISSUE TITLE
Facette Thema wird nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#648]
Auf ptah gibt es keine Facette Thema mehr beim Einzeltreffer:
![in](https://user-images.githubusercontent.com/17004223/32732137-fd2baf08-c88b-11e7-96db-ec2fa028fef3.png)

In IxTheo wurden sie noch angezeigt:
![in2](https://user-images.githubusercontent.com/17004223/32732267-4a72d39a-c88c-11e7-91d6-59ab8f48d144.png)

**Comment by jriedl** [comment]
Import abgeschlossen. Wird wieder angezeigt.

**Comment by IxTheoKm** [comment]
o.k.
