### ISSUE TITLE
Katalog durchstöbern - englische Angaben

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#65]
Klickt man bei "Katalog durchstöbern" auf Verfasser, so erscheinen zwei Angaben  auf englisch (by Publisher, by ixTheo Notation):
![verfasser publisher](https://cloud.githubusercontent.com/assets/16759964/12553174/2b2d96fe-c376-11e5-8f3d-3b14678e3924.png)

Unter Verlag erscheint wieder "By ixTheo Notation".
(http://ptah.ub.uni-tuebingen.de/Browse/Publisher)

Und unter der Kategorie "IxTheo Notation" erscheint wieder "By Publisher"
(http://ptah.ub.uni-tuebingen.de/Browse/ixtheo-notation)

**Comment by Mannsperger** [comment]
Und wenn ich unter einer der Kategorien "Verfasser, Verlag, IxTheo Notation" "nach Thema" auswähle, so verändern sich die Begriffe in ihrer Sprache nicht, wenn ich eine andere Sprache auswähle, sie sind deutsch und englisch gemischt:
![englische thema auswahl](https://cloud.githubusercontent.com/assets/16759964/12553410/875bb310-c377-11e5-99fe-28243eba6bfb.png)

**Comment by ruschein** [comment]
On 25/01/16 15:23, Mannsperger wrote:
>
> Und wenn ich unter einer der Kategorien "Verfasser, Verlag, IxTheo
> Notation" "nach Thema" auswähle, so verändern sich die Begriffe in
> ihrer Sprache nicht, wenn ich eine andere Sprache auswähle, sie sind
> deutsch und englisch gemischt:
>
Ich denke, die Begriffe kommen aus den Metadaten und sind dort bunt
gemischt.
>
> englische thema auswahl
> <https://cloud.githubusercontent.com/assets/16759964/12553410/875bb310-c377-11e5-99fe-28243eba6bfb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/65#issuecomment-174521732>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by ruschein** [comment]
Behoben.

On 25/01/16 15:13, Mannsperger wrote:
>
> Klickt man bei "Katalog durchstöbern" auf Verfasser, so erscheinen
> zwei Angaben auf englisch (by Publisher, by IxTheo Notation):
> verfasser publisher
> <https://camo.githubusercontent.com/cddfb3f7d1a9f9c9788cd040758f80ed43fbe38c/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31363735393936342f31323535333137342f32623264393666652d633337362d313165352d386633642d336231343637386533393234706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/65>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de
