### ISSUE TITLE
solr/vendor/ in .gitignore

### ISSUE THREAD

**Issue by bsesic** [ubtue/ixTheo#651]
Das Verzeichnis `solr/vendor` ist in der .gitignore und kann nicht ausgecheckt werden. Das Problem ist, dass es nach `git pull origin master` fehlt und solr nicht gestartet werden kann.

**Comment by mtrojan-ub** [comment]
solr ist eine 3rd party software die nach dem Herunterladen über composer installiert werden muss, genau wie das Zend Framework und weitere Abhängigkeiten. 

`composer update`

Übrigens: Das war früher anders, wurde aber mit Vufind 4 geändert (von Demian Katz)

![grafik](https://user-images.githubusercontent.com/26873381/34487326-28841e96-efd4-11e7-8485-5374352bd5db.png)
