### ISSUE TITLE
Fehlende Telefonnetz-Anbieter bei SMS versenden

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#66]
Die Auswahlfunktionen des Kontos funktionieren einwandfrei.
Auch die Funktionen „Zitieren“, „Auswahl per Email versenden“, „Datensatz exportieren“ funktionieren.
 
Unter der Auswahl „Per SMS versenden“ werden nicht alle Telefonnetz-Anbieter angezeigt, die es gibt.
![telefonfunktion](https://cloud.githubusercontent.com/assets/16759964/12553783/916f9c3e-c379-11e5-8457-7fb40a3aa24c.png)

**Comment by oobenland** [comment]
Ich glaube die größere Problematik bei diesem Dienst ist, dass er nicht funktioniert... Das ganze funktioniert über EMail-To-SMS. Dafür gibt es online [Listen](http://martinfitzpatrick.name/list-of-email-to-sms-gateways/). Jedoch gibt es je nach Anbieter bestimmte Voraussetzungen, damit das funktioniert (z.b.: Freischaltung, Anmeldung, sonstiges) und man muss je nach Anbieter die Telefonnummer anders angeben...
Somit ist es aus meiner Sicht recht schwierig solch einen Dienst fehlerfrei anzubieten.
@thefass Wie sollen wir damit umgehen?

**Comment by thefass** [comment]
das sollten wir rausnehmen. Ist zu kompliziert

**Comment by oobenland** [comment]
Ist deaktiviert.
