### ISSUE TITLE
Fehlende Übersetzungen

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#67]
Wie man dem Screenshot entnehmen kann, tauchen noch folgende Begriffe auf deutsch auf, die möglicherweise in den anderen Sprachen angezeigt werden könnten:
![deutsch in anderen sprachen](https://cloud.githubusercontent.com/assets/16759964/12553907/3e2c0bc4-c37a-11e5-8e24-671804fa5746.png)
Die Bezeichnung "Schlagwortfolgen" erscheint in allen Sprachen außer deutsch als "Keyword Chains", es fehlt also eine französische, spanische, italienische und chinesische Übersetzung:
![keyword chains](https://cloud.githubusercontent.com/assets/16759964/12553978/9e269c56-c37a-11e5-8e4a-4964e4bfa304.png)

**Comment by oobenland** [comment]
Könntest du in diesem Issue die fehlenden Übersetzungen per Kommentar erweitern? Ich glaube, dass für die Korrektur nur das Wort und die Sprachen, für die es keine Übersetzung gibt, wichtig sind, aber nicht wo auf der Webseite es auftritt.

**Comment by oobenland** [comment]
Meine Favorieten
Inhaltsverzeichnis
Keyword Chains

**Comment by Mannsperger** [comment]
Die Übersetzungen für "Inhaltsverzeichnis" und "Meine Favoriten" in allen anderen Sprachen

**Comment by Mannsperger** [comment]
für "Schlagwortfolgen" fehlt die Übersetzung ins französische, italienische, spanische, chinesische (die englische Übersetzung ist vorhanden)

**Comment by Mannsperger** [comment]
Auf der "Home"-Seite in englischer Sprache (https://www.ixtheo-test.de/#) sind folgende Felder noch nicht übersetzt:
![obere leiste](https://cloud.githubusercontent.com/assets/16759964/15959325/8c531b26-2efa-11e6-935e-e0916b14e547.png)

**Comment by Mannsperger** [comment]
Im Feld "About" (https://www.ixtheo-test.de/#)
![about](https://cloud.githubusercontent.com/assets/16759964/15959424/0cd207a8-2efb-11e6-9dfe-c620be1752d4.png)

**Comment by Mannsperger** [comment]
Aus meiner Sicht kann man den ersten Satz nun streichen, da ja nun die Suchtipps auch auf englisch verfügbar sind:
![search tips](https://cloud.githubusercontent.com/assets/16759964/15959587/bff3ed10-2efb-11e6-9d72-04cc04ce1573.png)

**Comment by Mannsperger** [comment]
Die Felder "clear" könnte man in der deutschen Version möglicherweise mit "löschen" wiedergeben.
![clear](https://cloud.githubusercontent.com/assets/16759964/15959760/917ad98e-2efc-11e6-9d38-052c43492980.png)

**Comment by Mannsperger** [comment]
Zum "Browsen über die Ixtheo-Klassifikation" verschiedene Anmerkungen (ich habe grün markiert was ich für gut - und rot markiert was ich für nicht gut erachte):

1.Wäre in der deutschen Version nicht vielleicht auch "nach Kategorien" treffender (englisch: by categories(https://www.ixtheo-test.de/Browse/IxTheo-Classification?findby=alphabetical&category=&query=A*&facet_prefix=A&query_field=ixtheo_notation_facet&facet_field=ixtheo_notation_facet)) als "nach Klassen"(https://www.ixtheo-test.de/Browse/IxTheo-Classification?findby=alphabetical&category=&query=A*&facet_prefix=A&query_field=ixtheo_notation_facet&facet_field=ixtheo_notation_facet)?

2. In der englischen Version fehlen noch Übersetzungen der Oberbegriffe, z.B.: englisch: "ixtheo-A", in der deutschen Version: "A Religionswissenschaft allgemein" 
![nach klassen](https://cloud.githubusercontent.com/assets/16759964/15960228/2730146a-2eff-11e6-9b7d-b78e6aaa0fc4.png)
![by categories](https://cloud.githubusercontent.com/assets/16759964/15960230/2a9bfd76-2eff-11e6-8cf9-8fa9052de6ac.png)

**Comment by Mannsperger** [comment]
Beim Browsen über die Ixtheo-Klassifikation nach Thema (https://www.ixtheo-test.de/Browse/IxTheo-Classification?findby=topic&query_field=topic_facet) erhält man sowohl deutsche als auch englische Begriffe. Z.B. "History" und "christliche Ethik". Sollte das so sein? "Unassigned" wird sonst im deutschen mit "unzugewiesen" wiedergegeben.
![nach thema](https://cloud.githubusercontent.com/assets/16759964/15960425/07b52368-2f00-11e6-9f77-66727eb287d6.png)

**Comment by Mannsperger** [comment]
Auch bei der Suche "nach Thema" wird  bislang mit "unassigned" auch in der deutschen Version betitelt, was sonst im Ixtheo als "unzugewiesen" im Deutschen wiedergegeben wurde:
![nachverlkeinerg](https://cloud.githubusercontent.com/assets/16759964/15960850/06044614-2f02-11e6-9edb-382f428b2a20.png)

Und ist es Absicht, dass auch in der deutschen Version alle Zahlen nach englischem Format (trennen mit Komma statt mit Punkt, z.B.20,022 statt 20.022) angegeben sind?

**Comment by Mannsperger** [comment]
Über "Katalog browsen" bei der Suche nach "DDC-Klassif**ic**ation"(ein Rechtschreibfehler ist hier noch enthalten) erhält man in der deutschen Version nur englische Ergebnisse in den aufgegliederten Kategorien wie zum Beispiel "300 - Sozialwissenschaften"
![englisch in d](https://cloud.githubusercontent.com/assets/16759964/16146362/e54a7d54-347d-11e6-98df-274d56ea8ff9.png)

**Comment by Mannsperger** [comment]
uch bei der Suche "nach Verfasser"/"nach Verlag"-> "nach Thema" wird bislang mit "unassigned" auch in der deutschen Version betitelt, was sonst im Ixtheo als "unzugewiesen" im Deutschen wiedergegeben wurde:
![unassigni](https://cloud.githubusercontent.com/assets/16759964/16146476/86692fe6-347e-11e6-8b8a-6e45822e998e.png)
https://www.ixtheo-test.de/Browse/Publisher?findby=topic&query_field=topic_facet

**Comment by Mannsperger** [comment]
Als "Beschreibung" wird in der dt. Übersetzung "printed material" angezeigt. 
![printed](https://cloud.githubusercontent.com/assets/16759964/16147348/d2e7c43c-3482-11e6-9fca-fd96203a23c6.png)

**Comment by Mannsperger** [comment]
Es scheint so, als sind die Angaben unter "Beschreibung" noch alle englisch:
![beschreibung](https://cloud.githubusercontent.com/assets/16759964/16147655/c26fe98e-3484-11e6-838e-802983cd5459.png)

**Comment by Mannsperger** [comment]
Es scheint so, als seien unter "Beschreibung" die Angaben nicht ins Deutsche übersetzt. Hier z.B. "Videocassette" statt "-kassette"
![cas](https://cloud.githubusercontent.com/assets/16759964/16147787/9d636926-3485-11e6-86f2-2f3c0ea0cd27.png)

**Comment by Mannsperger** [comment]
Auch hier: statt "Braille" müsste hier "Blindenschrift" stehen
![braille](https://cloud.githubusercontent.com/assets/16759964/16147816/e437e3a4-3485-11e6-99a7-dcc095033069.png)

**Comment by Mannsperger** [comment]
Hier findet sich eine deutsche, nicht ins Englische übersetzte Beschreibung (wahrscheinlich, weil sie sehr speziell ist):
![festgabe](https://cloud.githubusercontent.com/assets/16759964/16147919/8c88ff98-3486-11e6-95dc-09860a2306e2.png)

**Comment by Mannsperger** [comment]
Bei "Thema browsen" sind die Begriffe bislang nur deutsch, soweit ich es überblicken kann:
![topic](https://cloud.githubusercontent.com/assets/16759964/16269850/60aab2f6-3894-11e6-9e81-de76fcc0fcb8.png)

**Comment by IxTheoKm** [comment]
Die englischen Übersetzungen sind derzeit noch nicht eingespielt. Die Einspielung aus dem IxTheo für die Normdaten ist in Vorbereitung. Allerdings gibt es nicht für alle Normdatensätze schon englische Übersetzungen.

**Comment by Mannsperger** [comment]
In der französischen Version ist "find topic" noch nicht übersetzt:
https://www.ixtheo-test.de/Search/Advanced
![findtopic](https://cloud.githubusercontent.com/assets/16759964/16994332/36ccd832-4ea7-11e6-8c72-ce662dcd1dfb.png)

**Comment by Mannsperger** [comment]
In der oberen Spalte ist bislang nur "Sprache" in andere Sprachen übersetzt:
![aboutf](https://cloud.githubusercontent.com/assets/16759964/16994430/9c6cc9a4-4ea7-11e6-9a7a-857553398739.png)

**Comment by Mannsperger** [comment]
Unter "Parcourir le catalogue" (Katalog browsen) sind verschiedene Wörter noch nicht französisch, sondern englisch:
![parcourir](https://cloud.githubusercontent.com/assets/16759964/16994719/d6c1fdc6-4ea8-11e6-8ed2-9d504493bb5a.png)

https://www.ixtheo-test.de/Browse/Topic

**Comment by IxTheoKm** [comment]
https://ixtheo-test.de/Record/472863495/Details#tabnav
"Sprache: No linguistic content" für Ressourcen ohne sprachlichen Inhalt ist auf der deutschen Oberfläche in englischer Sprache

**Comment by IxTheoKm** [comment]
Auf der französische Oberfläche ist in der Facette Classification IxTheo die Anzeige von Klammern(?) nicht korrekt: NBM Justification...
https://ixtheo-test.de/Search/Results?join=AND&bool0[]=AND&lookfor0[]=luther%3F&type0[]=AllFields

Der Text nach Aufrufen von "Commentaire" ist englisch

**Comment by thefass** [comment]
> Der Text nach Aufrufen von "Commentaire" ist englisch

Das muss noch übersetzt werden

**Comment by IxTheoKm** [comment]
Im Text "Personnaliser l’utilisation du service " auf der französischen Startseite ist ein Absatz in deutscher Sprache stehen geblieben, der nur gestrichen werden muss. Die Übersetzung dafür ist vorhanden.

**Comment by IxTheoKm** [comment]
Müssten nicht auch die Begriffs für die Online-Zugriffe "Inhaltstext", "Inhaltsverzeichnis", Klappentext", "Rezension" usw. aus Feld 856 |3 in die jeweiligen Sprachen übersetzt werden?
Auf Seite 5 des Dokuments http://www.dnb.de/SharedDocs/Downloads/DE/DNB/wir/agVerbundKataloganreicherungsobjekte2010.pdf stehen die möglichen Begriffe.

**Comment by mtrojan-ub** [comment]
> Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a. folgende Funktionen zur Verfügung:

@IxTheoKm : "Die Übersetzung dafür ist vorhanden" => sie liegt uns leider nicht vor. Können Sie mir diese bitte zukommen lassen? Dann pflege ich ihn gerne ein.

**Comment by IxTheoKm** [comment]
Gemeint ist, dass nur der deutsche Absatz in dem vorhandenen Text gestrichen werden muss.
Dieser Absatz ist in dem vorhandenen französischen Text schon vorhanden (siehe Fettdruck):

Plusieurs fonctions utiles sont offertes aux détenteurs d’un compte IxTheo. Une fois inscrit, vous pouvez accéder à votre compte en cliquant sur le lien »Connexion» au coin supérieur droit. **Un clic sur »Votre compte» vous amène à la page de gestion de vos données. Vous avez alors accès aux fonctions suivantes :**

**Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a. folgende Funktionen zur Verfügung:** [<- Diesen Satz bitte nur streichen]

**Comment by mtrojan-ub** [comment]
Danke für die Erläuterung! Der Satz wurde auf ptah entfernt. Ich habe bei der Gelegenheit auch gleich ein paar falsche Anführungszeichen korrigiert.

**Comment by mtrojan-ub** [comment]
Der Issue ist ziemlich groß und es ist schwierig den Überblick zu behalten.

Ich fasse mal zusammen was von den oben genannten Themen noch offen ist:

* Beschreibungen
*- Printed Material
*- Videocasette
*- Braille
* Rechts oben: Nur Login/Language übersetzt (nicht home/about)
* "Naviguer dans le catalogue" => Classification IxTheo => par sujet
* No linguistic content
* Text nach Aufrufen von "Commentaire" ist Englisch
* (Begriff für die Online-Zugriffe)

Neue Dinge bitte unbedingt in separaten Issues melden, es wird sonst zu unübersichtlich

**Comment by mtrojan-ub** [comment]
Geschlossen in Rücksprache mit IxTheoKm, für alles was noch immer offen ist gibts neue Issues
