### ISSUE TITLE
Fehlermeldung Schlagwörter zum Themenbereich "Bibel"

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/ixTheo#71]
Gerade wollte ich zum Vergleich von WinIBW und VuFind über die Schlagwortsuche die Ergebnisse des Schlagworts "Bibel" vergleichen.
Es erscheint die gleiche Fehlermeldung, wie wenn man gerade versucht, über "Bible Range" zu suchen.
![bible range suche](https://cloud.githubusercontent.com/assets/16759964/12673293/16860b24-c67c-11e5-847c-c333787aa257.png) 
Schlagworte, die zu Bibelstellen gehören könnten wie Markus, Johannesevangelium oder Genesis erzeugen auch die Fehlermeldung.
Ander Schlagworte (z.B. Kant oder Soteriologie) liefern Ergebnisse.

**Comment by oobenland** [comment]
Sollte behoben sein.

**Comment by Mannsperger** [comment]
Wahrscheinlich arbeitet ihr gerade an der Bibelstellensuche, denn im Moment funktioniert sie nicht, aber noch vor ca. 30 min.

Aber auch zu dieser Zeit funktionierte der Operator "AND" nicht.
Es funktionierte aber problemlos, nach Psalm 22 und Mk 15 jeweils separat zu suchen, nur nicht in Kombination durch AND.

**Comment by oobenland** [comment]
Die Bibelstellensuche ist leider sehr eingeschränkt in ihrer Möglichkeit. Man kann nur eine einzelne Bibelstelle suchen. Operatoren werde nicht unterstützt.
