### ISSUE TITLE
Sortierung der Ergebnisanzeige der Schlagwortfolgen

### ISSUE THREAD

**Issue by jriedl** [ubtue/ixTheo#76]
Die Sortierung der Schlagwortfolgen liefert nun Ergebnisse, bei der Ketten mit dem gleichem Anfang alphabetisch zusammenliegen. Auf eine Sortierung anhand der Anzahl der Terme innerhalb der Kette habe ich jetzt verzichtet, da es einerseits sehr ressourcenintensiv wäre und wir nach einer internen Diskussion zu dem Ergebnis gekommen sind, dass das auch dazu führen kann, dass Ergebnisse sich an nicht intuitiv auffindbarer Stellen verschoben werden @ubtue/ixtheo

**Comment by thefass** [comment]
wenn ich das richtig sehe, dann sind SW-Folgen mit gleichem Anfang alphabetisch sortiert. Das ist gut so.

**Comment by thefass** [comment]
Was ist der Unterschied zwischen der Suche nach a und nach a*.
Warum kommen da unterschiedliche Ergebnismengen?

**Comment by jriedl** [comment]
Eine Suche nach 'a' liefert als Ergebnismenge Felder, in denen 'a' als einzelner Token (Token = das Ergebnis des "Zerhackens" der Felder in kleinere Einheiten nach bestimmten Regeln, z.B. Trennung bei Leerzeichen, Sonderzeichen wie Slash, Punkt, Minus etc. und stellt die eigentliche interne Repräsentation der Daten für eine Solr-Suche dar) vorkommt, eine Suche nach 'a*' liefert alle Ergebnisse als Treffer, bei denen ein Token mit 'a' anfängt.

**Comment by IxTheoKm** [comment]
Die alphabetische Sortierung klappt nicht zuverlässig.
s. vorletzte Zeile: 
Tübingen ...
Tür ...
Tübinger ...
![issue_76](https://cloud.githubusercontent.com/assets/17004223/13080877/da3956be-d4ca-11e5-8be8-811b9ce7572a.jpg)

**Comment by thefass** [comment]
Umlaute und Sonderzeichenwerden erst am Ende einsortiert. Das ist problematisch
Beispiel: 
Aufsatzsammlung / Zölibat
Aufsatzsammlung / al- Manār
Aufsatzsammlung / Ägypten (Altertum)

Link: https://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Results?lookfor=%22Aufsatzsammlung%22&type=keywordChainSearch&page=1959

**Comment by jriedl** [comment]
Die Sortierung wurde angepasst und entspricht jetzt der deutschen Sortierrreihenfolge

**Comment by thefass** [comment]
Ich glaube, das müssen wir nochmal dikutieren:
https://ptah.ub.uni-tuebingen.de/KeywordChainSearch/Results?lookfor=Aufsatzsammlung+%2F+%C3%84g*&type=KeywordChainSearch

die alphabetische Sortierung wird durchbrochen durch die Sortierung nach der Anzahl der Terme. Bin mir nicht sicher, ob das sinnvoll ist.

**Comment by jriedl** [comment]
Ok, dann finden wir hoffentlich bei der nächsten Gelegenheit eine für alle Seiten zufriedenstellende Lösung.

**Comment by thefass** [comment]
ist ok so
