### ISSUE TITLE
Datenstand

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#80]
Für die Tests vorweg eine Frage, um zu bewerten, ob die Daten vollständig sind: 
welchen Datenstand hat der VuFind-IxTheo?
Aber selbst davon scheint es nicht abzuhängen, dass manche relevanten mteo-Titel im SWB nicht im IxTheo gelandet sind (gerade kurz mit dem Suchfilter „Objekt“ verifiziert).

**Comment by oobenland** [comment]
@thefass Könntest du das beantworten?

**Comment by thefass** [comment]
Frage verschoben auf interne Mailingliste
