### ISSUE TITLE
Werktitel/Bibelstellen/Schlagwortteile fehlen in der Anzeige und sind nicht recherchierbar 

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#81]
In der Titelanzeige steht bei Schlagwortfolge nur das verbal erfasste Formschlagwort aus 689 |a
Das verknüpfte Schlagwort aus 689 |d fehlt.
Bsp.: PPN 121955494, 049848062

In anderen Fällen funktioniert zum Teil die vollständige Anzeige:
Bsp.: PPN 041743296, 040466213
Dort fehlen aber die zweite Schlagwortfolge bzw. ein Schlagwort aus der zweiten Schlagwortfolge

Es sind immer Werktitel, die fehlen

**Comment by IxTheoKm** [comment]
Die Schlagwörter selber werden auch nicht vollständig angezeigt und sind nicht vollständig recherchierbar:

PPN 040466213
689 	0 	0 	|d g  |0 (DE-588)4072956-4  |0 (DE-576)209188804  |2 gnd  **|a Israel  |9 g:Altertum**
"Altertum" fehlt in der Anzeige

PPN 347489117
689 	0 	0 	|d p  |0 (DE-588)11872942X  |0 (DE-576)166502820  |2 gnd  |**a Ludwig  |b XIII.  |c Frankreich, König**
Hier bleibt auch nur Ludwig in der Anzeige übrig.

**Comment by ruschein** [comment]
On 04/02/16 10:15, IxTheoKm wrote:
>
> Die Schlagwörter selber werden auch nicht vollständig angezeigt und
> sind nicht vollständig recherchierbar:
>
> PPN 040466213
> 689 0 0 |d g |0 (DE-588)4072956-4 |0 (DE-576)209188804 |2 gnd *|a
> Israel |9 g:Altertum*
> "Altertum" fehlt in der Anzeige
>
Wie soll das angezeigt werden. z.B.:

1. Israel/Altertum/...
2. Israel Altertum/...
3. Israel (Alterturm)/...
4. ???

> PPN 347489117
> 689 0 0 |d p |0 (DE-588)11872942X |0 (DE-576)166502820 |2 gnd |*a
> Ludwig |b XIII. |c Frankreich, König*
> Hier bleibt auch nur Ludwig in der Anzeige übrig.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/81#issuecomment-179725404>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by IxTheoKm** [comment]
Die korrekte Anzeigeform ist   Israel <Altertum>

**Comment by ruschein** [comment]
On 04/02/16 12:27, IxTheoKm wrote:
>
> Die korrekte Anzeigeform ist Israel
>
Dann ist ja alles OK wie wir es jetzt schon machen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/81#issuecomment-179781351>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by IxTheoKm** [comment]
Sorry, ich hatte "Altertum" in Winkelklammer gesetzt. Das war die bisherige Form. Die Zeichen sind wohl nicht darstellbar.
Ich habe bei der DNB nachgesehen: die macht "Israel (Altertum)".
Das heißt, Ihre Variante 3 bitte!

**Comment by ruschein** [comment]
On 04/02/16 10:15, IxTheoKm wrote:
>
> Die Schlagwörter selber werden auch nicht vollständig angezeigt und
> sind nicht vollständig recherchierbar:
>
> PPN 040466213
> 689 0 0 |d g |0 (DE-588)4072956-4 |0 (DE-576)209188804 |2 gnd *|a
> Israel |9 g:Altertum*
> "Altertum" fehlt in der Anzeige
>
> PPN 347489117
> 689 0 0 |d p |0 (DE-588)11872942X |0 (DE-576)166502820 |2 gnd |*a
> Ludwig |b XIII. |c Frankreich, König*
>
*Hatte leider vergessen wie wir das schreiben sollen.

Ludwig, XIII., Frankreich., König   ???
*
>
> Hier bleibt auch nur Ludwig in der Anzeige übrig.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/81#issuecomment-179725404>.
>

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by IxTheoKm** [comment]
Sorry, hätte ich auch gleich dran denken können:
ja, das ist korrekt. Bei den Personen werden Zählungen usw. jeweils mit Komma getrennt

**Comment by IxTheoKm** [comment]
Problem ist nicht ganz behoben. Bei PPN 041743296 wird die zweite Schlagwortfolge nicht angezeigt, nur der Button "B".
689 	1 	0 	|D u  |0 (DE-588)4073016-5  |0 (DE-576)209188995  |2 gnd  |t Bibel  |p Jeremia

**Comment by IxTheoKm** [comment]
Problem scheint noch nicht überall behoben zu sein:
https://www.ixtheo.de/Record/466171439#details
Die Unterfelder werden nicht angezeigt und sind nicht recherchierbar

150 $aDRK$9g:**Wortstamm**   
450 $adārak$9g:**Verb**

![drk_wortstamm](https://user-images.githubusercontent.com/17004223/31810814-64dc0d90-b57d-11e7-8e30-d18fdeb14ce3.png)

**Comment by thefass** [comment]
ist ok
