### ISSUE TITLE
Fehlende Verlinkung zwischen über- und untergeordneten Werken

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#82]
Wo sind die "untergeordneten Datensätze" von Zeitschriften, Schriftenreihen oder Monographien?
Ich bekomme bei der übergeordneten Aufnahme keinen Hinweis auf die daran hängenden Bände oder Aufsätze.
Umgekehrt bekomme ich von den untergeordneten Aufnahmen keinen Hinweis darauf, in welchem Band/Heft dieser Beitrag oder dieses Buch erschienen ist.

**Comment by oobenland** [comment]
Beim Browsen geht es eher um eine thematische Unterteilung, die nach Häufigkeit sortiert ist.
Das heißt, wenn man wissen möchte, welche Verfasser eine Predigt geschrieben hat, dann findet man das unter Verfasser > Nach Thema > Predikt. So gruppiert man die Verfasser nach einem Thema. Eine Sortierung ist das aber nicht.
Alphabetisch bedeutet nur, dass man den jeweiligen Verfasser nach dem Anfangsbuchstaben gruppiert.

**Comment by thefass** [comment]
Ja, das ist super wichtig: hohe Priorität

**Comment by IxTheoKm** [comment]
Im Internformat finde ich nun einige untergeordnete Werke unter CLD.
Es sind aber nur sehr wenige. Vgl. Theologische Literaturzeitung 001 014414023.
Hierfür gibt es mindestens 35.000 untergeordnete Titel mit mteo (insgesamt ca. 47.000 untergeordnete Sätze)

**Comment by IxTheoKm** [comment]
https://ptah.ub.uni-tuebingen.de/Record/405847572
@thefass Ist die Zählungsangabe schon besprochen?

"Year: ..., Jahrgang: ..., Heft: ..., Pages: ..."
sieht sehr merkwürdig aus.

Normalerweise sind es "Jahrgang, Erscheinungsjahr, Heft, Seiten"
Statt Jahrgang kann es auch "Band" heißen

**Comment by IxTheoKm** [comment]
Nach Rücksprache mit thefass zur Info:
Verknüpfung des untergeordneten Werks (Artikel) zum übergeordneten Werk (Zeitschrift oder Monographie) in _773 $w(DE-576)_

Bsp. ID 416104584 Artikel in einer Zeitschrift:
773 0 $iIn$d2014$g38(2014), 4, S. 163-173$x1431-200x$w(DE-576)015208249

DE-576 = BSZ bzw. SWB-Verbund
015208249 = ID des übergeordneten Werks (Zeitschriftengesamtaufnahme)

Im Datensatz 015208249 gibt es keine Verlinkung zu den untergeordneten Datensätzen.

----------------------------------------------------------------------------------------------------------------------------------
Bsp. ID 384336159 Artikel in einer Monographie:
773 0 $iIn$d2013$g(2013), S. 99-125$w(DE-576)382683099

----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
Verknüpfung des untergeordneten Werks (Band) zum übergeordneten Werk (Zeitschrift oder Schriftenreihe) in _773 $w oder 800 $w oder 810 $w oder 830 $w_

-----------------------------------------------------------------------------------------------------------------------------------
Bsp. ID 429487401 unselbständiger Bandsatz an einer Zeitschrift:
773 18$w(DE-576)015208249$g39,2

-----------------------------------------------------------------------------------------------------------------------------------
Bsp. ID 398082456 einbändiger Stücktitel an einer Zeitschrift:
830 0$aHomiletisch-liturgisches Korrespondenzblatt$q1030$v30 = 112/113$w(DE-576)015712052

-----------------------------------------------------------------------------------------------------------------------------------
Bsp. ID 365089222 mehrere Überordnungen:
773 18$w(DE-576)362428360$g3
810 2 $aUniversità del Salento$bFacoltà di Giurisprudenza$tCollana della Facoltà di Giurisprudenza, Università del Salento$q1018,3$vN.S., 18$w(DE-576)345035186

-----------------------------------------------------------------------------------------------------------------------------------
Es fehlen noch die Beispiele für untergeordnete Sätze bei mehrteiligen Mononographien!

**Comment by IxTheoKm** [comment]
Ergänzung:
habe die Beispiele im SWB überprüft: die Verknüpfungsfelder für mehrteilige Monographien sind dieselben.
Bsp. ID 378124242
PICA
4160 !32649135X!Briefe / $PTeresa$lde Jesús*1515-1582*$l3
4165 !098288032!Gesammelte Werke / $PTeresa$lde Jesús*1515-1582*$l8
4180 !02400474X!Herder-Spektrum$l6311
MARC
773 18$w(DE-576)32649135X$g3
800 0 $aTeresa$cde Jesús$d1515-1582$tGesammelte Werke.$g8$w(DE-576)098288032
830 0$aHerder-Spektrum$v6311$w(DE-576)02400474X

**Comment by thefass** [comment]
die Über- und Unterordnung Verknüpfung ist implementiert
@IxTheoKm :: bitte die Beispiele von oben prüfen

**Comment by thefass** [comment]
@oobenland :: ein Beispiel für eine Schriftenreihe:
https://ptah.ub.uni-tuebingen.de/Record/01447350X

Hier funktioniert die Verknüpfung zu den untergeordneten Werken noch nicht

PPN eines untergeordneten Werkes, das zu dieser Schriftenreihe gehört: 444462643
(insgesamt sind es 265 untergeordnete Werke)
https://ptah.ub.uni-tuebingen.de/Record/444462643

siehe obige Definitionen von Frau Kellmeyer:
**_"Verknüpfung des untergeordneten Werks (Band) zum übergeordneten Werk (Zeitschrift oder Schriftenreihe) in 773 $w oder 800 $w oder 810 $w oder 830 $w"_**

**Comment by IxTheoKm** [comment]
Weiteres Beispiel für eine Schriftenreihe:
830 		0 	|a Herders biblische Studien  |v 18  |w (DE-576)04111759X

**Comment by thefass** [comment]
Die Verknüpfung geht nicht mehr mit dem neuen Code
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:014895846

**Comment by IxTheoKm** [comment]
Verlinkung zwischen über- und untergeordneten Werken funktioniert jetzt
