### ISSUE TITLE
Katalog browsen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#83]
Die Browsing-Funktion finde ich ziemlich undurchsichtig.
Lediglich die alphabetische Sortierung erklärt sich von alleine. Allerdings ist das Ergebnis dann _nicht _ alphabetisch geordnet.

**Comment by oobenland** [comment]
Beim Browsen geht es eher um eine thematische Unterteilung, die nach Häufigkeit sortiert ist.
Das heißt, wenn man wissen möchte, welche Verfasser eine Predigt geschrieben hat, dann findet man das unter Verfasser > Nach Thema > Predikt. So gruppiert man die Verfasser nach einem Thema. Eine Sortierung ist das aber nicht.
Alphabetisch bedeutet nur, dass man den jeweiligen Verfasser nach dem Anfangsbuchstaben gruppiert.

**Comment by IxTheoKm** [comment]
Na ja, wenn ein Nutzer aber aus dem "Angebot" wählt _Verfasser > Alphabetisch > [Buchstabe]_ wird er keine thematische Unterteilung, sondern eine alphabetisch geordnete Liste erwarten.
Die ist dann wohl aber unter "Weitere Suchoptionen", "Alphabetisch browsen" zu finden (was derzeit nicht funktioniert), richtig?

Wenn ich bei Katalog browsen einsteige mit _Thema_, habe ich nur die Auswahl _Alphabetisch_
Dann muss ich von oben bis unten den Buchstaben oder auch die Zahl durchsuchen, ob mein gesuchter Begriff irgendwo dazwischen steht.  

Wenn ich bei _Verfasser_ einsteige, bekomme ich die merkwürdige Auswahl _Nach Verfasser_ (mit anschließender Anzeige der Verlage).

Wenn ich bei _IxTheo-Notation_ einsteige und _Verfasser_ auswähle, werden auch Verlage angezeigt.

Das meine ich mit undurchsichtig. Ist das so gewollt?

Nach Häufigkeit sortiert heißt dann auch, dass die Treffer nicht vollständig angezeigt werden, richtig?

**Comment by oobenland** [comment]
Verfasser > Nach Verfasser ist ein Übersetzungsfehler. Das ist nach Verlag.
Das Problem ist, dass eine alphabetische Sortierung keinen Sinn mach, da maximal 100 Einträge angezeigt werden. Da wir zurzeit 6200 Autoren mit A haben wäre der letzte angezeigte Autor ʿAbbād.
Deshalb ist es nach Häufigkeit sortiert, da es wahrscheinlicher ist, dass jemand sich für einen Autoren interessiert, der viel geschrieben hat. Hätte man den Namen eines Autors schon im Kopf, dann könnte man einfach nach dem Namen suchen und muss nicht browsen.

Es ist geplant, dass das Browsen sowie die Facetten-Anzeigen bei der Suche erweitert werden. Jedoch haben wir entschieden, dass das ein Feature mit sehr niedriger Priorität ist.

**Comment by thefass** [comment]
Momentan ist das zurückgestellt, das stimmt. Es ist aber von hoher Bedeutung für alle Browsing Listen und auch für die Facetten. Es ist deswegen von hoher Bedeutung, da das die wissenschaftlichen Nutzer als erstes monieren werden, denn dahinter steckt ja ein Sachproblem.
