### ISSUE TITLE
Facette "Format"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#87]
Wenn ich die Daten richtig verstehe, stecken hier die "physischen Einheiten".
In den marc.properties mit "physical" bezeichnet? Also die Felder 300abcefg:530abcd ?

Fließen hier auch die Abrufzeichen 935... für Datenträgertypen ein?

**Comment by ruschein** [comment]
Das sollte sich mit der BSZ-Konkordanz beantworten lassen: https://wiki.bsz-bw.de/doku.php?id=v-team:daten:datendienste:marc21#marc_21-tabellen
