### ISSUE TITLE
Blättern in einer Treffermenge

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#88]
Gibt es keine Möglichkeit in einer kleineren Treffermenge nach dem Aufrufen eines Treffers _direkt_ weiter zu blättern? 
Momentan kann ich scheinbar nur mit dem Zurück-Pfeil im Browser auf die Kurzliste zurück gehen und dort den nächsten Treffer aufrufen, und wieder zurück, und den nächsten ... usf.

**Comment by oobenland** [comment]
Ich habe noch nichts gesehen, was darauf hinweist, dass diese Funktionalität im Standard VuFind existiert. Wenn du ein VuFind-Katalog kennst, welches das kann, dann können wir uns gerne mit dem Katalog in Verbindung setzen, in der Hoffnung das Nachnutzen zu dürfen.

**Comment by thefass** [comment]
Das sollten wir in der nächsten Sitzung besprechen. Könnte auch so gelöst werden wie im Ub Katalog plus, wo die Langanzeige nicht auf einer weiteren Seite aufgeht, sondern als eine Erweiterung in der Kurztitelseite selbst

**Comment by IxTheoKm** [comment]
Drei Beispiele (evtl. gibt es mehr?):
https://katalog.hmt-leipzig.de/Record/0000072976
https://katalog.tub.tu-harburg.de/Record/737241500
https://katalog.fh-erfurt.de/vufind-gbv/Record/507133005

Über dem Titel sind Pfeile bzw. "nächster" zum Durchblättern der Treffermenge

**Comment by socheres** [comment]
hier noch ein Bsp.:https://lobid.org/nwbib/HT018574551

**Comment by socheres** [comment]
in Vufind gibt es ein Plugin "ResultScroller". Bitte implementieren: vufind/module/VuFind/src/VuFind/Controller/Plugin/ResultScroller.php

**Comment by ruschein** [comment]
Ist behoben.

**Comment by thefass** [comment]
gelöst. Bitte Issue schließen
