### ISSUE TITLE
Nur das erste Abrufzeichen fließt in die Facetten ein

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#91]
Wenn wiederholbare Abrufzeichen in 935 $b erfasst werden, wird nur das erste für die Facetten berücksichtigt.
Bsp.:
PPN 114756457
935 $bsott$bdias

PPN 250388197
935 $btonbd$bdias

(PPN 074613545 finde ich gar nicht. Nicht geliefert?)

**Comment by ruschein** [comment]
Wir werten 935 bisher überhaupt nicht aus.

**Comment by IxTheoKm** [comment]
Dann also doch nur 300abcefg:530abcd ? (s. Issue #87)
Der BSZ-Tabelle kann ich die Auswertung leider nicht entnehmen, nur die Existenz der Felder.

935 enthält die normierten Abrufzeichen. Warum werden die nicht (auch) ausgewertet? Ich dachte, die werden zu diesem Zweck erfasst.

**Comment by ruschein** [comment]
On 08/02/16 16:04, IxTheoKm wrote:
> Dann also doch nur 300abcefg:530abcd ? (s. Issue #87
> <https://github.com/ubtue/ixTheo/issues/87>)
> Der BSZ-Tabelle kann ich die Auswertung leider nicht entnehmen, nur die
> Existenz der Felder.
> 
> 935 enthält die normierten Abrufzeichen. Warum werden die nicht (auch)

Wo kann ich diese Norm einsehen?  Ich muss die Kürzel vermutlich auf
englische Terminologie übersetzen damit die Übersetzungsmachinerie in
VuFind funktionieren kann.

> ausgewertet? Ich dachte, die werden zu diesem Zweck erfasst.

Es ist wohl noch niemanden aufgefallen.  Deshalb brauche wir Sie ja gerade.

> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubtue/ixTheo/issues/91#issuecomment-181402651>.
> 

-- 
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

**Comment by thefass** [comment]
Bitte in diesem Zusammenhang das Issue #36 (Header :: an Position 07: a) beachten

**Comment by ruschein** [comment]
Sollte jetzt behoben sein.

**Comment by IxTheoKm** [comment]
Test ist erst nach einer neuen Gesamtlieferung sinnvoll:
es sind zu viele mteo-Titel nicht vorhanden.

**Comment by IxTheoKm** [comment]
Die ersten beiden Titel sind zwar im VuFind nachgewiesen, unter "Dia" finde ich sie immer noch nicht.
Der dritte Titel PPN 074613545 ist immer noch nicht vorhanden

**Comment by IxTheoKm** [comment]
Hat es nicht inzwischen eine neue Gesamtlieferung gegeben?
Stand ist unverändert: Titel PPN 074613545 fehlt weiter, die anderen beiden stecken nicht bei 'Dia'

**Comment by thefass** [comment]
Die ersten beiden sind m.E. nun in der Facette Dia enthalten. 
Das dritte Beispiel, das gar nicht gefunden wird, hat mit den Facettenproblematik nichts zu tun.
@IxTheoKm Kann das Issue geschlossen werden? Evt. neues wegen PPN 074613545 anlegen.

**Comment by IxTheoKm** [comment]
Jetzt o.k. Titel ppn 074613545 wurde inszwischen gelöscht
