### ISSUE TITLE
Falsche Autoreninformation aus Wikipedia

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/ixTheo#96]
Vgl. Autorenrecherche Weber, Dieter

Nach Anklicken von Weber, Dieter 1960- bekomme ich die falschen Informationen und den falschen Link nach Wikipedia:
Den 1939 geborenen DDR-Fußballer.
Der Theologe existiert in Wikipedia nicht.
-->
Die Informationen aus Wikipedia sollten nur über die GND-Nummer geholt werden.

Wie wird die Bildauswahl vorgenommen?
Beim Beispiel Küng, Hans finde ich das Bild ziemlich unglücklich (rhetorische Frage: wer von den dreien ist Hans Küng?)

**Comment by thefass** [comment]
oder Karl Löning:
https://ptah.ub.uni-tuebingen.de/Author/Home?author=L%C3%B6ning%2C+Karl
ist leider der falsche. Der richtige ist nicht in der Wikipedia.
IxTheoKm hat recht: nur über die GND Nummer in der Wikipedia einbinden:
Beispiel: Zenger, Erich:
https://de.wikipedia.org/wiki/Erich_Zenger
ganz runterscrollen, vorletzter Absatz: Normdaten

**Comment by thefass** [comment]
Es wäre aus meiner Sicht besser, wenn der Klick auf den Link der Personen wirklich zum Wikipediaartikel führen würde. Momentan löst er eine weitere Suche aus. Das ist auch gut, sollte aber beides möglich sein:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=albright%2C+william&type=Author&limit=10&sort=relevance
Weiterführung zu Wikipedia vielleicht durch ein Icon 

Bei manchen Namen kommt etwas vorn der Wikipedia, bei anderen nicht. Woran liegt das?
Anzeige kommt bei: Albright, Madeleine 1937-
nicht aber bei: Albright, William Foxwell 1891 - 1971
obwohl beide in der Wikipedia sind

**Comment by oobenland** [comment]
Wie sucht man bei Wikipedia mit der GND?

**Comment by IxTheoKm** [comment]
Hier ist ein Hinweis:
https://de.wikipedia.org/wiki/Hilfe:GND#Download_und_Verlinkung_auf_die_Wikipedia

**Comment by thefass** [comment]
das ganze funktioniert anscheinend auch mit der englischsprachigen Wikipedia. Dort werden mittlerweile auch die Normdaten in Artikeln eingetragen. Normdaten heißen im englischen authority files:
http://tools.wmflabs.org/persondata/redirect/gnd/en/118768581
Wenn ich das richtig sehe, dann ist der einzige Unterschied in der Adresse das en.

**Comment by thefass** [comment]
kann das sprachabhängig angeboten werden?
also bei deutscher Sprachauswahl Verlinkung auf die deut. Wikipedia,
bei allen anderen Spracheinstellungen (erstmal) auf die eng. Wikipedia.
(Die Einbindung der Normdaten in den anderen Srachversionen der Wikipedia ist noch nicht so weit vorangeschritten)

**Comment by oobenland** [comment]
Die Auswahl der Sprache sollte keine Probleme machen. Aber die Änderung des Wikipedia-Plugins mit der GND ist umständlich. Zurzeit wird der Name des Autors direkt an die Wikipedia-URL angehängt. Informationen über die GND des Autors liegen nicht vor.
Unsere Einschätzung ist, dass die Umsetzung aufwändig ist und somit zurück gestellt werden sollte. Je nach dem müssen wir das nochmal besprechen.

**Comment by thefass** [comment]
Dann sollten wir das rausnehmen, bis es umgesetzt werden kann. Das feature ist schon wichtig und auch innovativ. Wenn es aber zu falschen Personen führt, ist es aber blamabel.
Nehmen wir auf unsere Besprechungsliste am Montag

**Comment by oobenland** [comment]
Ist deaktiviert.

**Comment by thefass** [comment]
Das Thema greifen wir in der zweiten Förderperiode auf
