### ISSUE TITLE
JOP - falsche Anzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/ixTheo#99]
Schaut Euch bitte mal diesen Titel aus der Zeitschrift "Stimmen der Zeit" an:
https://ptah.ub.uni-tuebingen.de/Record/425590445

Dort heißt es von JOP: available online
Wenn man darauf klickt, kommt man auf Archiv.org, auf dem die Bände der Vorgängerzeitschrift von "Stimmern der Zeit" mit dem Titel "Stimmen aus Maria Laach". Das sind aber Bände vor 1914 (archiviert 2008). Der obige Beitrag ist aber aus 2015. Die Info "available" ist also falsch.
Wenn man den Beitrag im alten IxTheo sucht, dann bekommt man die richtige JOP Info:
http://services.dnb.de/fize-service/gvr/html-service.htm?atitle=die%20entdeckung%20der%20subjektivitaet&aufirst=georg&aulast=sans&genre=article&sid=ixtheo&title=stimmen%20der%20zeit&issn=0039-1492&date=2015&volume=233&issue=2&spage=87&epage=94&pid=zdbid%3D205159-x%26bibid%3DUBTUE

Mir ist also nicht klar, wie die JOP Aussage "available" in ptah zustande kommt

**Comment by jriedl** [comment]
Es werden jetzt zusätzliche Daten für die Identifikation verwendet und ausgewertet. Nach dem nächsten Neueinspielen der Daten sollte das Verhalten wie gewünscht sein.

**Comment by oobenland** [comment]
Inzwischen ist die Einspielung durchgelaufen und die Anzeige hat sich geändert.

**Comment by socheres** [comment]
keine JOP-Anzeige bei mehreren Aufsatztitel in Record-Ansicht: https://ptah.ub.uni-tuebingen.de/Record/425096327
Bitte prüfen!

**Comment by jriedl** [comment]
Die Artikel sollten jetzt beim Import richtig kategorisiert und damit JOP auch das gewünschte Verhalten zeigen.

**Comment by thefass** [comment]
Bei diesem Artikel sieht man kurz die Anzeige, dass JOP geladen wird, dann ist das Feld aber einfach leer.
https://ptah.ub.uni-tuebingen.de/Record/103282025

**Comment by oobenland** [comment]
Das ist jetzt schwierig. Du testest gerade von zu hause? Ich habe eine VPN-Verbindung ins Uni-Lan und bekomme ein gutes Ergebnis.

**Comment by thefass** [comment]
ja, von zuhause und ohne VPN
Muss auch ohne VPN funktionieren, da unsere Nutzer aus der ganzen Welt kommen

**Comment by jriedl** [comment]
JOP versucht mittels der übertragenen IP-Adresse zu ermitteln, von welcher Institution eine Anfrage kommt, und generiert anhand dessen die Verfügbarkeitsanzeige. Derzeit wird die Adresse des anfragenden Clients verwendet. Die leere Anzeige erfolgt, wenn für die ermittelte Institution weder Print- oder Onlinebestände verfügbar sind. Es besteht die Möglichkeit, grundsätzlich die Serveradresse zu verwenden, man bekommt dann unabhängig von Ort des Zugriffs die Tübinger Bestände.

**Comment by jriedl** [comment]
Nachtrag und Präzisierung: Das Problem ist, dass dann in den Icons und in der Verfügbarkeitszeige in VuFind Daten angezeigt werden, die eigentlich nicht stimmen. Denn beim Klick auf die JOP-Icons wird die JOP-Seite ja direkt mit der IP des Clients aufgerufen und spätestens hier greift die Zugriffskontrolle von JOP.

**Comment by thefass** [comment]
die Serveradresse von Tübingen einzutragen halte ich nicht für sinnvoll.
Im jetzigen IxTheo wird auch nichts angezeigt, wenn die IP nicht ermittelt werden kann. In der vollanzeige ist dann aber einfach ein Link ( und nicht die Icons, die wie Du richtig anmerkst, ja schon ein Ergebnis anzeigen). Wenn man den anklickt, dann fragt er nach, welche Institution man auswählen will. Das ist praktisch, wenn man nicht vor Ort ist und trotzdem auf seine Heimatuni zugreifen will.
Könnte das so gelöst werden, dass bei nicht Erkennung einer IP anstelle der Icons ein Link erscheint:
"Verfügbarkeit prüfen"?
Oder gibt es vielleicht für diesen Fall graue Icons?

**Comment by jriedl** [comment]
Die Icons werden als gif geliefert und auch wenn nichts angezeigt wird, ist dort ein 1x1 Pixel großes gif. Falls die Abfrage bei JOP fehlschlägt, ist jetzt unter "Verfügbarkeit prüfen" der Link auf die JOP Seite

**Comment by thefass** [comment]
funktioniert. Danke
